### ISSUE TITLE
Android build

### ISSUE THREAD

**Issue by luben** [luben/zstd-jni#10]
We will need separate build for Android

**Comment by shaheenkdr** [comment]
Does the library use Scala ?

**Comment by luben** [comment]
No, only the tests use scala

**Comment by davidarchi** [comment]
when will you release new version for Android building ?
Thanks

**Comment by luben** [comment]
Unfortunately I don't have any experience building software for Android and I am not familiar what are the best practices and the preferred ways for building, packing and distribution of JNI jars. I guess an Android build/packaging will not need any code changes as there is nothing unusual in the code itself.

It would be great if somebody with more experience in this area take a look.

**Comment by shaheenkdr** [comment]
The problem is I started with Android development, I do not have any prior experience with C/CPP in a wider level. And I tried building it here in Android, however, there were multiple issues, primarily, Android studio even fails to resolve some header files included in this project.

**Comment by davidarchi** [comment]
I am looking for this lib in android studio.
Can any one with much experience help to build in android ?

**Comment by Cl1608Ho** [comment]
https://github.com/monstertoss/zstd-android

have a lib here, its as simple as including it as android studio module

**Comment by luben** [comment]
Android build is now available and supported. If you have suggestions about the distribution model, please give and advice in #54
