### ISSUE TITLE
Small records compression support for zstd-jni

### ISSUE THREAD

**Issue by sudoa** [luben/zstd-jni#100]
Hi, I'm wondering if zstd-jni supports bulk processing library and explicit context. The [zstd manual ](https://facebook.github.io/zstd/zstd_manual.html#Chapter6) mentioned that using explicit compression context and a pre-generated digested dictionary when compressing many small records is more memory friendly. I didn't not find 
`size_t ZSTD_compress_usingCDict(ZSTD_CCtx* cctx,
                                void* dst, size_t dstCapacity,
                          const void* src, size_t srcSize,
                          const ZSTD_CDict* cdict);`
in the java binding implementation. Is there a plan to support it soon?

**Comment by luben** [comment]
Yes, there is PR #99 in progress that addresses the context reuse.

**Comment by luben** [comment]
The most recent version adds ability to reuse contexts when compressing/decompressing direct byte buffers. Compression/decompression of byte arrays will come in the next versions. Please look at the ZstdCompressCtx/ZstdDecompressCtx. If you are looking to only reuse dictionaries, it's already supported though:

```java
compress(byte[] dst, byte[] src, ZstdDictCompress dict)
decompress(byte[] src, ZstdDictDecompress dict, int originalSize)
```
and similar functions.

**Comment by luben** [comment]
Hi, I just pushed v1.4.4-5 to Maven. I think everything needed is in `ZstdCompressionCtx` and `ZstdDecompressionCtx` to cover your use case.
