### ISSUE TITLE
Can we make the path to the DLL configurable?

### ISSUE THREAD

**Issue by skunkiferous** [luben/zstd-jni#102]
We are using zstd-jni-1.3.8-6. We have a WebStart fat client, which connects to our servers over the Internet. A handful of our clients get this error, when using ZStd to compress the data exchanged over the Internet:
`java.lang.UnsatisfiedLinkError: no zstd-jni in java.library.path
Unsupported OS/arch, cannot find /win/x86/libzstd-jni.dll or load zstd-jni from system libraries. Please try building from source the jar or providing libzstd-jni in you system.
`
(Text was typed, based on a screenshot, and might not be exactly correct)
We don't have any direct access to the computers of those clients, but those that had the error were using "Windows Terminal Server 2008 R2".

Recently we had an issue with one of our servers HDD running full. We discovered that over 4200 copies of libzstd-jni.dll were in the Windows Temp directory, consuming multiple GB of space. That is the point where we realised, that the DLL is copied into the Temp directory.

While those 1000s of copies are annyoing, they are not a deal-breaker; I just coded that the app always try to delete all of those on start. But the real issue is that we cannot fully switch to ZStd, which I would very much like because it gives us much better results than GZip, until *all* clients can use it.

I have a suspiscion, that those that have a problem, have it because of some permission/anti-virus issue related to the Windows Temp dir.

Now I'm getting to the point ... Could this library be made configurable, so that we can tell it where to store the DLL? Maybe we can then get it to work for those few clients where the DLL is not found.

Currently, all our client and servers are running on Windows, and Java 1.8.X. Most of them x64, but some clients still have 32-bit Java, I believe.

**Comment by skunkiferous** [comment]
OK, there _is_ a way to specify a path; you have to call this method with a path, **before accessing Zstd in any form**:

    static {
        Native.load("myTempDir");
    }

If it is documented anywhere, I did not see it. If it is not documented, it probably should be.

Note: I have yet to try it...

The "thousands of copies" problem seems to be typical under Windows: [tensorflow issue](https://github.com/tensorflow/tensorflow/issues/18397)

**Comment by luben** [comment]
Hi, yes, it's not yet documented (apart from https://www.javadoc.io/doc/com.github.luben/zstd-jni/1.4.0-1), and I agree it is a miss to call it out. I would accept PR for patching the README with a warning, but I don't feel I know all the details as I don't have Windows on hand.

The whole `Native.load()` thing is a huge mess as it tries to do the right thing for all platforms (unix, windows, mac, android) but I guess there are more edge-cases than I can imagine. I am glad that `Native.load(tmpDir)` unblocks you.

This method was conriuted with https://github.com/luben/zstd-jni/pull/70 and addresses https://github.com/luben/zstd-jni/issues/69 but I agree it does not explain the motivation.

**Comment by luben** [comment]
Looked at the tensorflow issue - looks it's hard problem to solve for Windows, as `deleteOnExit` does not work as expected.
