### ISSUE TITLE
Unknown frame descriptor

### ISSUE THREAD

**Issue by MichaelPriebe** [luben/zstd-jni#103]
I cannot seem to decompress this file using ZstdInputStream (as I do not know the output size to use the regular .decompress)
I get the error "Unknown frame descriptor"
[example.txt](https://github.com/luben/zstd-jni/files/3432930/example.txt)

**Comment by luben** [comment]
Yes, there is some issue. Even if I use the `Zstd.decompress(out, in)` that is very thin wrapper around `ZSTD_decompress`, I still get "Unknown file descriptor".

How did you create the compressed file?

**Comment by MichaelPriebe** [comment]
This is from a game that uses zstd to store data.
The tools at https://github.com/facebook/zstd/releases can decompress it without any problems!

**Comment by MichaelPriebe** [comment]
Oooops! My bad this file was gzipped. The game uses zstd in other places so I expected it to be used everywhere!

**Comment by luben** [comment]
Haha, I should have looked also. I assumed it's Zstd as I was able to decompress it with the zstd CLI, but nowadays it also handles other formats.
