### ISSUE TITLE
method to validate dictionary format

### ISSUE THREAD

**Issue by alexwang08** [luben/zstd-jni#104]
Is there a method to validate dictionary format? The format is defined [here](https://github.com/facebook/zstd/blob/dev/doc/zstd_compression_format.md#dictionary-format), is there a way to validate that a dictionary (passed in byte[]) is legal?

**Comment by luben** [comment]
I don't think zstd provides any functions to explicitly validate the dict format. One option is to create `ZstdDictCompress` or `ZstdDictDecompress` from the byte array and the constructors will throw an exception if the dictionary is corrupted.
