### ISSUE TITLE
Compatibility with go lang library (v1.4.1)

### ISSUE THREAD

**Issue by ssuuk** [luben/zstd-jni#106]
Hi,

I am developing a server-client message transfer function using zstd dictionary compression.

Attempting to decompress a message compressed with the go lang library using jni does not work.
However, the decompressed function in go lang works for jni compressed messages.

Is there an issue with compatibility between each library?

(go lang lib : https://github.com/DataDog/zstd, version : v1.4.1
I used the same version. zstd-jni (v1.4.1-1)

**Comment by luben** [comment]
Hi, I am not sure where the incompatibility comes from. Internally we use the facebook's code - the project is just thin wrapper over it.

If you write the golang compressed message to file, are you able to decompress it with the zstd cli?

**Comment by luben** [comment]
BTW, what is the exception you are getting? Are you using the streaming API? Are you using dictionaries?

**Comment by luben** [comment]
Any feedback here? Both libs use the same backend C code, so I don't see how they could me incompatible. Are you sure it's not problem on you application side?

**Comment by luben** [comment]
BTW, there is now zstd-1.4.4-2 that should be backwards copatible with 1.4,1, can you try it?

**Comment by luben** [comment]
@ssuuk  also there is v1.4.4-3 that may fix some input stream issues.

**Comment by luben** [comment]
closing due to no feedback
