### ISSUE TITLE
getDictIdFromDict causes unsupported OS/arch

### ISSUE THREAD

**Issue by tomtocz** [luben/zstd-jni#109]
I use zstd-jni 1.4.3-1 (maven package). When I use it on my local Windows machine it works perfect.
But when I deploy it to a linux server I have a problem while trying to invoke 
**Zstd.getDictIdFromDict(dictionary)** :
```
java.lang.UnsatisfiedLinkError: java.lang.UnsatisfiedLinkError: no zstd-jni in java.library.path
Unsupported OS/arch, cannot find /linux/amd64/libzstd-jni.so or load zstd-jni from system libraries. Please try building from source the jar or providing libzstd-jni in you system.
java.lang.UnsatisfiedLinkError: no zstd-jni in java.library.path
Unsupported OS/arch, cannot find /linux/amd64/libzstd-jni.so or load zstd-jni from system libraries. Please try building from source the jar or providing libzstd-jni in you system.
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at com.github.luben.zstd.util.Native.load(Native.java:73)
	at com.github.luben.zstd.util.Native.load(Native.java:60)
	at com.github.luben.zstd.Zstd.<clinit>(Zstd.java:11)
```
It is strange that commpression/decompresion works fine on the linux server. I only have a problem with **getDictIdFromDict** there.

I will be grateful for your hints.

**Comment by luben** [comment]
Hmm, that's very strange indeed. I will look closer as I haven't seen this before.

**Comment by luben** [comment]
BTW, does it happen with older version, e.g. 1.4.2-1 ? Also what it the version of your libc and jvm?

**Comment by tomtocz** [comment]
I have realized that my problem lies elsewhere. Sorry for bothering you.
