### ISSUE TITLE
Fail to read from ZstdInputStream by chunks

### ISSUE THREAD

**Issue by fjssilva** [luben/zstd-jni#110]
I'm using a ZstdInputStream with a bunch of bytes of compressed data, let's say 100 bytes that inflate into 160 bytes of uncompressed data, then I read these 160 bytes in two chunks of 80 bytes each but the second read throws this exception: "java.io.IOException: Read error or truncated source".

If I wrap the ZstdInputStream with a BufferedInputStream(zstdIn, 160), then it works fine, but I really want to avoid this.

As I understand it, the BufferedInputStream causes a full read of the inflated data leaving the original stream ready for what comes next, if any. A direct read from ZstdInputStream returns the requested bytes and discards the remaining, not yet read, ones.

My final goal is to wrap a Socket InputStream with a ZstdInputStream and read compressed packets from a server that is streaming data continuously.

Is there a way of doing this without using an extra BufferedInputStream or similar? Could this be a bug in ZstdInputStream?

I would say it's a bug because, to me, it would be natural to think that can consume the inflated bytes chunk by chunk as I need them and not as in the amount of the available in the stream.

**Comment by luben** [comment]
Hmm, I think I know what's happening.

When you are compressing the data, do you set closeFrameOnFlush? This will notify the consumer/decompressor that there is no more data to expect. It may affect the compression ratio as each frame (the data between flushes) will be compressed separately.

Another option is to  `setContinuous(true)` on the InputStream.

**Comment by fjssilva** [comment]
So far I'm only decompressing data so the only option I have available is  `setContinuous(true)` but it doesn't work either. With this option the `read()` operation just runs the `while (result == 0)` loop endlessly until more data is available, so, in my example above, the second block of 80 bytes is lost.

Even if this worked it wouldn't be enough for me because I really would like to instantiate the class `ZstdInputStream` through reflection and treat is just as a plain `InputStream` implementation. These implementation specific methods would have to be known beforehand. In other words I'm designing a solution that can work with multiple compression algorithms as long as the libraries provide `InputStream` and `OutputStream` implementations and they can be used from the interface methods only. Anyway, this is a requirement for my case and I can't enforce it here.

**Comment by fjssilva** [comment]
I haven't said but the compressed data I'm consuming comes in a continuous flow, hence I have to use the same `ZstdInputStream` for decompressing it continuously, the other end is not doing it in Java.

When I send compressed data to the other end (which I haven't tried yet) I want to be able to flush data in chucks, say, in some protocol packets logic, and I have to do it continuously using the same `ZstdOutputStream` too, so the option `closeFrameOnFlush=true` doesn't work for me. It's good that it is `false` by default.

**Comment by luben** [comment]
Can you provide me some minimal reproduction? I have a test that exercise something similar:
https://github.com/luben/zstd-jni/blob/master/src/test/scala/Zstd.scala#L403-L421

**Comment by luben** [comment]
> With this option the read() operation just runs the while (result == 0) loop endlessly until more data is available

It gives you an option to break and do some other job until more data is available. It could also be checked with `is.available()`. Regarding using only the interface methods, you can always wrap it into MyZstdInputStream (or anonymous class) that sets the desired parameters in the constructor

**Comment by fjssilva** [comment]
> you can always wrap it into MyZstdInputStream (or anonymous class) that sets the desired parameters in the constructor

Correct, it would require custom made wrappers though. My goal is to just add a compression library (your's, apache commons-compress, whatever) to the class path and point out the classes that implement the algorithms. Anyway, don't worry about it, this is a problem for me to figure out how to solve it if comes to it.

So far I have it working using deflate (in stream mode) and lz4 (in frame mode / each packet compressed in isolation) but the process is pretty much the same except that the `<compressor>InputStream` is reused or a new one created all the time respectively.

I'll check the test you mentioned and try to send you a short example as soon as I can.

**Comment by luben** [comment]
Hi,

I pushed a small change in the ZstdInputStream. It may fix the issue. Can you test if it solves the problem?

Thanks in advance,
luben

**Comment by luben** [comment]
@fjssilva I think it was error in the ZstdInputStream - it didn't consider that there is buffered state in the zstd context and was trying too eagerly to read from the underlying input stream. Should be fixed now. Can you confirm?

**Comment by fjssilva** [comment]
You don't have a compiled version of this patch, do you?

**Comment by luben** [comment]
@fjssilva  I have a few jars around. Which OS are you using?

**Comment by luben** [comment]
Try this one:
[zstd-jni.jar.zip](https://github.com/luben/zstd-jni/files/3861081/zstd-jni.jar.zip)

**Comment by fjssilva** [comment]
Linux 64bits, but suppose I only need the generic jar.

**Comment by luben** [comment]
Yes, the above JAR contains linux-amd64 and a few other variants built from the CI pipeline.

**Comment by fjssilva** [comment]
Great news! It seems you got it right. A quick test showed it is working as I expected. Tomorrow I'll check your patch in detail and do some more tests.

**Comment by luben** [comment]
Great, I will hold off and push a patch release with this and a few other changes after you confirm.

**Comment by luben** [comment]
@fjssilva , just pushed v1.4.4-3 to maven central. I may take some time to show in the index.

Thanks a lot for the help!

**Comment by fjssilva** [comment]
@luben, I wasn't able to reply before, sorry.

I did some more tests for my use case and all is working just fine. Thanks for fixing this so quickly.

If you are interested, here's a piece of code I used to test this:
```
public class ZstdTest {
    public static void main(String[] args) throws Exception {
        byte[] rawData = generateDataStream();

        PipedOutputStream inflaterPipe = new PipedOutputStream();
        ZstdInputStream zin = new ZstdInputStream(new PipedInputStream(inflaterPipe));

        ByteArrayInputStream dataSource = new ByteArrayInputStream(rawData);
        while (dataSource.available() > 0) {
            // Read a compressed packet
            int size = dataSource.read();
            byte[] compressedData = new byte[size];
            dataSource.read(compressedData);
            System.out.println(Arrays.toString(compressedData));

            // Inflate compressed data
            inflaterPipe.write(compressedData);

            // Read inflated messages
            int uncompressedLength = zin.read();
            while (uncompressedLength > 0) {
                int messageSize = zin.read();
                byte[] messageData = new byte[messageSize];
                uncompressedLength -= 1 + messageSize;
                zin.read(messageData);
                System.out.println(new String(messageData));
            }
        }
        zin.close();
    }

    /*
     * The data stream is composed by packets of known size of compressed data. The compressed data contains any number of fields with a known size:
     * {data-stream} :: [1 Byte {size}][{size} Bytes {compressed-data}][1 Byte {size}][{size} Bytes {compressed-data}]...
     * {compressed-data} :: [1 Byte {size-uncompressed}][1 Byte {size}][{size} Bytes {data}][1 Byte {size}][{size} Bytes {data}]...
     * {size-uncompressed} :: sum-of-all-{size}-in-same-compressed-packet
     */
    public static byte[] generateDataStream() throws Exception {
        String[] data1 = new String[] { "Data sample one", "Data sample two", "Data sample three" };
        String[] data2 = new String[] { "More data sample one", "More data sample two", "More data sample three", "THE END!" };
        String[][] data = new String[][] { data1, data2 };

        ByteArrayOutputStream finalDataStream = new ByteArrayOutputStream();
        ByteArrayOutputStream compressedDataStream = new ByteArrayOutputStream();
        ZstdOutputStream zout = new ZstdOutputStream(compressedDataStream);
        for (String[] d : data) {
            ByteArrayOutputStream partialDataStream = new ByteArrayOutputStream();
            for (String s : d) {
                partialDataStream.write(s.length());
                partialDataStream.write(s.getBytes());
            }
            byte[] partialData = partialDataStream.toByteArray();
            zout.write(partialData.length);
            zout.write(partialData);
            zout.flush();
            byte[] compressedData = compressedDataStream.toByteArray();
            finalDataStream.write(compressedData.length);
            finalDataStream.write(compressedData);
            compressedDataStream.reset();
        }
        zout.close();
        return finalDataStream.toByteArray();
    }
}
```

**Comment by luben** [comment]
Thanks, I will add some test next release also.
