### ISSUE TITLE
Version 1.4.4-5 not able to locate native library in Docker container

### ISSUE THREAD

**Issue by christian-schlichtherle** [luben/zstd-jni#114]
Hello,

I am using Zstd-JNI in my project Fun I/O on GitHub (https://github.com/christian-schlichtherle/fun-io).
For CI, I'm using Travis CI and have it configured so that the test code is run in two Docker containers, Specifically, the Docker images are openjdk:8-jdk and openjdk:13-jdk (see https://github.com/christian-schlichtherle/fun-io/blob/master/.travis.yml).

With Zstd-JNI 1.4.3-1, the test suite runs just fine. However, when I upgrade my dependency to version 1.4.4-5, I get the following exception:

```
Message: UnsatisfiedLinkError was thrown during property evaluation. (TransformedCodecSpec.scala:128)
Message: /tmp/libzstd-jni923823003686801281.so: libc.musl-x86_64.so.1: cannot open shared object file: No such file or directory
no zstd-jni in java.library.path
Unsupported OS/arch, cannot find /linux/amd64/libzstd-jni.so or load zstd-jni from system libraries. Please try building from source the jar or providing libzstd-jni in your system.
```

The first line of the error message is coming from Scalatest. The rest should be the exception message triggered by zstd-jni. I think there is an issue with how the Java code figures the architecture and where to look for the corresponding native library. I know the native libraries are embedded in the JAR file, for both the old and the new version. I did a quick check of these JAR files. They both seem OK.

When I run the test code natively on MacOS 10.14.6, everything is OK.

So what could be wrong within the Docker container?

**Comment by christian-schlichtherle** [comment]
To reproduce the issue, you may want to clone the `zstd-jni-update` branch of my project and run `./docker-sbtx 8-jdk +test`.

As for the Travis logs, you may want to check this: https://travis-ci.org/christian-schlichtherle/fun-io/builds/640508796

**Comment by luben** [comment]
Hi, I think I know what is the issue. Let me try to push a new build. I don't know how to yank the 1.4.4-5 version from Maven.

**Comment by christian-schlichtherle** [comment]
With Maven, releases are eternal. So you can only fix the issue in the next release.

**Comment by luben** [comment]
Yes, I I used different machine to build of the linux_amd64 shared object. I think this is the problem

**Comment by luben** [comment]
Just pushed v1.4.4-6 to Maven, it make take some time to show in the index.

**Comment by christian-schlichtherle** [comment]
It’s fixed - thanks a lot for the swift response!
