### ISSUE TITLE
ZstdInputStream hangs for certain chunks

### ISSUE THREAD

**Issue by benbarkay** [luben/zstd-jni#116]
Hi there,

Here's a failing test:

```java
@Test(timeout = 1000)
public void itCanStreamCompressedChunks() throws IOException {
    // The uncompressed input data for this test case
    byte[] expected = new byte[1024];

    // The decompressed output
    byte[] actual = new byte[expected.length];

    Random random = new SecureRandom();
    random.setSeed(0); // -- so that we get same random bytes each time.. If that makes sense.
    random.nextBytes(expected);

    PipedInputStream pin = new PipedInputStream();
    PipedOutputStream pout = new PipedOutputStream(pin);
    ZstdInputStream zin = new ZstdInputStream(pin);
    ZstdOutputStream zout = new ZstdOutputStream(pout);

    zin.setContinuous(true);
    zout.setCloseFrameOnFlush(false);
    zout.setLevel(3);

    zout.write(expected);
    zout.flush();

    int totalRead = 0;
    while (totalRead < actual.length) {
        totalRead +=
                zin.read(actual, totalRead, actual.length - totalRead);
    }

    assertThat(actual, equalTo(expected));
}
```

Using `compile 'com.github.luben:zstd-jni:1.4.4-7'`

**Comment by luben** [comment]
Yes, that is strange:

 - the `setContinuous(true)` configures the ZstdInputStream to not assume the stream is finished even if underlying input stream tells it's finished.

- `setCloseFrameOnFlush(false)` configures the output reader to not close the frame on flush but it looks that it also does not fully flushes the buffers.

I will investigate but it points to output stream flush issue.

**Comment by luben** [comment]
Actually it's not problem with Zstd Input/Output streams. `PipedInputStream` has internal buffer of 1024 by default. So if the connected `PipedOutputStream` tries to write more data it will block until some of the data is consumed on the other end. In your example the data is compressed to more than 1024 bytes (as it's random) so it blocks on `zout.flush()` as there is nothing reading it on the other end. You can reproduce it even without Zstd in the mix, just pick buffer bigger than 1024 bytes. 

Your example is solvable by setting bigger buffer, e.g. `new PipedInputStream(1034)`. If you want to to be able to handle all output sizes produced by Zstd, make it 128 KB

**Comment by benbarkay** [comment]
You're right, sorry about that.
I'll form a new test that represents my problem correctly (I was not using
PipedInputStream when I discovered the issue).

**Comment by benbarkay** [comment]
Also, is 128KB the absolute output limit? What should I expect for inputs
that produce more than 128KB of compressed data? (this might be the cause
of what I'm experiencing).

**Comment by luben** [comment]
Hmm, actually you are right, 128 KB is not the absolute maximum. It's the internal size of the Zstd segment.

BTW, why do you need `setContinuous(true)` - this is solving very narrow use case (tail files that are not finished) but has high chance of deadlocks as it's up to you to decide if the file is actually finished or not.

**Comment by benbarkay** [comment]
Sorry for wasting your time, looks like this works well (even with very big inputs) in my new test...
