### ISSUE TITLE
Support for armhf

### ISSUE THREAD

**Issue by ajb113** [luben/zstd-jni#117]
Can this library be extended to support armhf?

Instructions to create a Vagrant cross-compilation environment are here:
https://github.com/ajb113/zstd-jni/commit/28fc80a0bb734467cc7187bc2479b417745f435e

The cross compiler can be invoked by Cmake
`cmake . -DCMAKE_C_COMPILER=arm-linux-gnueabihf-gcc`

**Comment by luben** [comment]
Sorry for the slow feedback. I have just pushed v1.4.4-8 that also includes buid for `armhf`. I have not tested it as I just cross-compiled the native code. Can you try it and tell me if it works or not? I have some doubts about the value of `os.arch` system property, what I pushed uses `armfh` but I suspect it may be just `arm`.

**Comment by ajb113** [comment]
Hi @luben no problem, thanks for having a look at it.

I think you're correct: the os.arch system property should be "arm" rather than "armhf". It currently fails with an exception and the output of os.arch is "arm".

If it is changed to "arm" then I will be able to test the cross-compiled library.

**Comment by luben** [comment]
great, I will push a new version shortly.

**Comment by luben** [comment]
Hmm... sonatype have some issues and I cannot push the new release. Will try later.

**Comment by luben** [comment]
Just pushed it successfully, it should be available on Maven central shortly.

**Comment by luben** [comment]
@ajb113 , can you test v1.4.4-9, it's based on the last one but puts the shared object in hopefully the right place.

**Comment by ajb113** [comment]
@luben 

I tested it and it worked fine. Thanks for supporting this!

**Comment by luben** [comment]
Great, thanks for reporting and helping me release it.
