### ISSUE TITLE
JVM Crash When Internal output Stream Closed / Not Writable

### ISSUE THREAD

**Issue by dilipkasana** [luben/zstd-jni#119]
We are using zstd with Spark. As spark uses Hadoop Infrastructure at backend , If the OutputStream  we are writing in has some error from backend like Data Node Down, File Not Exists, File Not Found , Lease Expired etc, The JVM is always  crashes and some time hangs having  the following in Thread dump indefinitely.
`com.github.luben.zstd.ZstdOutputStream.compressStream(Native Method)`

OR

`java(17689,0x7000069d4000) malloc: *** error for object 0x7faf3c0ca200: pointer being freed was not allocated
java(17689,0x7000069d4000) malloc: *** set a breakpoint in malloc_error_break to debug
Abort trap: 6`

To Reproduce this bug I have made some code where I use a ByteArrayOutputStream as the Internal Output Stream and closes this OutputStream in between.This happens in big data systems  frequently that the internal stream can throw an exception at any point including flush, close , write methods.

Follow this code to produce the issue : [https://github.com/dilipkasana/zstd-crash](Test Code to reproduce)

This happening in frequently in our Hadoop Environment and Spark Environment.

**Comment by dilipkasana** [comment]
By debugging I found out that this happened due to ZstdOutputStream.close throws an exception while closing underlying stream as It executes following statement in sequence :

1. `freeCStream(stream);`
2. `out.close();`
3. `isClosed = true;`

Here statement 1 got success, and statement 2 got exception from underlying stream, Now statement 3 did not got executed.

If someone calls the close method again or It has been called from finalize then It will give a JVM dump as `    /* Opaque pointer to Zstd context object */
    private final long stream;`. is now Invaild.

**Comment by dilipkasana** [comment]
So the actual hierarchy of statement should be 

1. `freeCStream(stream);`
2. `out.close();`
3. `isClosed = true;`

**Comment by luben** [comment]
Thanks for the fix. I will wait for the CI to pass and release it as 1.4.4-10

**Comment by luben** [comment]
v1.4.4-10 is on Maven centra.
