### ISSUE TITLE
Support passing memory addresses directly

### ISSUE THREAD

**Issue by xxDark** [luben/zstd-jni#127]
Hello!
Currently we can only pass `java.nio.ByteBuffer`, however, it would be nice to be able to pass memory addresses directly.
e.g. `io.netty.buffer.ByteBuf#memoryAddress`
Thanks!

**Comment by luben** [comment]
Search for the "Unsafe" variants: `compressUnsafe` and `decompressUnsafe`

**Comment by xxDark** [comment]
Yes, saw it first time and then my mind went like 'ok let's forget about that'
Thanks!
