### ISSUE TITLE
Incomparable compression results from the library vs Zstd CLI

### ISSUE THREAD

**Issue by kartikchanana** [luben/zstd-jni#128]
I am using this library for compressing a set of files(~700) that are 2KB each in size. These files are expected to have similar content being XML files, except a few that can be 20-60KB. I use 20 files from the set as samples to train a dictionary, which I then use to compress the full set and write them concatenated to a large tar-type file(PGPArchive). I compared this compressed file size to a similarly produced tar file compressed by the Zstd CLI. The compressed mega-file produced by the library is 3-4 times larger than the one produced by the CLI. I am trying to debug why these numbers do not match with some buffer.
I have followed the [example](https://github.com/luben/zstd-jni/blob/master/src/test/scala/ZstdDict.scala), created a ZstdDictTrainer, and then used Zstd.compressUsingDict API. In a nutshell, what I am doing is:
###
ZstdDictTrainer trainer;
while(samples_fed<20) {
    trainer.addSample(nextFile.bytes());
}

byte[] dictionary = trainer.trainSamples();

for (file : list_of_files) {
    bytes[] compressedFile = Zstd.compressUsingDict(file.bytes[], dictionary, 3);
    megaFile.write(compressedFile);
}
###

I did read on this [ticket](https://github.com/luben/zstd-jni/issues/21#issuecomment-259930176) that the dictionary creation is done by the CLI, I'm not sure what that is supposed to mean. 
Also, I know compression ratio depends on many other factors, so I would like to know if there is something fundamental that I need to change to get optimal results.

**Comment by luben** [comment]
That ticket is quite old, before we had code for dictionary training. One way you can test it is to train the dictionary with the CLI and use it with the library - just load the trained dictionary in the `byte[]` array.

**Comment by kartikchanana** [comment]
Using the dictionary created by the CLI improved the compression, but still is 3 times bigger than CLI compression. Are there any benchmarks, or numbers that you can provide comparing how does the library compare to the CLI?
One thing that I should mention is that I am using the dictionary to compress one file at a time. Although, I think that is how the CLI works as well.

**Comment by luben** [comment]
They should produce the same results. It's strange. I have tests but without dictionary that assert the output is exactly the same. 

What happens if we don't use dict at all?

**Comment by kartikchanana** [comment]
The difference was that I was compressing a tar containing all the files from the CLI, while from the library I was compressing one file at a time. Programmatically creating a tar archive and compressing it produced results very close to the CLI. Thank you for your help.
