### ISSUE TITLE
Return int for compressStream or endStream in ZstdOutputStream.java?

### ISSUE THREAD

**Issue by advancedxy** [luben/zstd-jni#13]
Hi, @luben why is int returned in java side when the signature in c version's compressStream/endStream is size_t?

**Comment by luben** [comment]
The size of "size_t" is platform specific and does not have equivalent on the java side. So we have to map it either to int (32bit) or long (64bit). I am mapping them to int as they are always bounded by the buffers sizes that are less than 2G.

**Comment by advancedxy** [comment]
Then what about the error code? 
I can see an error code returned as an int will have negative value, then Zstd.isError can just get it right? (negative value converted to size_t, mapped to the corresponding error code?)

**Comment by luben** [comment]
The error codes are negative numbers way smaller than what an integer can represent. So there is no loss of information in casting from `size_t` to `int` and back. BTW, zstd has also to follow the same constraint if it want to work on platforms where size_t is 32 bit signed integer.

**Comment by advancedxy** [comment]
Thanks. I had figured that out, but want to double check with you.
