### ISSUE TITLE
Weird min compression level

### ISSUE THREAD

**Issue by melezov** [luben/zstd-jni#132]
Requesting `com.github.luben.zstd.Zstd.minCompressionLevel` returns -131072 (0xFFFE0000) which doesn't seem right.
It's returning the same constant on Windoze x64 and Centos 7 x64. Assuming it should be 1?

Also, it would be cool if the default level was exposed as a constant a'la `Zstd.defaultCompressionLevel`

Keep up the great work! 🥇

**Comment by luben** [comment]
minCompressionLevel is what the zstd native library exposes: https://github.com/luben/zstd-jni/blob/master/src/main/native/jni_zstd.c#L322-L325 - it supports negative compression levels also.

Yes, default compression level might be useful. I may add it in the future.

**Comment by melezov** [comment]
Gotcha, thanx!
