### ISSUE TITLE
Read error or truncated source while reading zstdInputStream

### ISSUE THREAD

**Issue by adityasharma1685** [luben/zstd-jni#136]
Hi,

While reading zstdInputStream sometimes I get "read error or truncated source" error. I googled this and found this issue (https://github.com/luben/zstd-jni/issues/110) related to this, here you have mentioned about setting setContinuous(true) which I did and it solved my issue. However,I wanted to understand exactly what this property actually does. Will it be possible to have any kind of side effects using this property which I should handle in my code.

Thanks

**Comment by luben** [comment]
Are you using recent version? I think I fixed an issue with it.

Regarding setContinuous, it is for handling input streams that can return EOF before the compression frame is completed, but may provide more data in the future. Example of this would be decompressing a file that is produced/compressed concurrently.In this case the FileInputStream will indicate it has reached EOF (return 0 from read) though there will come more data. In this case setContinuous will help. If the underlying stream will block, e.g. Tcp Socket, you don't need to set it

**Comment by adityasharma1685** [comment]
Hi Luben,

Thanks for the explanation. I am using this version github/luben/zstd-jni/1.4.5-5/zstd-jni-1.4.5-5.jar

Thanks

**Comment by luben** [comment]
Yes, that version should be fine. Does your workload fit the above description of reading compressed files that are still being written?

**Comment by adityasharma1685** [comment]
My application read compressed logs which can be of GZIP or ZSTD format present in AWS S3 bucket but exposed as pre-signed url. Based on the type of the log it decides on the fly which type of input stream need to be use, once the log is decompressed it is read through BufferInputStream and pass the record to process further using spark.

My application break sometime with the “read or truncated error” while returning ZSTD input stream. However, using setContinous it seems to be working fine.

**Comment by luben** [comment]
OK, yes, looks this is exactly the use case.
