### ISSUE TITLE
Support for IBM Z (s390x)

### ISSUE THREAD

**Issue by mundaym** [luben/zstd-jni#137]
Is it possible to add support for IBM Z (s390x) to the binary releases of Zstd-jni? I have compiled and tested the project natively on the platform and it appears not to require any code modifications.

For the binary release it should be ok to use cross-compilation. I think the process would be very similar to that done for armhf in #117. Alternatively (or in addition) hardware access can be provided via the [LinuxOne community cloud](https://github.com/linuxone-community-cloud/technical-resources/blob/master/faststart/deploy-virtual-server.md) or [Travis CI](https://docs.travis-ci.com/user/multi-cpu-architectures/).

I suggest using the flag `-march=z196` if possible to avoid compiling for very old versions of the machine. The major commercial Linux distributors for IBM Z (Red Hat, SuSE and Canonical) all require a z196 or newer machine for their supported distributions.

Do let me know if I can provide any assistance. I am more than happy to help with any PRs, testing etc. that is required. Thanks!

**Comment by luben** [comment]
Yes, I will do it. It will take some time as I am away of my build setup for a few weeks

**Comment by mundaym** [comment]
Thanks! Really appreciate it.

**Comment by luben** [comment]
Hi @mundaym , added it through cross-compilation. Just released 1.4.5-7. Please try it.

**Comment by mundaym** [comment]
Thanks @luben. I've tried out the library and ran into the following issue:

```
Unsupported OS/arch, cannot find /linux/s390x/libzstd-jni.so or load zstd-jni from system libraries. Please try building from source the jar or providing libzstd-jni in your system.
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2670)
        at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:830)
        at java.base/java.lang.System.loadLibrary(System.java:1873)
        at com.github.luben.zstd.util.Native.load(Native.java:78)
        at com.github.luben.zstd.util.Native.load(Native.java:54)
        at com.github.luben.zstd.ZstdOutputStream.<clinit>(ZstdOutputStream.java:16)
```

It looks like the shared object is present in the jar file but is in the folder `linux/s390` (32-bit) rather than `linux/s390x` (64-bit). I'm currently testing the shared object manually. It looks like it was correctly compiled for s390x (64-bit) so I think that the folder just needs to be renamed `linux/s390x` to fix the issue.

**Comment by luben** [comment]
I see, I didn't know about the correct name. Fixing it now.

**Comment by luben** [comment]
Just pushed v1.4.5-9 with the correct path - it should be available on maven-central shortly

**Comment by luben** [comment]
@mundaym , it's already on maven-central.

**Comment by mundaym** [comment]
Thanks @luben, it is working now!
