### ISSUE TITLE
Zstd.decompressedSize() of 0 is ambiguous

### ISSUE THREAD

**Issue by bjmi** [luben/zstd-jni#138]
According to docs of `Zstd.decompressedSize(byte[])` returns _0 if the original size is now known_.  But compressing an empty array would return a _0_ too. I.e. it is not possible to distinguish both cases beyond that compressing an empty array doesn't really make sense.
```
byte[] empty = new byte[] {};
byte[] compressed = Zstd.compress(empty);
long decompressedSize = Zstd.decompressedSize(compressed); // Returns zero
```
Wouldn't it be better to return _-1_ in case of an unknown original size or can you explain why _0_ was chosen?

**Comment by luben** [comment]
the compressed input  had size 0 so it knows it's 0. Else we will return negative number that represents the error code that could be checked with `Zstd.isError(code)` and decoded with `Zstd.getErrorName`

**Comment by bjmi** [comment]
> [...] Else we will return negative number that represents the error code that could be checked with `Zstd.isError(code)` and decoded with `Zstd.getErrorName`

Following snippet returns _0_ instead of an error code. Is this an expected behavior or was the API used in the wrong way?
```
byte[] someBytes = new byte[] { 'a', 'r', 'b', 'i', 't', 'r', 'a', 'r', 'y' };
long decompressedSize = Zstd.decompressedSize(someBytes); // Returns zero
```

**Comment by luben** [comment]
Hmm, looks like the underlying function from `libzstd` is returning 0 as the JNI wrapper just returns it without any modification:

https://github.com/luben/zstd-jni/blob/master/src/main/native/jni_zstd.c#L45-L59 

I think this should be fixed upstream but I am not sure how willing are they to change the behaviour.

**Comment by bjmi** [comment]
Thank you very much for your clarification.
