### ISSUE TITLE
Example usage for byte[] compression and decompression

### ISSUE THREAD

**Issue by gcstang** [luben/zstd-jni#14]
I've looked everywhere I could to find some form of example to use this with Java 

I understand using something like this for compression
byte[] data = ...
byte[] compressed = Zstd.compress(data)

But decompression is baffling me, how are these used in order to decompress?
long originalSize = Zstd.decompress(byte[] dest, byte[] src)
OR
byte[] dest = Zstd.decompress(byte[] src, int originalSize) 

Thank you for any help.

**Comment by luben** [comment]
Hi,

```java
byte[] dest = Zstd.decompress(byte[] src, int originalSize) 
```
should work. One problem is that you have to know the exact `originalSize`

There is `ZSTD_getDecompressedSize` for finding the original size that was added recently to Zstd, I am going to add it to the JNI bindings with the 1.0.1 version. Though keep in mind that the original size is optional field and can be missing.

**Comment by luben** [comment]
P.S. the `decompress(byte[] src, int originalSize)` is wrapper around the `decompress(src, dst)` method. If you want you can use the later one if you already have an allocated buffer.

**Comment by gcstang** [comment]
Thank you, is there a way without knowing the original size?

**Comment by luben** [comment]
I have just pushed binding for `Zstd.decompressedSize(src)` but the original size is optional (it may not be known).

Another way to do decompression is to use the ZstdInputStream filter and consume the decompressed result in chunks.

**Comment by luben** [comment]
Here is how to use the ZstdInputStream:
```java
byte[] src = ...;
InputStream is =  new ZstdInputStream(ByteArrayInputStream(src));
byte[] buff = new byte[128*1024];
int size = 0;
while (size = is.read( )



```

**Comment by mehmetonler** [comment]
Hey @luben ,
I was trying use `Zstd.decompressUsingDict` but it's expecting `dst`, `src` and `dic`' Array of bytes. Obviously, I have `src` and `dict` array but have no idea how long should be `dst` array. How can I calculate the possible length of `dst`? Or is there another way to do this? (Until 1.0.1 is released)

**Comment by luben** [comment]
Yes, the streaming dict support is not yet fleshed out. In the 1.0.1 (or if you compile the current master from source) you will have `Zstd.decompressedSize(src)`

**Comment by luben** [comment]
Closing as the `Zstd.decompressedSize(src)`  is released with 1.1.0

**Comment by LewiTech** [comment]
> I have just pushed binding for `Zstd.decompressedSize(src)` but the original size is optional (it may not be known).
> 
> Another way to do decompression is to use the ZstdInputStream filter and consume the decompressed result in chunks.

I currently use the version 1.5.6-7, but the original size does not seem to be optional. Can you give me a hint please?

**Comment by luben** [comment]
What do you mean that it's not optional? It depends on the side that does the compression - they may embed it or not.

**Comment by LewiTech** [comment]
> What do you mean that it's not optional? It depends on the side that does the compression - they may embed it or not.

I wanted to create really simple test, because i currently need to compress a String token which i compress as

Zstd.compress(objectMapper.writeValueAsBytes(serialized.data()))
and want to decompress as: 

Zstd.decompress(compressedToken.getBytes())

or something like that. But the decompress() function has an int originalSize parameter which seems not to be an optional one. If i use the one with "dst" and "src" params, i feel i also should know the size for the dst byte[] to initialize. Also the method decompressedSize() is deprecated.

Maybe i did not understand the concept... Thanks for your help in advance!

**Comment by luben** [comment]
if you create your compressed payload using `ZstdOutputStream` it will not have the `originalSize` in the header as the compressor does not know in advance when the stream is going to end. If you just use `Zstd.compress(..)` the originalSize will always be there
