### ISSUE TITLE
ZstdOutputStream and ZstdInputStream buffering

### ISSUE THREAD

**Issue by yuzawa-san** [luben/zstd-jni#141]
I use this project indirectly via Kafka. In the producer code, Kafka does a good amount of calls to ZstdOutputStream.write(int b) to write record headers and such. The currently implementation here just makes a byte[] of size 1 and does the compression on that. We have seen performance issues related to these small bytes being written. This is part of a CPU flame chart:
![image](https://user-images.githubusercontent.com/1082334/94295498-543c3880-ff2f-11ea-9bba-57bca54fb3c8.png)
My guess is that crossing into the JNI-land for a single byte over and over is not very efficient.

What is your opinion on adding an input buffer? The alternative would be to contribute to Kafka and add a BufferedOutputStream like is done for other compressors like GZIP: https://github.com/apache/kafka/blob/trunk/clients/src/main/java/org/apache/kafka/common/record/CompressionType.java#L57 The LZ4 and snappy compressors do input buffer internally within their OutputStream implementations.

If you think this is a reasonable idea, I could be willing to open a PR.

**Comment by yuzawa-san** [comment]
Also what are you thoughts on buffer recycling?

**Comment by yuzawa-san** [comment]
Here is a related ticket in Kafka's JIRA: https://issues.apache.org/jira/browse/KAFKA-10470

**Comment by luben** [comment]
Released in 1.4.5-7

**Comment by luben** [comment]
@yuzawa-san, yes. I think we could add some logic to batch the small reads/writes.

Looking at the code, we can add private methods that wrap the `compressStream` and `decompressStream` JNI calls.

 Do you want to try it?

**Comment by yuzawa-san** [comment]
sure i'll give it a shot in the coming days

**Comment by luben** [comment]
@yuzawa-san , more and more thinking about it, I am not sure we can do significantly better than wrapping the Zstd streams in Buffered(Input|Output)Stream. May be the only advantage we can get is reusing the buffers from the BufferPool but I think you can get the same advantage by creating your own BufferedStream implementation that gets the same type of BufferPool.

**Comment by yuzawa-san** [comment]
Yes, I'm currently trying to make an implementation which uses the new BufferPool. I believe this can be an improvement since the stock Buffered*Stream classes allocate a new buffer (defaultly 8192 bytes) each time. I'll have to benchmark it to see if there is an improvement, but intuitively I know the allocation rate and GC will be lower since there is that nice reuse.

**Comment by luben** [comment]
@yuzawa-san , I fear adding unconditional buffering may have negative performance implication for the use cases that don't write small chunks as it will incur and aditional memcpy.

I think the best approach is to create new buffering classes that accept buffer pools or buffer suppliers as argument and use them when needed, e.g. both for Zstd and Gzip streams.

**Comment by yuzawa-san** [comment]
ok i'm going to stop working on this for now. The folks on this ticket https://issues.apache.org/jira/browse/KAFKA-10470 are fine wrapping with Buffered*Stream, so I'll probably add it there.

**Comment by luben** [comment]
@yuzawa-san , I am releasing the 1.4.5-8 with the new code so I don't block its integration.

Thanks for helping
