### ISSUE TITLE
ZstdCompressCtx / ZstdDecompressCtx

### ISSUE THREAD

**Issue by adiantek** [luben/zstd-jni#142]
I have a question about "One such context is required for each thread - put this in a ThreadLocal." - can it be in a synchronized block without any problems on production?

**Comment by mortengrouleff** [comment]
You could do that, but that would be a potential performance bottleneck.

If you do not need the performance form having a pre-allocated context, then you're probably better off making a fresh context for each invocation, or use the methods that create the context internally instead.

**Comment by luben** [comment]
Agree with what @mortengrouleff said
