### ISSUE TITLE
 Library problem on AIX server

### ISSUE THREAD

**Issue by lootsyn** [luben/zstd-jni#144]
This is an eclipse osgi application using apache commons-compress and zstd-jni.
Error when running on ibm server.
What is the server environment that created the library?
Also, how do I compile '.so' on a server where sbt cannot be installed?

System
AIX 7.1.0
Processor Type: PowerPC_POWER8

java -version
Java(TM) SE Runtime Environment (build 8.0.5.20 - pap6480sr5fp20-20180802_01(SR5 FP20))
IBM J9 VM (build 2.9, JRE 1.8.0 AIX ppc64-64-Bit Compressed References 20180731_393394 (JIT enabled, AOT enabled)

Caused by: java.lang.UnsatisfiedLinkError: /tmp/libzstd-jni2791897149596775679.so (	0509-022 Cannot load module /tmp/libzstd-jni2791897149596775679.so.
	0509-026 System error: Cannot run a file that does not have a valid format.)
zstd-jni (Not found in java.library.path)
Unsupported OS/arch, cannot find /aix/ppc64/libzstd-jni.so or load zstd-jni from system libraries. Please try building from source the jar or providing libzstd-jni in your system.
	at java.lang.ClassLoader.loadLibraryWithPath(ClassLoader.java:1425) ~[?:2.9 (07-31-2018)]
	at java.lang.ClassLoader.loadLibraryWithClassLoader(ClassLoader.java:1395) ~[?:2.9 (07-31-2018)]
	at java.lang.System.loadLibrary(System.java:565) ~[?:2.9 (07-31-2018)]
	at com.github.luben.zstd.util.Native.load(Native.java:115) ~[bundlefile:1.4.5-7]
	at com.github.luben.zstd.util.Native.load(Native.java:54) ~[bundlefile:1.4.5-7]
	at com.github.luben.zstd.ZstdOutputStream.<clinit>(ZstdOutputStream.java:15) ~[bundlefile:1.4.5-7]
	... 12 more

**Comment by lootsyn** [comment]
and Native.java 66th line on 1.4.5-7
Shouldn't it be fixed like this?
System.loadLibrary(libname); --> System.loadLibrary(libnameShort);

**Comment by luben** [comment]
Hmm, that's strange. With versions before 1.4.5-7 was it able to load it?

Regarding building to shared library without sbt, you could adapt https://github.com/luben/zstd-jni/blob/master/make_so.sh

**Comment by luben** [comment]
@lootsyn , were you able to use v1.4.5-6 previously?

**Comment by lootsyn** [comment]
@luben 
It was still unable in v1.4.5-6.
also /tmp 's permission is 1777

I am not able to work in real time on this IBM server.
and This ibm server does not have gcc and xlc installed.
I will compile it after installing the compiler.

**Comment by lootsyn** [comment]
@luben And please review the code below.


Native.java
```java
        // try to load the shared library directly from the JAR
        try {
            Class.forName("org.osgi.framework.BundleEvent"); // Simple OSGI env. check
            System.loadLibrary(libnameShort);
            loaded = true;
            return;
        } catch (Throwable e) {
            // ignore and try other methods
        }
```


MANIFEST.MF
```
Bundle-NativeCode: ...
win/amd64/zstd-jni.dll;osname=Win32;processor=amd64,
win/x86/zstd-jni.dll;osname=Win32;processor
```

and change filename on windows
libzstd-jni.dll -> zstd-jni.dll

**Comment by luben** [comment]
I think the binary names and manifests are red herring. Looking at the messages it looks this is the root cause:
```
Caused by: java.lang.UnsatisfiedLinkError: /tmp/libzstd-jni2791897149596775679.so ( 0509-022 Cannot load module /tmp/libzstd-jni2791897149596775679.so.
```
so it finds the shared object but for some reasons it cannot link it.

I will try experimenting on my side to see if I can fix it. May be the `-brtl` will help, as you suggest.

**Comment by luben** [comment]
Hmm, I guess the problem is that it was compiled with gcc and it links some gcc libs that I guess are not commonly installed:
```
luben@gcc111:[/home/luben]ldd libzstd-jni.so
libzstd-jni.so needs:
         /opt/freeware/lib/gcc/powerpc-ibm-aix7.1.0.0/4.8.1/libgcc_s.a(shr.o)
         /usr/lib/libpthread.a(shr_xpg5.o)
         /usr/lib/libc.a(shr.o)
         /unix
         /usr/lib/libpthreads.a(shr_comm.o)
         /usr/lib/libcrypt.a(shr.o)
```
Next version will come compiled with `xlc` and should not have the dynamic linking problem:
```
luben@gcc111:[/home/luben]ldd libzstd-jni.so
libzstd-jni.so needs:
         /usr/lib/libpthread.a(shr_xpg5.o)
         /usr/lib/libc.a(shr.o)
         /unix
         /usr/lib/libpthreads.a(shr_comm.o)
         /usr/lib/libcrypt.a(shr.o)
```

**Comment by lootsyn** [comment]
@luben 
Can I get the commands of gcc and xlc for testing? also each .so file?

**Comment by luben** [comment]
@lootsyn, you can inspect https://github.com/luben/zstd-jni/blob/master/make_so.sh : the old shared object is produced by the `compile` function, the new is produced by the `compile_ppc64_aix`

**Comment by luben** [comment]
@lootsyn , I have just pushed v1.4.5-8 : can you try it and report if it solves the issue?

**Comment by lootsyn** [comment]
@luben 
Still didn't work well for the same reason.

https://www.ibm.com/support/knowledgecenter/SSGH3R_16.1.0/com.ibm.xlcpp161.aix.doc/compiler_ref/opt_3264.html
it seems that the default value is -q32.

and I have a question.
Why didn't you use xlc_r instead of xlc?

**Comment by luben** [comment]
Hmm, right, next version will come with -q64. I was expecting that to be default on the 64 bit host.

 I didn't know about xlc_r, looks equivalent to `xlc -lpthread`. Will use it.

**Comment by lootsyn** [comment]
@luben 
It worked fine. Thank you so much for your help.

and The reason I posted the above code, 
when execute to only use Bundle-NativeCode except for the code to copy lib to the tmp directory,
I couldn't run either on windows and linux.

And Exception caused a problem because UnsatisfiedLinkError could not be caught.

**Comment by luben** [comment]
I am not sure if it works as I don't use OSGI myself, but it was reported working in https://github.com/luben/zstd-jni/issues/130

**Comment by lootsyn** [comment]
@luben 

Have you ever tried running it on linux?

If there is no problem, the subject's problem has been resolved, 
so if the same problem occurs later, we will open a new subject.

**Comment by luben** [comment]
No, I don't use it in environments that uses OSGI and I have currently no interest in learning it. I am open to suggestions how to improve it but that's another topic.

**Comment by luben** [comment]
@lootsyn , I got the problem with the OSGI - it was that we need to catch `Throwable` as the `UnsatisfiedLinkError` is not subclass of `Exception`. There is v1.4.5-12 on maven-central that should fix the problem.
