### ISSUE TITLE
LGTM Java analysis failing

### ISSUE THREAD

**Issue by yuzawa-san** [luben/zstd-jni#147]
The log output from their website says "Minimum supported Gradle version is 4.10.1.", so I think it needs to be bumped.

https://lgtm.com/projects/g/luben/zstd-jni/logs/languages/lang:java

**Comment by luben** [comment]
I think it's the other way around - the gradle uses the google android plugin that requires gradle-4.10.1 though it's being run by gradle-4.1that LGTM uses.

**Comment by luben** [comment]
Hmm, strange, may be not. Let me try to push a gradle-wrapper config.

**Comment by luben** [comment]
I think I fixed it: https://lgtm.com/logs/5da3d2fd99a3d8850f8be38de8cc9bf8e93cb12d/lang:java
