### ISSUE TITLE
[REQ] Allow application to specify path to native library

### ISSUE THREAD

**Issue by djelinski** [luben/zstd-jni#150]
Some users of my application are pretty paranoid about security, and set noexec on every directory that can be written by the application; I understand that this can be worked around by copying the native library to /usr/lib or by setting LD_LIBRARY_PATH, but that forces me to test two code paths - on machines without noexec the library is loaded from temp directory, and on machines with noexec it is loaded from system path.

I'd like to be able to configure the path to native zstd library, for example using a system property. When the path is configured, there should be no fallback to system libraries or unpacking - all load failures should be final.

**Comment by luben** [comment]
@djelinski , I have just released v1.4.7-1 and you can override the native library path using the `ZstdNativePath` system property.

**Comment by djelinski** [comment]
@luben looks perfect. Exactly what I needed. Thank you!

**Comment by luben** [comment]
@djelinski , use the latest version 1.4.7-3, the previous ones have minor bugs.
