### ISSUE TITLE
Apple M1 architecture

### ISSUE THREAD

**Issue by jasonnerothin** [luben/zstd-jni#153]
Zstd builds and seems stable on Apple M1. I'd like to provide a PR. 

What would the logistics need to be? (No Actions for M1 yet on Github.)

**Comment by luben** [comment]
Thanks for confirming there are not problems on M1. The current issue is the lack of M1 support on Github actions - I use the build artifacts from the GH actions (and GCC compile farm) and include them in the final jars.

Let's hope the M1 build problems get resolved sooner: https://github.com/actions/virtual-environments/issues/2187, https://github.com/actions/runner/issues/805

Another option is to cross-compile it. I have to research a little bit about this, though the latest installed xcode (12.2) should support it.

**Comment by jasonnerothin** [comment]
Seems like cross-compile is going to be the only option for a while, even after Github fixes that one - sbt (and most things JVM) are mostly broken. Same thing for golang and therefore Docker.

**Comment by luben** [comment]
I have a build script that uses just the cc and produces the binary, I use it for cross-compiling and building on more exotic architectures. Downside is that I don't run the test suite on them.

**Comment by jasonnerothin** [comment]
Could you put it up on a new branch?

My exotic architecture is a 2015 MBP (sdkman -> JVMs, SBTs, scala-langs...) and a 2020 MBA ("[native](https://github.com/Homebrew/brew/issues/7857)" homebrew -> cmake zstd))

Could it be adapted to run the sbt tests on an sbt-container image prior to packaging up the dylibs from an as-yet-nonexistent m1 action?

**Comment by luben** [comment]
@jasonnerothin , looks I was able to cross-compile it with Xcode using github actions. One question, can you check the architecture folder in the JAR you compiled on M1? It should be `darwin/arm64` or `darwin/aarch64` or something similar. As I am cross-compiling it I don't know what will be the value for architecture in the JVM.

**Comment by jasonnerothin** [comment]
[This program](https://gist.github.com/jasonnerothin/b053ddfe617ad4c5165b9f78af3bd2da) prints this output:

OS: mac_os_x arch: aarch64

Note: I'm running Azul Systems' JVM. It is the only one that runs, last time I checked.

**Comment by luben** [comment]
Great, thanks. So next release should support M1.

**Comment by luben** [comment]
Hmm, I will wait for https://github.com/facebook/zstd/issues/2428 to be resolved as it looks dangerous.

**Comment by luben** [comment]
@jasonnerothin pushed v1.4.7-1 to maven-central,  it also contains the fix for the above bug. Can you test it?

**Comment by luben** [comment]
Better try 1.4.7-3

**Comment by dongjoon-hyun** [comment]
Thank you for 1.4.7-3, but Facebook seems to release a hot fix 1.4.8.
- https://github.com/facebook/zstd/commit/7c495e8ea2fd8ef39084c44e24c2f854aff2b68e

**Comment by luben** [comment]
@dongjoon-hyun , yes I already have the same fix. Doesn't hurt to release also 1.4.8

**Comment by dongjoon-hyun** [comment]
Nice! Thanks for confirming, @luben !

**Comment by luben** [comment]
@dongjoon-hyun , I just pushed v1.4.8-1  the only functional change is adding an assert for the buffer alignment.

**Comment by jasonnerothin** [comment]
This is what I'm seeing: Unsupported OS/arch, cannot find /darwin/aarch64/libzstd-jni.dylib or load zstd-jni from system libraries. Please try building from source the jar or providing libzstd-jni in your system.

**Comment by luben** [comment]
Hmm, let me doublecheck

**Comment by luben** [comment]
Another thing that may help is to extract the library from the jar, e.g. 'jar -xf zstd-jni.jar' and find if there is some break in the linking with `ldd libzstd-jni.dylib` (I hope it works the same on Mac).

**Comment by jasonnerothin** [comment]
**created: darwin/
  created: darwin/x86_64/
 inflated: darwin/x86_64/libzstd-jni.dylib**
...
  **created: linux/
  created: linux/aarch64/
 inflated: linux/aarch64/libzstd-jni.so**

**Comment by jasonnerothin** [comment]
```
jasonnerothin@wibble x86_64 % pwd
/tmp/darwin/x86_64
jasonnerothin@wibble x86_64 % otool -L libzstd-jni.dylib
libzstd-jni.dylib:
	/Users/runner/work/zstd-jni/zstd-jni/target/classes/darwin/x86_64/libzstd-jni.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1281.100.1)
```

**Comment by luben** [comment]
@jasonnerothin , any help with the error message? It should at least have line number, but also there may be another error messages before the `Unsupported OS/arch, cannot find /darwin/aarch64/libzstd-jni.dylib ...` line

**Comment by jasonnerothin** [comment]
^^ two comments back is partial output of ```jzr xvf zstd-jni-1.4.5-12.jar```: The ```dylib``` is going to the linux directory and the ```so``` file is ending up in the ```darwin directory```. 

^ last comment says that the ```dylib``` file is pointing to a non-existent directory.

**Comment by luben** [comment]
`zstd-jni-1.4.5-12` is not build for M1. I stated including the M1 native binary in the  1.4.7 (thought it was fast followed by 1.4.8).

I don't think the `dylib` is going the the linux directory:
```
$ jar tf zstd-jni-1.4.8-1.jar | grep dylib
darwin/aarch64/libzstd-jni.dylib
darwin/x86_64/libzstd-jni.dylib
```

I am not sure about the link to "/User/runner/..." : I don't think this is an issue as 1.4.5 was build using the old gcc toolchain and it's working. With 1.4.7 I switched the toolchain to use the xcode compiler in order to support the cross-compilation to M1.

Can you try with v1.4.8-1?

**Comment by jasonnerothin** [comment]
Okay, so it looks like the issue is that Apple has moved its "User Cache" to somewhere else.

otool is reporting that the darwin dylib is looking for ```/usr/lib/libSystem.B.dylib```. ```find / -type f ...etc``` turns nothing up in the default OS.

However, installing XCode installs one for each of tvOS, iOS, watchOS. 

I am symlinking to see if I can get the scala tests to run from IntelliJ.

**Comment by paplorinc** [comment]
Seems to be working with latest `1.4.9-1` - can this issue be closed?

**Comment by luben** [comment]
Thanks for confirming. I am not sure where the fix came from - most probably something changed on the GH workers.

@jasonnerothin , can you confirm `1.4.9-1` is working for you also?
