### ISSUE TITLE
Zstd.decompressSize Array - ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by fggarcia** [luben/zstd-jni#155]
After upgrading to 1.4.7-2 (also try with 1.4.7-1) when i try to decompress from this methods throw Exception

![image](https://user-images.githubusercontent.com/1306596/102649401-d9f30d00-4147-11eb-920c-855d0dea1dcf.png)

```
Array index out of range: 2526193 java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 2526193 >>> 	at com.github.luben.zstd.Zstd.decompressedSize(Zstd.java:583) >>> 	at com.github.luben.zstd.Zstd.decompressedSize(Zstd.java:599) >>> 	at com.github.luben.zstd.Zstd.decompressedSize(Zstd.java:610)
```

**Comment by luben** [comment]
Hmm, I added that check recently. May be I made an error there. Let me look

**Comment by luben** [comment]
I will release shortly

**Comment by luben** [comment]
@fggarcia , pushed v1.4.7-3 a few minutes ago - it fixes the issue.

**Comment by fggarcia** [comment]
Thanks @luben
