### ISSUE TITLE
Alpine link error

### ISSUE THREAD

**Issue by LarsKrogJensen** [luben/zstd-jni#157]
Using kafka clients (that is using zstd-jni 1.4.5-6) in alpine 3.11.6 causes linker error:

`Caused by: org.apache.kafka.common.KafkaException: java.lang.UnsatisfiedLinkError: /tmp/libzstd-jni5866050574215524596.so: Error loading shared library libgcc_s.so.1: No such file or directory (needed by /tmp/libzstd-jni5866050574215524596.so)
no zstd-jni in java.library.path: [/opt/jre/lib/server, /opt/jre/lib, /opt/jre/../lib, /usr/java/packages/lib, /usr/lib64, /lib64, /lib, /usr/lib]
Unsupported OS/arch, cannot find /linux/amd64/libzstd-jni.so or load zstd-jni from system libraries. Please try building from source the jar or providing libzstd-jni in your system.
`

As glibc is not available on alpine and thus fails to load.

I am using azul/zulu-openjdk-alpine:11.0.9  image that is a tck certified musl port of java.

Any plans for a musl .so provided jni-zstd?

**Comment by luben** [comment]
Hi,

It's a known issue that pops from time to time. We build on old debian 7 with libc-2.13. At some point it was loading on Alpine but looks it has changes (or was never fixed). Currently we decide on which shared object to load based on `os.name` and `os.arch` [1].  Any idea how we can tell if we are running on Alpine from inside the JVM so we load different native lib?

1. https://github.com/luben/zstd-jni/blob/master/src/main/java/com/github/luben/zstd/util/Native.java#L19-L32

**Comment by luben** [comment]
BTW, it looks it's failing due to missing libgcc. Can you add it to your image? I think it's packaged : https://pkgs.alpinelinux.org/package/edge/main/x86_64/libgcc

**Comment by LarsKrogJensen** [comment]
As awork-around I can add glibc, but the whole point of alpine is small and secure image runtime it would defeat its purpose. With https://openjdk.java.net/projects/portola/ and other initiatives this likely will be more common.

I will dig a bit to see that vars that might be used as identifying alpine.

**Comment by luben** [comment]
Can you first try adding libgcc?

**Comment by LarsKrogJensen** [comment]
Hmm that seems to be a gcc package, and not glibc.

**Comment by luben** [comment]
OK, mystery solved. One year ago I tried going the other way around - compiling on Apline and using the .so on glibc but it didn't work. Now looking into it, it looks we can statically compile the libgcc so that it will not be needed on the host.

**Comment by LarsKrogJensen** [comment]
aha, sounds promising, but statically link glibc might make the included .so files much bigger...

In the mean time I added glibc with the same approach as adoptopenjdk builds their alpine openjdk images (thats depends on glibc): https://github.com/AdoptOpenJDK/openjdk-docker/blob/master/11/jdk/alpine/Dockerfile.hotspot.releases.full#L22-L54

It does the trick, but is a hack

**Comment by luben** [comment]
Yes, I don't intend to link the glibc, just libgcc - it just adds a few KB.

What happened when you just installed libgcc without adding also the glibc?

**Comment by LarsKrogJensen** [comment]
didn't work

**Comment by LarsKrogJensen** [comment]
FWIW, compared ldd between libzstd-jni and netty epoll transport:
16:15 $ ldd libzstd-jni.so 
        linux-vdso.so.1 (0x00007ffd9dd76000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f4c9694c000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f4c9675a000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f4c9673f000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f4c96c5f000)
16:16 $ ldd libnetty_transport_native_epoll_x86_64.so 
        linux-vdso.so.1 (0x00007ffe6d0d1000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f2379ef5000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f2379eef000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f2379cfd000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f2379cda000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f237a12b000)

Also I am far outside my comfort zone on these parts :)

**Comment by luben** [comment]
Another thing you may compare between both: `strings libzstd-jni.so | grep GLIBC` and similarly for the netty lib

**Comment by LarsKrogJensen** [comment]
17:08 $ strings libnetty_transport_native_epoll_x86_64.so | grep GLIBC
GLIBC_2.2.5
GLIBC_2.8
GLIBC_2.3.4
GLIBC_2.10
GLIBC_2.7
GLIBC_2.5
GLIBC_2.3.2
GLIBC_2.9
pipe2@@GLIBC_2.9
memset@@GLIBC_2.2.5
snprintf@@GLIBC_2.2.5
shutdown@@GLIBC_2.2.5
close@@GLIBC_2.2.5
epoll_create@@GLIBC_2.3.2
recvmsg@@GLIBC_2.2.5
uname@@GLIBC_2.2.5
splice@@GLIBC_2.5
getpeername@@GLIBC_2.2.5
read@@GLIBC_2.2.5
strncmp@@GLIBC_2.2.5
malloc@@GLIBC_2.2.5
fopen@@GLIBC_2.2.5
unlink@@GLIBC_2.2.5
setsockopt@@GLIBC_2.2.5
eventfd@@GLIBC_2.7
fgets@@GLIBC_2.2.5
free@@GLIBC_2.2.5
strlen@@GLIBC_2.2.5
listen@@GLIBC_2.2.5
__cxa_finalize@@GLIBC_2.2.5
syscall@@GLIBC_2.2.5
pipe@@GLIBC_2.2.5
epoll_create1@@GLIBC_2.9
sendmsg@@GLIBC_2.2.5
in6addr_any@@GLIBC_2.2.5
strerror@@GLIBC_2.2.5
epoll_ctl@@GLIBC_2.3.2
strstr@@GLIBC_2.2.5
strcat@@GLIBC_2.2.5
getsockopt@@GLIBC_2.2.5
strtol@@GLIBC_2.2.5
getsockname@@GLIBC_2.2.5
connect@@GLIBC_2.2.5
memcpy@@GLIBC_2.2.5
eventfd_read@@GLIBC_2.7
socket@@GLIBC_2.2.5
sendfile@@GLIBC_2.2.5
__errno_location@@GLIBC_2.2.5
accept4@@GLIBC_2.10
strcpy@@GLIBC_2.2.5
epoll_wait@@GLIBC_2.3.2
dladdr@@GLIBC_2.2.5
eventfd_write@@GLIBC_2.7
calloc@@GLIBC_2.2.5
__xpg_strerror_r@@GLIBC_2.3.4
writev@@GLIBC_2.2.5
fclose@@GLIBC_2.2.5
recvfrom@@GLIBC_2.2.5
stderr@@GLIBC_2.2.5
sendto@@GLIBC_2.2.5
bind@@GLIBC_2.2.5
fwrite@@GLIBC_2.2.5
timerfd_create@@GLIBC_2.8
__strndup@@GLIBC_2.2.5
fprintf@@GLIBC_2.2.5
timerfd_settime@@GLIBC_2.8
write@@GLIBC_2.2.5
accept@@GLIBC_2.2.5
fcntl@@GLIBC_2.2.5
open@@GLIBC_2.2.5
fflush@@GLIBC_2.2.5

**Comment by luben** [comment]
Yes, then this should not been the issue for libzstd-jni.so - the highest required version is 2.2.5.

I just pushed v1.4.8-2 to maven-central. Can you try it? It compiles the libgcc_s statically that's the only difference with the netty libs.

Here is how it looks:
```
~/zstd-jni(master) » ldd target/classes/linux/amd64/libzstd-jni.so
        linux-vdso.so.1 (0x00007ffc951ce000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f5b05528000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f5b05363000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f5b05850000)
```

**Comment by LarsKrogJensen** [comment]
Will do

**Comment by LarsKrogJensen** [comment]
Amazing, it just works, soo many thanks.

Obviously, had to maven exclude the version that kafka-client depends on and include an explicit version this one.

**Comment by luben** [comment]
Perfect! Thanks for helping me solve this issue.

Regarding why it stopped working - I suspect I switched to new compiler some time ago. May be it added the libgcc dependency.

**Comment by LarsKrogJensen** [comment]
OK, final word, maybe you should notify kafka team to bump its dependency as they rely on your work

**Comment by luben** [comment]
Yes, I think they merge new versions regularly.

@yuzawa-san , @ijuma, with v.1.4.8-2 we have fixed an issue with loading the native library in Alpine (and hopefully other musl environments).

Please note, that by default the `RecyclingBufferPool` is not used - you can still pass an instance of it or another implementation of the BufferPool in the constructor - I am not sure if you rely on being used by default.

**Comment by ijuma** [comment]
Submitted PR here https://github.com/apache/kafka/pull/9957

**Comment by luben** [comment]
Thanks for the fast reaction!
