### ISSUE TITLE
Deprecated javah is invoked

### ISSUE THREAD

**Issue by advancedwebdeveloper** [luben/zstd-jni#158]
I caught such an exception:

> $ ../sbt/sbt/bin/sbt compile
> 
> [info] Loading settings for project zstd-jni-build from plugins.sbt ...
> 
> [info] Loading project definition from /home/ivan/zstd-jni/project
> [info] Loading settings for project zstd-jni from build.sbt ...
> [info] Set current project to zstd-jni (in build file:/home/ivan/zstd-jni/)
> [info] Executing in batch mode. For better performance use sbt's shell
> [info] javah -d /home/ivan/zstd-jni/target/classes/include -classpath /home/ivan/zstd-jni/target/classes com.github.luben.zstd.Zstd com.github.luben.zstd.ZstdCompressCtx com.github.luben.zstd.ZstdDecompressCtx com.github.luben.zstd.ZstdDictCompress com.github.luben.zstd.ZstdDictDecompress com.github.luben.zstd.ZstdOutputStream com.github.luben.zstd.ZstdInputStream com.github.luben.zstd.ZstdDirectBufferDecompressingStream com.github.luben.zstd.ZstdDirectBufferCompressingStream
> [error] java.io.IOException: Cannot run program "javah": error=2, No such file or directory
> [error]         at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
> [error]         at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
> [error]         at scala.sys.process.ProcessBuilderImpl$Simple.run(ProcessBuilderImpl.scala:75)
> [error]         at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.run(ProcessBuilderImpl.scala:106)
> [error]         at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.$anonfun$runBuffered$1(ProcessBuilderImpl.scala:154)
> [error]         at scala.sys.process.ProcessBuilderImpl$AbstractBuilder$$Lambda$5009/0000000000000000.apply$mcI$sp(Unknown Source)
> [error]         at scala.runtime.java8.JFunction0$mcI$sp.apply(JFunction0$mcI$sp.java:23)
> [error]         at sbt.internal.util.BufferedLogger.buffer(BufferedLogger.scala:111)
> [error]         at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.runBuffered(ProcessBuilderImpl.scala:154)
> [error]         at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.$bang(ProcessBuilderImpl.scala:120)
> [error]         at com.github.joprice.JniPlugin$.$anonfun$projectSettings$20(JniPlugin.scala:127)
> [error]         at com.github.joprice.JniPlugin$.$anonfun$projectSettings$20$adapted(JniPlugin.scala:122)
> [error]         at com.github.joprice.JniPlugin$$$Lambda$3852/0000000000000000.apply(Unknown Source)
> [error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)
> [error]         at scala.Function1$$Lambda$1893/0000000000000000.apply(Unknown Source)
> [error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
> [error]         at sbt.internal.util.$tilde$greater$$Lambda$2957/0000000000000000.apply(Unknown Source)
> [error]         at sbt.std.Transform$$anon$4.work(Transform.scala:67)
> [error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
> [error]         at sbt.Execute$$Lambda$2975/0000000000000000.apply(Unknown Source)
> [error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
> [error]         at sbt.Execute.work(Execute.scala:290)
> [error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
> [error]         at sbt.Execute$$Lambda$2966/0000000000000000.apply(Unknown Source)
> [error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
> [error]         at sbt.ConcurrentRestrictions$$anon$4$$Lambda$2973/0000000000000000.apply(Unknown Source)
> [error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
> [error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
> [error]         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
> [error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
> [error]         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
> [error]         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
> [error]         at java.base/java.lang.Thread.run(Thread.java:836)
> [error] Caused by: java.io.IOException: error=2, No such file or directory
> [error]         at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
> [error]         at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:340)
> [error]         at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:271)
> [error]         at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
> [error]         at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
> [error]         at scala.sys.process.ProcessBuilderImpl$Simple.run(ProcessBuilderImpl.scala:75)
> [error]         at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.run(ProcessBuilderImpl.scala:106)
> [error]         at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.$anonfun$runBuffered$1(ProcessBuilderImpl.scala:154)
> [error]         at scala.sys.process.ProcessBuilderImpl$AbstractBuilder$$Lambda$5009/0000000000000000.apply$mcI$sp(Unknown Source)
> [error]         at scala.runtime.java8.JFunction0$mcI$sp.apply(JFunction0$mcI$sp.java:23)
> [error]         at sbt.internal.util.BufferedLogger.buffer(BufferedLogger.scala:111)
> [error]         at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.runBuffered(ProcessBuilderImpl.scala:154)
> [error]         at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.$bang(ProcessBuilderImpl.scala:120)
> [error]         at com.github.joprice.JniPlugin$.$anonfun$projectSettings$20(JniPlugin.scala:127)
> [error]         at com.github.joprice.JniPlugin$.$anonfun$projectSettings$20$adapted(JniPlugin.scala:122)
> [error]         at com.github.joprice.JniPlugin$$$Lambda$3852/0000000000000000.apply(Unknown Source)
> [error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)
> [error]         at scala.Function1$$Lambda$1893/0000000000000000.apply(Unknown Source)
> [error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
> [error]         at sbt.internal.util.$tilde$greater$$Lambda$2957/0000000000000000.apply(Unknown Source)
> [error]         at sbt.std.Transform$$anon$4.work(Transform.scala:67)
> [error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
> [error]         at sbt.Execute$$Lambda$2975/0000000000000000.apply(Unknown Source)
> [error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
> [error]         at sbt.Execute.work(Execute.scala:290)
> [error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
> [error]         at sbt.Execute$$Lambda$2966/0000000000000000.apply(Unknown Source)
> [error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
> [error]         at sbt.ConcurrentRestrictions$$anon$4$$Lambda$2973/0000000000000000.apply(Unknown Source)
> [error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
> [error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
> [error]         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
> [error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
> [error]         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
> [error]         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
> [error]         at java.base/java.lang.Thread.run(Thread.java:836)
> [error] (jniJavah) java.io.IOException: Cannot run program "javah": error=2, No such file or directory
> [error] Total time: 43 s, completed Jan 29, 2021, 3:28:17 PM

Here is my environment:
> $ java -version && javac -version
> openjdk version "11.0.8" 2020-07-14
> OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.8+10-202007292333)
> Eclipse OpenJ9 VM AdoptOpenJDK (build master-dc7cbe4bd, JRE 11 Linux riscv-64-Bit Compressed References 20200729_78 (JIT disabled, AOT disabled)
> OpenJ9   - dc7cbe4bd
> OMR      - 1c0299f20
> JCL      - 94b9d6d2c6 based on jdk-11.0.8+10)
> javac 11.0.8

> $ uname -a
> Linux test-gdams-debian10-riscv64-1.adoptopenjdk.net 5.0.0-rc1-56210-g0a657e0d72f0 #1 SMP Fri May 15 18:05:26 EDT 2020 riscv64 GNU/Linux

> $ lscpu
> Architecture:        riscv64
> Byte Order:          Little Endian
> CPU(s):              4
> On-line CPU(s) list: 0-3
> Thread(s) per core:  1
> Core(s) per socket:  1
> Socket(s):           4
> L1i cache:           64 KiB

> $ cat /proc/cpuinfo
> processor	: 0
> hart		: 1
> isa		: rv64imafdc
> mmu		: sv39
> uarch		: sifive,rocket0

**Comment by luben** [comment]
Yes, looks the sbt-jni is still not updated: https://github.com/joprice/sbt-jni#known-issues

**Comment by advancedwebdeveloper** [comment]
What is required?

**Comment by advancedwebdeveloper** [comment]
CC @joprice @dongjinleekr @carymrobbins

**Comment by joprice** [comment]
When I was looking into how to support newer jvms, I found this project https://github.com/jodersky/sbt-jni. I think it uses asm to generate bytecode for bindings.

**Comment by luben** [comment]
Looked at my C files and it looks like I don't rely on the generated headers. So they are not needed neither at build-time nor run-time. The only use I can see is somebody wants to link to the produced native `libzstd-jni.so` but I think this is quite a niche use-case. @joprice , is there a way to disable the generation of the header files?

**Comment by luben** [comment]
Sent https://github.com/joprice/sbt-jni/pull/28 to add option not to generate header files.

**Comment by luben** [comment]
@advancedwebdeveloper , can you try the latest commits - they do not invoke `javah` anymore.

**Comment by luben** [comment]
Closing as we don't invoke `javah` anymore in the build
