### ISSUE TITLE
tag 1.3.2-2 lead to decompress less data

### ISSUE THREAD

**Issue by seayoun** [luben/zstd-jni#159]
I have a zstd data, use 1.3.2-2 decompress it will only decompress one frame, and it does's continue and exit safely
The ZSTD_decompressStream order at last is:
1. zdss_read
2. zdss_load
3. zdss_load
4. zdss_read
5. exit.

**Comment by seayoun** [comment]
I make a BufferedInputStream wrapped ZstdInputStream, when my BufferedInputStream buffer is 1024, the decompressed data size is `7236608`, when the buffer size is 8192, the decompressed data size is `1966080`, much less;

**Comment by seayoun** [comment]
BufferedInputStream and ZstdInputStream with different buffer will lead to different data

**Comment by luben** [comment]
Yes, there are some known issues in the older versions. See https://github.com/luben/zstd-jni/issues/75 and https://github.com/luben/zstd-jni/issues/110.

Please use more recent version, e.g. > =1.4.4-3. I recommend using the latest version - it is API compatible with all the previous releases.
