### ISSUE TITLE
Provide optimized implementation for direct ByteBuffers

### ISSUE THREAD

**Issue by anelson** [luben/zstd-jni#16]
The current implementation supports only Java managed `byte[]` buffers.  In my application I'm working with memory-mapped I/O buffers, in other words `ByteBuffer`s for which `isDirect()` returns `true`.  This is a special case which has an optimized JNI API for accessing the underlying `void *` very quickly, without pinning an array on the heap.

It would be very useful to be able to use this optimized I/O pattern with the `zstd` library.  I have a working implementation to submit shortly.

**Comment by luben** [comment]
Thanks for the contribution.

**Comment by anelson** [comment]
Thanks for the quick merge.  Closing as resolved.
