### ISSUE TITLE
[QUESTION] Why such big native libraries?

### ISSUE THREAD

**Issue by bolds07** [luben/zstd-jni#160]
I'm trying to use your binaries in my system, but i checked and you have an average 1MB file for the native libraries (each) that looks such a big file for a library. I would like to ask why these files got so big?

This might sound a very stupid concern but i'm planning to use this in an android app and the whole app (including assets and images) fits in 3.5MB adding 1MB more just for using one library its weird to me (mainly because my app targets low end devices)

i found some other implementations of this algorithm with binaries lesser than 100kb so why this native version got so big? is it possible to improve the size?

**Comment by luben** [comment]
You can remove the unneeded functionality for your use case, e.g. dict training, handling old versions, etc. and build a package to distribute with your app. I agree that the Android packages could be slimmed down.

**Comment by bolds07** [comment]
> You can remove the unneeded functionality for your use case, e.g. dict training, handling legacy versions, etc. and build a package to distribute with your app. I agree that the Android packages could be slimmed down, but they will not come down to 100KB: the `aar` files contain the native binaries for 4 platforms arm, aarch64, x86, amd64, so they add up.

100KB **each** platform I think is a reasonable goal.

TBH, my first thought about this large lib file was poor dependecy management, like someone was importing any dependency without really check if it is needed (unhapilly this is a very common habbit)

I didn't want to download the source and compile myself since it adds an extra complexity to my enviroment (i've never used ndk for example) also your interface and performance is very good [comparing with other java solution]

**Comment by luben** [comment]
Yes, but 100KB is not possible with the current approach when we ship all the supported features. If you have limited needs you can build a package without the needed components. Currently for generic amd64 compile:

888     ./compress
196     ./decompress
152     ./dictBuilder
88      ./common
1396    .

So if you want just the decompression part you should be able to strip it to ~ 280KB.
