### ISSUE TITLE
Missing libzstd-jni

### ISSUE THREAD

**Issue by luciangruiaro** [luben/zstd-jni#162]
I ran my project without any issues on Win x64, but when I try to deploy and run on Centos x64, I am facing this issue.

Caused by: java.lang.UnsatisfiedLinkError: no zstd-jni in java.library.path
Unsupported OS/arch, cannot find /linux/amd64/libzstd-jni.so or load zstd-jni from system libraries. Please try building from source the jar or providing libzstd-jni in you system.

I tried with multiple versions of dependency but non of them worked. 

I also found a ticket related to this and checked this version, and still the same issue.

 <dependency>
            <groupId>com.github.luben</groupId>
            <artifactId>zstd-jni</artifactId>
            <version>1.3.4-7</version>
        </dependency>

Do you have any hint on that, please?
Thanks!

**Comment by luben** [comment]
Have you tried with version 1.4.8-2 or later. It may be related with https://github.com/luben/zstd-jni/issues/157? At least you are going to get more descriptive error message what is the problem.

**Comment by luben** [comment]
Another thing to put you in the right direction: unzip the jar and see what the system linker complains:
```
unzip zstd-jni...
ldd linux/amd64/libzstd-jni.so
```

**Comment by luben** [comment]
@luciangruiaro , I am closing. If you have any feedback, please reopen it.
