### ISSUE TITLE
how to reduce jar size if only run on some platforms, any conflict with more classifiers?

### ISSUE THREAD

**Issue by bthulu** [luben/zstd-jni#164]
i only need to run on win_amd64 and linux_amd64, if i add both
`<dependency><classifier>win_amd64</classifier></dependency>`
and
`<dependency><classifier>linux_amd64</classifier></dependency>`
 to my pom.xml, is there exists some conflict?
i see that all of the classifier jars have the same java class files in it.

**Comment by luben** [comment]
Hi, I haven't tried. I would expect the duplicate class-files to not be a problem. If there is a problem it would be when loading the native library. If you try it, please come back so we know if it works or not.

**Comment by bthulu** [comment]
it seems to work well
