### ISSUE TITLE
Is it possible to provide a way to determine the size of the compressed data block when data is transmitted in segments

### ISSUE THREAD

**Issue by skyguard1** [luben/zstd-jni#165]
Hello, I am using zstd-jni to write a pr(https://github.com/netty/netty/pull/10422), and currently encounter 2 problems:
1. `Zstd.decompressedSize()` may return 0, is there any way to return the compressed block size of the data block
2. In reality, network packs data in frames. It's a frequent use-case that data arrive to the server in multiple chunks of a different length. The expected length should be taken from zstd header and decoder should wait until that data available before attempting to decompress. At present, a method is needed to determine whether the size of a complete compressed data block has been reached

**Comment by luben** [comment]
The problem is that the data may be coming in chunks also on the sender side so when the compressor sends the frame header it does not yet know the full size of the frame - this is the case of the `OutputStream` filter. 

I see two options:
- if you don't send the messages in a streaming manner but compress the whole message at once in the sender the `decompressedSize` will always be populated in the frame header. If you take this route I recommend using the `ZstCompressCtx`/`ZstdDecompressCtx` as you can reuse the context to process multiple messages.

- if you want to use the `OutputStream`/`InputStream` interfaces you can configure the `ZstdOutputStream` with `closeFrameOnFlush` so that you can use `output.flush()` to close the frame. The problem here is that on the `Input` side we don't give indication when `read` completes if the frame was closed or just the output buffer is filled. This is something we can provide.

I have not looked at your PR details. Which of the approaches are you taking? If you want to take the streaming approach I can extend the `ZstdInputStream` to give indication when frame is finished, e.g add `isFrameFinished()` method.

**Comment by skyguard1** [comment]
Thanks for the reply, this pr is using `Zstd.compress` and `Zstd.decompress` for compression and decompression operations, `ZstdInputStream` and `ZstdOutputStream` are only used for test cases, so if you can directly add methods in Zstd, tell users whether a compression The boundary of the data block is the best
In addition, is there any way to solve the problem that the return value of `Zstd.decompressedSize()` is 0, especially when using directBuffer, so that redundant memory allocation can be avoided, thank you

**Comment by luben** [comment]
@skyguard1 , I will check the `Zstd.decompressedSize` - it should not return 0 if it is in the header, i.e. the frame is produced by `Zstd.compress` methods. Agree we need to be able to return the unconsumed data back from the `decompress`.

**Comment by skyguard1** [comment]
In this pr, it is necessary to use Zstd to determine whether the data block has reached a complete zstd compressed data block, just like the `isFrameFinished()` method does, thanks for the reply

**Comment by skyguard1** [comment]
@luben, How is the progress, are there any special difficulties here?

**Comment by skyguard1** [comment]
Can you please provide a method, when `Zstd.isError` is true, return `false` instead of throwing `ZstdException`?
https://github.com/luben/zstd-jni/blob/master/src/main/java/com/github/luben/zstd/ZstdDecompressCtx.java#L120
and
https://github.com/luben/zstd-jni/blob/master/src/main/java/com/github/luben/zstd/ZstdDecompressCtx.java#L156
thanks

**Comment by luben** [comment]
This methods return `int`, so it's not possible to return `false`. May be we can return negative int with the error number there.

**Comment by skyguard1** [comment]
What I mean is that a new method can be provided to return the value of `Zstd.isError`, so that can check whether the packet is a complete zstd compressed data block, thanks for the reply

**Comment by luben** [comment]
Added in last commit

**Comment by skyguard1** [comment]
Thanks for the update. And `Zstd.decompressedSize()` on macos even if it is a complete `zstd` compressed `ByteBuffer`, the return value is still 0, thanks

**Comment by luben** [comment]
`Zstd.decompressedSize()` reads the size from the frame header. If the chunk was compressed in streaming mode, e.g. using `ZstdOutputStream` it will not have it as the streams by definition don't know the whole size. If you compress your chunks with `ZstdCompressionCtx.compress` or `Zstd.compress` (and related methods) it will have the decompressed size.

**Comment by skyguard1** [comment]
Thanks for the reply. Now I have another problem. When I compress data with `Zstd`, I can read the return value of `Zstd.decompressedSize()`, but when compressing very large data, such as an array with a length of 102400, The return value of `Zstd.decompressedSize()` is 65536, but when I use this return value to allocate `ByteBuffer`, decompression will throw `com.github.luben.zstd.ZstdException: Destination buffer is too small`, and when this value is increased in the code, `Zstd` can decompress normally, thanks

**Comment by luben** [comment]
Hmm, looks like a bug returning 65536 , that's 2^16 so may be there is truncation somewhere. I will look into it.

**Comment by luben** [comment]
Just checked locally and it works as expected even with large arrays:
```
scala> val bytes = new Array[Byte](scala.math.pow(2, 28).toInt -1)
bytes: Array[Byte] = Array(0,...
scala> val compressed2 = ctx.compress(bytes)
compressed2: Array[Byte] = Array(40, -75,...
scala> Zstd.decompressedSize(compressed2)
res13: Long = 268435455
```

**Comment by skyguard1** [comment]
Thanks for the reply, it may also be the problem of using netty's `byteBuf.` In addition, when using `ZstdOutputStream` to compress data, is there any way to determine how much memory should be allocated for decompressed data, just like `Zstd.decompressedSize()` does, thanks

**Comment by luben** [comment]
If the payload is compressed in one go (like using `Zstd.compress`) you can write a `InputStream` wrapper that inspects the first few bytes (pass them to `Zstd.decompressedSize`) to get the size. I still don't think this is the right approach - if you input is compressed in one go, it should be possible also to decompress in one go.

**Comment by skyguard1** [comment]
But in reality, network packs data in frames. So `ZstdOutputStream` compression may not be suitable for this way, thanks

**Comment by luben** [comment]
Either compress/decompress each network frame independently in one go (`Zstd.compress`/`Zstd.decompress`) or have your network framing inside the compressed stream. Pseudo-code:

Sender
```
zos = ZstdOutputStream(socketStream);

fn send(buf) {
 zos.write(buf.size)
 zos.write(buf)
 zos.flush()
}
```

Receiver side:
```
zis = ZstdInputStream(socketStream)

fn recv() {
  frame_size = zis.read_int();
  if frame_size <= 0 {
   // socket closed
  }
  buf = alloc(frame_size)
  read = 0
  while (read < frame_size) {
     num = zis.read(buf, read, buf.len() - read)
     if (num <= 0) { 
       // socket closed unexpectedly
     }
     read += num
  }
  return buf
}
```

**Comment by skyguard1** [comment]
Thanks for your suggestion, this is the same as done in the test case, thanks

**Comment by skyguard1** [comment]
I noticed that you added a method to determine zstd compressed data blocks in `ZstdDecompressCtx`, but not in `Zstd`, like `Zstd.decompress(java.nio.ByteBuffer, java.nio.ByteBuffer)` and `Zstd.decompress(byte[], byte[])`, is there any reason so that users cannot use these two methods to determine whether it is a zstd data block? thanks

**Comment by luben** [comment]
I don't understand the question. In `ZstdDecompressCtx` there are no methods to determine compressed data blocks, all methods there just decompress buffers/bytes arrays. All `ZstdDecompressCtx` methods are also exposed under `Zstd` by creating a temp context.

**Comment by skyguard1** [comment]
Sorry, but I didn’t find a place to call `decompressDirectByteBufferWithError()` and `decompressByteArrayWithError()` in `Zstd`. In addition, can you please tell me when you release it, thanks

**Comment by luben** [comment]
Aaa, I see. Any reason you prefer to use the `Zstd` - it will create more memory pressure as it allocates/deallocates the context for each operation?

**Comment by skyguard1** [comment]
For example, users usually do not specify so many parameters in `decompressDirectByteBufferWithError(ByteBuffer dstBuff, int dstOffset, int dstSize, ByteBuffer srcBuff, int srcOffset, int srcSize)`, but use `Zstd.decompress(java.nio.ByteBuffer, java.nio .ByteBuffer)` and `Zstd.decompress(byte[], byte[])`, which is more convenient for users to use `Zstd` for decompression, thanks

**Comment by skyguard1** [comment]
Considering that `ZstdDecompressCtx` is stateful, even if users use `ZstdDecompressCtx` themselves, they usually create an instance every time, so there is no difference in decompressing with `Zstd`, thanks

**Comment by luben** [comment]
`ZstdDecompressCtx` is not statfull apart from being able to load a dictionary.

**Comment by skyguard1** [comment]
Well, from my point of view, can you please provide a method in `Zstd`, so that users can choose whether to use `Zstd`, if they have higher requirements for memory allocation, thanks

**Comment by luben** [comment]
I think the `*WithError` methods are mistake and I will remove them. Errors should be exceptional and they will still be propagated as exceptions.

If you put your own framing inside the compressed stream outside the compressed packets you are always going to get complete frames. The "inside" approach I showed you above, the outside approach is something like:

```
fn send(buf) {
  compressed = cctx.compress(buf)
  sock.write(compressed.len())
  sock.write(compressed)
} 

fn recv () -> Buf {
  compressed_size = sock.read_int()
  in = sock.read(size)
  return dctx.decompress(in, Zstd.decompressedSize(in))  
}
```

**Comment by skyguard1** [comment]
Sorry, but this situation only applies to a certain special format, but as a general network framework, netty should be universal, please see https://github.com/netty/netty/pull/10422#discussion_r470308514,The implementation of the first version is similar to the example you gave, but it does not meet the general requirements of netty. Could you please keep the return size without throwing `ZstdException`? thanks

**Comment by luben** [comment]
You have to chose between 2 options:
- add framing outsize the compressed stream so you can split it in packets/chunks.
- don't add framing outside and expose Input/Output stream without packets/chunks and rely on the internal protocol to split it (framing is inside)

You are asking for Input/Output Stream to preserve message boundaries - this cannot be done without adding some form of explicit framing.

**Comment by skyguard1** [comment]
Considering the complexity of users reading the internal frame, is it possible to provide a method to read the internal frame? thanks

**Comment by luben** [comment]
No, Zstd frames are internal detail.
