### ISSUE TITLE
Project doesn't compile on clean checkout with osx / AdoptOpenJDK

### ISSUE THREAD

**Issue by lukestephenson** [luben/zstd-jni#166]
I've just tried cloning this project on osx with 
```
java --version
openjdk 11.0.6 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.6+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.6+10, mixed mode)
```

`sbt compile` fails with lots of errors like:
```
[error] /Users/lstephenson/Code/zendesk/zstd-jni/src/main/native/jni_directbufferdecompress_zstd.c:1:10: fatal error: 'jni.h' file not found
[error] #include <jni.h>
[error]          ^~~~~~~
[error] 1 error generated.
```

Which as a hack I've managed to fix with:
```
zstd-jni: cp jni/*.h src/main/native
```

On inspection of the generated `gcc` command, I can see it referencing
```
[info] gcc -shared -fPIC -O3 -I/Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home/../include -I/Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home/../include/darwin
```

Note the presence of the `..` navigation in the path makes the desired directories invalid.  The `include` directory is located at `/Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home/include` 

Project CI works though, so perhaps related to my java version.

**Comment by luben** [comment]
I think I fixed it in https://github.com/luben/zstd-jni/commit/2b60b3a86249b8bb95cf020800486610e10f4873

**Comment by lukestephenson** [comment]
Thanks.
