### ISSUE TITLE
Version 1.4.9-2 tag missing

### ISSUE THREAD

**Issue by Stephan202** [luben/zstd-jni#170]
Version 1.4.9-2 is present on [Maven Central](https://repo1.maven.org/maven2/com/github/luben/zstd-jni/1.4.9-2/), but there does not appear to be a corresponding Git tag at this time. Could this perhaps be added?

**Comment by luben** [comment]
Pushed now. Forgot to `git push --tags`

**Comment by Stephan202** [comment]
@luben it appears the `1.4.9-4` tag is also missing :)

**Comment by luben** [comment]
@Stephan202 , just pushed it - I frequently forget to `git push --tags`. Thanks for reminding me.

**Comment by hisener** [comment]
`1.5.0-2` is also missing. 🙈

**Comment by luben** [comment]
Pushed it now

**Comment by Stephan202** [comment]
@luben friendly ping for tag `v1.5.0-3` :)
