### ISSUE TITLE
1.4.9-4 aar contains 1.4.9-3 so

### ISSUE THREAD

**Issue by Artemych** [luben/zstd-jni#172]
<img width="229" alt="Screenshot 2021-04-14 at 15 41 03" src="https://user-images.githubusercontent.com/8808562/114711662-e7a45200-9d37-11eb-9f21-0598bbc85433.png">

**Comment by luben** [comment]
Hmm, yes. Looks there is some issue with the build process. I will rebuild and release new version.

**Comment by luben** [comment]
@Artemych, looks like the v1.4.9-3 `aar` was re-released as v1.4.9-4. The changes from patch 3 to 4 were only affecting how the java classes are build for the main jars and it should not affect the code in the aars. Do you have issues using the current `aar`as-is?

**Comment by Artemych** [comment]
yes as on init it tries to call loadlib 1.4.9-4 but only 1.4.9-3 and then it crashes with FileNotFoundException

**Comment by luben** [comment]
OK, I see. Looks it's not just the same jar but some mix of new java code and old jni filenames. I will re-release it.

**Comment by luben** [comment]
@Artemych , I just pushed v1.4.9-5 to maven central.

**Comment by Artemych** [comment]
Thx will check.
