### ISSUE TITLE
Desynchronize the NoPool BufferPool

### ISSUE THREAD

**Issue by Logic-32** [luben/zstd-jni#178]
Ref: ![20210608-nopool-blocking](https://user-images.githubusercontent.com/25107222/121221054-6e5e4280-c842-11eb-876a-eca1280e4041.png)

Over the course of about 2hrs we spent 10.5hrs blocked trying to allocate a buffer from the NoPool BufferPool.

We use Zstd compression for compressing data over a network from a web service that sees about 10k RPM.  So, the locking overhead from the use of the `synchronized` keyword on a method that has no apparent requirement for synchronization really adds up.

Is there something I'm missing?  Does NoPool really need to be synchronized?

**Comment by luben** [comment]
You are completely right - it does not need synchronization. It was me copying it from the recycling pool and forgetting to remove the synchronization.

**Comment by Logic-32** [comment]
No worries.  Copy/pasta happens :)  Thanks for fixing though!  Any ETA on when it can be released?

**Comment by luben** [comment]
I am building it as we speak. In 1-2 hours should be on maven-central.

**Comment by luben** [comment]
I pushed it to maven-central - it should become public soon. Tell me if it solved the problem when you have a chance to try it.

**Comment by Logic-32** [comment]
I'll need a few days to get it out to an environment where I can test it thoroughly but I'll make a note to follow up when I can.  Thanks!

**Comment by dongjoon-hyun** [comment]
Thank you, @Logic-32 and @luben . BTW, did you have a chance to run it, @Logic-32 ?

**Comment by luben** [comment]
@Logic-32 , I am also interested if this have improved the performance of your system.

Thinking one step further, if the bottleneck was on the `NoPool` synchronization, it means that the payloads you are compressing/decompressing are quite small. In that case you may find using `ZstdCompressCtx`/`ZstdDecompressCtx` better suited to your needs - you can reuse them to process multiple payloads and also save on the native memory allocation/deallocation.

**Comment by Logic-32** [comment]
Unfortunately it'll probably be a couple months before I'm able to circle back around to this.  But, I have it on my todo list!  Sorry.

**Comment by luben** [comment]
No problem. I will close the issue as resolved. Please report back when you had a chance to test it.
