### ISSUE TITLE
Upgraded version does not work on android apps that are uploaded to the Play Store

### ISSUE THREAD

**Issue by Elyahu41** [luben/zstd-jni#179]
Hello there, I just wanted to let you know that using the latest version of this repo / dependency causes android apps that are uploaded to the play store to crash.

I am actually not using this dependency directly, rather this dependency is relying on it: https://github.com/dustin-johnson/timezonemap 

There was no problem building the app or running it on the emulator.

I ran into some problems with minify, but after I disabled it, it would only crash after it was uploaded to the play store, not when I signed the APK with android studio.

Through LogCat, I was able to see this error message:

`java.lang.NoSuchFieldError: no "J" field "srcPos" in class "Lcom/github/luben/zstd/ZstdInputStreamNoFinalizer;" or its superclasses`

After downgrading from the latest version to 1.4.9-5, there were no more crashes even from the play store.

I do not know why this happens, but I wanted to let you know that this issue exists.

**Comment by luben** [comment]
Hmm, that's very strange as the `srcPos` is declared in `ZstdInputStreamNoFinalizer`: https://github.com/luben/zstd-jni/blob/master/src/main/java/com/github/luben/zstd/ZstdInputStreamNoFinalizer.java#L29 and I did not touch anything relevant on the java side between 1.4.9-5 and 1.5.0-1.

Today I will release v1.5.0-2 with some unrelated change and will try to cleanup/rebuild everything from scratch.

**Comment by Elyahu41** [comment]
I understand, it's definitely a weird issue. It probably has something to do with Google and their attempts to shrink the java classes. So I don't want to put the blame on this repo. But I don't know why the older version works flawlessly either. 

Anyways, hopefully the next update will fix this issue. It's kind of hard to test it though 😅

**Comment by luben** [comment]
v1.5.0-2 just hit maven-central. Can you try it? I am not sure if it's going to solve the problem though - I just cleaned and rebuild it with one unrelated commit.

**Comment by Elyahu41** [comment]
I'll upload a test version to the Play Store again. It might take a bit for the review process to finish.

**Comment by Elyahu41** [comment]
@luben I just upgraded my android app and uploaded it to the play store again. The issue is not there anymore! Thank you for the help!

**Comment by luben** [comment]
Thanks for reporting it.

**Comment by simonpoole** [comment]
Just a a note long after the fact, I just ran in to this issue and it was completely independent of the version of the library.  At least in my case this was caused, unsurprisingly, by minimization, excluding all the Zstd classes fixed the issue.

**Comment by luben** [comment]
@simonpoole , yes relocating the classes breaks the link between the java part and the native part - the names should match so the jvm knows which C function to call.

**Comment by Elyahu41** [comment]
It would be nice to just post a quick warning with a guide that says to exclude the Zstd classes if you are using it on Android.
