### ISSUE TITLE
Build Is Broken

### ISSUE THREAD

**Issue by Maithem** [luben/zstd-jni#180]
`sbt compile test package` fails with:

```
[warn] 
[warn]  Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn]          com.github.joprice:sbt-jni:0.2.2-SNAPSHOT (sbtVersion=1.0, scalaVersion=2.12)
[warn] 
[warn]  Note: Unresolved dependencies path:
[error] sbt.librarymanagement.ResolveException: Error downloading com.github.joprice:sbt-jni;sbtVersion=1.0;scalaVersion=2.12:0.2.2-SNAPSHOT
[error]   Not found
[error]   Not found

```

This seems like a recent change after migrating from binray as https://repo1.maven.org/maven2/com/github/joprice/sbt-jni_2.12_1.0/0.2.2-SNAPSHOT/sbt-jni-0.2.2-SNAPSHOT.pom is not reachable.

**Comment by luben** [comment]
Yes, you have first to do:
```
$ cd sbt-jni
$ ./sbt publishLocal
```
I hope this is temporary situation until `sbt-jni` is republished. Worth documenting it though

**Comment by luben** [comment]
Updated the instructions in the README

**Comment by Maithem** [comment]
@luben which version of java are you using?

I'm using java 8 and getting this error, is it a supported version for building ?

```

java.lang.IllegalArgumentException: invalid flag: --release
[error]         at com.sun.tools.javac.api.JavacTool.processOptions(JavacTool.java:206)

```

**Comment by luben** [comment]
I have switched to jvm11 for the build. I think the `--release` flag was added after 8.

**Comment by luben** [comment]
BTW, the `sbt-jni` plugin was released on maven-central and the build step is not necessary anymore.
