### ISSUE TITLE
Skiping values larger then MAX_INT may fail

### ISSUE THREAD

**Issue by johannesherr** [luben/zstd-jni#181]
When calling `ZstdInputStream.skip` with a long value larger than `Integer.MAX_VALUE` the call may fail with the following exception:

<pre>
Exception in thread "main" java.lang.IllegalArgumentException: capacity < 0: (-500704114 < 0)
        at java.base/java.nio.Buffer.createCapacityException(Buffer.java:256)
        at java.base/java.nio.ByteBuffer.allocate(ByteBuffer.java:347)
        at com.github.luben.zstd.NoPool.get(NoPool.java:16)
        at com.github.luben.zstd.ZstdInputStreamNoFinalizer.skip(ZstdInputStreamNoFinalizer.java:229)
        at com.github.luben.zstd.ZstdInputStream.skip(ZstdInputStream.java:101)
</pre>

The reason are these lines in `com.github.luben.zstd.ZstdInputStreamNoFinalizer#skip`

```
        long toSkip = numBytes;
        int bufferLen = Math.min((int) recommendedDOutSize(), (int) toSkip);
        ByteBuffer buf = bufferPool.get(bufferLen);
```

`numBytes` is the long value we want to skip. It gets passed to `toSkip` which is cast to a `int`. For values larger than the largest int this may result in a negative int, even though the argument was a positive long. If this happens `bufferLen` becomes this negative value which leads to the exception.

A possible solution would be to repeatedly skip `Integer.MAX_VALUE` until `toSkip` is smaller then `Integer.MAX_VALUE`.

**Comment by luben** [comment]
Good catch! The fix is simpler - just not overflow when computing the `bufferLen`.

**Comment by luben** [comment]
pushed v1.5.0-3 to maven-central it should be available soon

**Comment by johannesherr** [comment]
Thank you for the quick response.

**Comment by dongjoon-hyun** [comment]
Hi, @luben . Does this bug exist only at 1.5.0? Old releases like 1.4.x seems to have this too.

**Comment by luben** [comment]
I don't think it's 1.5 only. Do you depend on 1.4.x?

**Comment by dongjoon-hyun** [comment]
Thank you for the confirmation. For upcoming Apache Spark 3.2.0, we updated via https://issues.apache.org/jira/browse/SPARK-36244 , but old Spark releases do. For Parquet/Avro/Kafka community, it will be the same.

**Comment by luben** [comment]
On sonatype I cannot change released artifact so it will need a version change anyway.

Looked at the PR for Spark-3.2.0. Can you use the 1.5.0-4 , the 1.5.0-3 has some packaging issues that would affect some architectures. In 1.5.0-4 there is no code change.

**Comment by dongjoon-hyun** [comment]
Oh, thank you for informing 1.5.0-4.

For old versions, I just asked that for bug reporting for those community. For old versions, I usually expected 1.4.10, but 1.5.x is okay if there is no backward incompatibility.
> on sonatype I cannot change released artifact so it will need a version change anyway.

**Comment by luben** [comment]
Yes, there are not backward  incompatibility introduced by 1.5.0.
