### ISSUE TITLE
Indication that frame is finished on input stream

### ISSUE THREAD

**Issue by stephanie-phuong-khanh** [luben/zstd-jni#183]
Hi, I am using zstd-jni to write an encoder and decoder for internal use, similar to https://github.com/luben/zstd-jni/issues/165 but taking the streaming approach. I would like to use `ZstdOutputStream` and `ZstdInputStream`, but as you mentioned [here](https://github.com/luben/zstd-jni/issues/165#issuecomment-804760851), there is no indication when a frame is finished, if the frame was closed on the input side or if the buffer has been filled. Could you please add support on the input side to check if the frame is finished?

**Comment by luben** [comment]
The `Zstd` frames are internal detail. I think if you need to frame message it's better to introduce explicit framing - either before of after the compression.
