### ISSUE TITLE
hi! does zstd-jni support multithreading? If yes, how to turn it on?

### ISSUE THREAD

**Issue by xiaoxiaogan666** [luben/zstd-jni#184]
I now use ZstdInputStream to decompress a 16g .zst file. It takes about 260 seconds. How can I shorten the decompression time?

**Comment by luben** [comment]
Hi, multi-threading is supported on the compression side only. 260sec seams too much. Are you sure the bottleneck is not on the IO? How big is the decompressed file?

**Comment by xiaoxiaogan666** [comment]
I checked. 20.6g before decompression and 14.1g after decompression. It takes 110s to decompress using the command line. Streaming decompression and processing time takes 250s. Perhaps the bottleneck is Io

**Comment by luben** [comment]
There should be only one memory copy in the java code on top of the time it takes for the native library. I think this should not be the cause. Can you try just decompressing it (consuming the InputStream) without processing the output?

**Comment by praveennish** [comment]
Hi @luben,

Does compressByteArray method supports multi-thread compression? 

Also, how can we take advantage of multi-threaded compression. Can you please share code samples?

**Comment by luben** [comment]
if you use ZstdCompressCtx you can enable multi-threading and use its methods

**Comment by praveennish** [comment]
@luben Is there a way to use dictionary along with  ZstdCompressCtx? I could not find a method under https://javadoc.io/static/com.github.luben/zstd-jni/1.5.0-4/com/github/luben/zstd/ZstdCompressCtx.html which gives option to include dictionary!

**Comment by luben** [comment]
@praveennish , you `ctx.loadDict(...)` and then use the `compress` methods - the compression is going to use the loaded dictionary. Also you don't need to reload the dict if it's not change between compression requests.

**Comment by luben** [comment]
Hmm, on another side I see I have not added option to set the number of workers in `ZstdCompressCtx` so it can use multiple threads - I will add it.

**Comment by luben** [comment]
@praveennish , The last commit I pushed let you set number of worker threads on the `ZstdCompressCtx`. Unfortunately I am away from my build system and will release it in a few weeks.

**Comment by praveennish** [comment]
waiting...

**Comment by luben** [comment]
Aaa, yes. I will release this week

**Comment by luben** [comment]
released 1.5.0-5
