### ISSUE TITLE
native library naming.

### ISSUE THREAD

**Issue by harideva16** [luben/zstd-jni#187]
Java native interface (jni) allows calling native libraries

 1. Windows --> .dll,
 2. Linux --> .so and
 3. Mac -->.dylib.

I use the following code to load native library.

      static {
        System.loadLibrary("mypl");
        }

If I generate native library in windows os the native library's name comes `mypl.dll`

But , in Linux os the native library's name comes `libmypl.so` and in mac it comes `libmypl.dylib` 

Will this code ` System.loadLibrary("mypl");` load native library correcty after creating JPackage  in linux and mac ?

**Comment by luben** [comment]
What do you want to achieve? The native library loading is handled internally by the library
