### ISSUE TITLE
Native.Class.getResourceAsStream causes inconsistency in hadoop environment 

### ISSUE THREAD

**Issue by daniel-sudz** [luben/zstd-jni#188]
I noticed that launching an executable jar with `jar -jar <bundle.jar>` has inconsistent behaviour compared to `hadoop jar <bundle.jar>` in regards to native code linking with the zstd-jni library. 

It appears to me that `Native.Class.getResourceAsStream` resolves to the hadoop bundled zstd-jni instead of the user declared zstd-jni version when using hadoop 3+.

When setting a breakpoint: 

`InputStream is = Native.class.getResourceAsStream(resourceName);` resolves to `sun.net.www.protocol.jar.JarURLConnection:jar:file:/usr/local/Cellar/hadoop/3.3.1/libexec/share/hadoop/tools/lib/zstd-jni-1.4.3-1.jar!/darwin/x86_64/libzstd-jni.dylib` when launched in a hadoop environment. 

This is problematic if a user wants to use a newer version of zstd-jni compared to a pre-bundled version from hadoop. 

This mixup in version causes a linking error: 
```
Exception in thread "main" java.lang.UnsatisfiedLinkError: com.github.luben.zstd.ZstdCompressCtx.init()V
	at com.github.luben.zstd.ZstdCompressCtx.init(Native Method)
	at com.github.luben.zstd.ZstdCompressCtx.<init>(ZstdCompressCtx.java:28)
	at com.zstdtest.main.ZstdTest.main(ZstdTest.java:111)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.util.RunJar.run(RunJar.java:244)
	at org.apache.hadoop.util.RunJar.main(RunJar.java:158)
```

While my user declared zstd-jni version is 1.4.4-7, the native code seems to be extracted from zstd-jni version 1.4.3-1 that comes in hadoop.

**Comment by daniel-sudz** [comment]
simply deleting the hadoop zstd-jni (/usr/local/Cellar/hadoop/3.3.1/libexec/share/hadoop/tools/libzstd-jni-1.4.3-1.jar) allows resolution to occur properly to the user declared version. Of course this is not a solution as hadoop relies on this version for its own internal purposes. 

I'm going to test a couple more thing -- I have a feeling that just adding the executable jar itself to the classpath might solve this.

**Comment by daniel-sudz** [comment]
@luben would you accept a PR to shade the "Native" class with a version number such as from the sbt docs here: https://github.com/sbt/sbt-assembly#shading. 

This should allow resolution to the proper native files regardless of classpath and should have no changes to current behaviour.

**Comment by daniel-sudz** [comment]
duplicate of issue described in comment of #189

**Comment by luben** [comment]
Hmm, any idea why Hadoop is not happy with more recent version? I am trying to keep backwards compatibility but I may have missed something
