### ISSUE TITLE
Javadoc?

### ISSUE THREAD

**Issue by niwinz** [luben/zstd-jni#19]
Hi,

Would be awesome to have javadoc published somewhere and/or have some examples in readme for quick getting started with the library.

Thanks

**Comment by luben** [comment]
Yes, I agree on both points.

**Comment by sumit784** [comment]
A fully working test example in Java will be highly appreciated.

**Comment by luben** [comment]
If you look in the test folder you can pretty comprehensive examples how to use it.

**Comment by luben** [comment]
The javadocs are available at: https://www.javadoc.io/doc/com.github.luben/zstd-jni

I have also added a link/badge to the readme.
