### ISSUE TITLE
java.security.AccessControlException for loadlibrary

### ISSUE THREAD

**Issue by praveennish** [luben/zstd-jni#191]
@luben while trying to integrate zstd into apache lucene, i got following error in running a simple unit test case

java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "loadLibrary./home/praveen/Documents/lucene-development/lucene/lucene/codecs/build/tmp/tests-tmp/libzstd-jni168266960372894918

is this a known issue?

**Comment by luben** [comment]
The tmp folder has to have permissions to load native libraries from it.

**Comment by armsword** [comment]
@praveennish  Hi, praveennish, how to give  permission via policies in lucene project?
