### ISSUE TITLE
[zstd file corrupted] version zstd-jni 1.4.4-3

### ISSUE THREAD

**Issue by hk-lrzy** [luben/zstd-jni#195]
Recently, we upgraded ztsd-jni from 1.0.0 to 1.4.4-3, and then we observed that the rate of zstd file corrupted increased.
The reason for the corrupted is that the magic number of zstd appears in the middle of the block, and the previous block is not marked as last.

So I want to know if there are known similar issues in this version.
![image](https://user-images.githubusercontent.com/14176134/146748860-bc8e4a04-90c5-49a7-bd90-d95817f4c898.png)

**Comment by hk-lrzy** [comment]
> Hmm, that's new for me. Any chance you reusing the same Zstd* instances between multiple threads? Do you use Zstd or ZstdOutputStream or some of the others, e.g. the byte buffer variants?

Use one ZstdOutputStream object in one thread, different threads will not interfere with each other, and we not use any buffer right now.

**Comment by luben** [comment]
Hmm, that's strange. Any particular reason to use v1.4.4-3 ? Can you try with newer versions - they are API compatible.
