### ISSUE TITLE
Apparent Leak when using ZstdDictDecompress

### ISSUE THREAD

**Issue by tonyschwartz** [luben/zstd-jni#196]
I'm re-using ZstdDecompressCtx and calling decompressByteArray0 over and over since I have small records.  Lots of them.  Around 2000 per second.  If I never close the ZstdDecompressCtx and just keep using it, I run out of java heap space.  If I close it and open a new one every 1 million records, the app lasts longer.  If I close it and open a new one every 100K records, it lasts even longer.  If I close it and open a new one every 5K records, it seems to be holding stable so far.  And VisualVM seems to show better memory behavior.  Every time I construct a new ZstdDecompressCtx , I call loadDict.  Is this recommended?  It seems there is a leak here, but I don't know what is going on.  How expensive is it to construct a new ZstdDecompressCtx anyway?  Will the app eventually run out of heap space anyway even after only using it for 5K records?  How are others using this library when using it to decompress large numbers of small byte arrays?

**Comment by luben** [comment]
Hmm, that's interesting - I will try to reproduce. Creating ZstdDecompressCtx makes a native allocation on the non-managed heap (done by the native library), the performance hit depends on the cost of the allocation (depends on OS, specific implementation of malloc used on Linux/MacOS) and how much work you do afterwards. If you don't want reusable contexts, you can use the static methods of `Zstd` - they will automatically allocate new context for each operation.

Regarding the `loadDict` - yes you need to load it for each context. Note, there are 2 versions of `loadDict`: one takes `byte[]` - this will be expensive, the other takes `ZstdDictDecompress`  (you can construct if from `byte[]`) and it's just pointer copy, so it's cheap.

BTW, which

**Comment by tonyschwartz** [comment]
I am using Linux OS.  I was assuming I need to reuse the context since i am compressing and decompressing lots of small records.  No sense in reinitializing each time.  I am using a single ZstdDictDecompress which I load one from a byte array which has been primed ahead of time.  This byte array is hard coded in the app.Tony Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: luben karavelov ***@***.***> Date: 12/21/21  18:36  (GMT-05:00) To: luben/zstd-jni ***@***.***> Cc: Tony Schwartz ***@***.***>, Author ***@***.***> Subject: Re: [luben/zstd-jni] Apparent Leak when using ZstdDictDecompress (Issue #196) 
Hmm, that's interesting - I will try to reproduce. Creating ZstdDecompressCtx makes a native allocation on the non-managed heap (done by the native library), the performance hit depends on the cost of the allocation (depends on OS, specific implementation of malloc used on Linux/MacOS) and how much work you do afterwards. If you don't want reusable contexts, you can use the static methods of Zstd - they will automatically allocate new context for each operation.
Regarding the loadDict - yes you need to load it for each context. Note, there are 2 versions of loadDict: one takes byte[] - this will be expensive, the other takes ZstdDictDecompress  (you can construct if from byte[]) and it's just pointer copy, so it's cheap.
BTW, which

**Comment by tonyschwartz** [comment]
Please forgive me for not thoroughly testing this before submitting an issue.  I am unable to reproduce this in the simplest case.  I believe the problem is with my own code.  I'm sorry to both you with this.  I was grasping at straws a bit.  But for a minute, I was convinced the problem was in the library.

**Comment by luben** [comment]
No problem. Glad you solved the problem. Yes the intention of the DecompressCtx is to be reused and amortize the cost of construction / allocation.
