### ISSUE TITLE
Make it possible to prevent the UnsupportedOperationException at class loading time

### ISSUE THREAD

**Issue by DavyLandman** [luben/zstd-jni#20]
I like the approach of having one jar with all the binaries! Makes it much nicer to distribute.

However, we would like to switch back to gzip when zstd is not available for the current platform. This is not possible at the moment, since [the static initializer of Zstd class](https://github.com/luben/zstd-jni/blob/master/src/main/java/com/github/luben/zstd/Zstd.java#L11) calls the `Native.load` method that throws the `UnsupportedOperationException`. 

Would it be possible to have something like this:

- Put the load in a place that can be catched (for example the constructors of the Input/OutputStreams)
- Have a boolean method that returns if there is a zstd implementation available (to prevent the exception in the first place).

I have no problem adding this, but in that case I would prefer some discussion on the desired interface (to avoid having that after I implemented it).

**Comment by luben** [comment]
Yes, looks reasonable... I will look how to make it possible.

**Comment by DavyLandman** [comment]
Thanks! 

Perhaps for inspiration (in case you weren't aware) checkout the [jpountz/lz4-java](https://github.com/jpountz/lz4-java) bindings that automatically switch between native and java implementation.

**Comment by luben** [comment]
Yes, thanks. The loader is actually based on the same code from lz4-java.

**Comment by luben** [comment]
BTW, can you try something like this:

```java
InputStream is = null;
try {
  com.github.luben.zstd.util.Native.load();
  is = ZstdInputStream(....);
} catch (Throwable e) {
  is = GzipInputStream(....);
}
```
I think it should work as the static initialization is not executed if the class is never used. BTW, it's the same mechanism used by the LZ4

**Comment by DavyLandman** [comment]
You are completely right, I was confused on when exactly static blocks are executed.
I now mangled the jar to exclude the binaries for my platform and indeed it works.

```
    public static boolean zstdAvailable() {
        try {
            if (Native.isLoaded()) {
                return true;
            }
            Native.load();
            return Native.isLoaded();
        }
        catch (Throwable t) {
            return false;
        }
    }
```

this is the method I constructed, and indeed doesn't fail, as long as it is called before any construction of the zstd classes. 

Sorry for the issue, I think you could close it, or perhaps add a boolean method to the `Native` class that signals it can't be loaded?

**Comment by luben** [comment]
You can make it a little bit shorter:

```java
    public static boolean zstdAvailable() {
        try {
            Native.load();
            return Native.isLoaded();
        }
        catch (Throwable t) {
            return false;
        }
    }
```

**Comment by DavyLandman** [comment]
ah yes, due to the:

```
        if (loaded) {
            return;
        }
```
