### ISSUE TITLE
Old version 1.5.0-5 .so is included in 1.5.1-1 Maven jar for linux/amd64 architecture

### ISSUE THREAD

**Issue by dchristle** [luben/zstd-jni#202]
I noticed that the Maven jar for 1.5.1-1 seems to contain two .so files for the `amd64` architecture. When I unzip the .jar, I observe this output:
```
 creating: darwin/
   creating: darwin/aarch64/
  inflating: darwin/aarch64/libzstd-jni-1.5.1-1.dylib
   creating: darwin/x86_64/
  inflating: darwin/x86_64/libzstd-jni-1.5.1-1.dylib
   creating: freebsd/
   creating: freebsd/amd64/
  inflating: freebsd/amd64/libzstd-jni-1.5.1-1.so
   creating: freebsd/i386/
  inflating: freebsd/i386/libzstd-jni-1.5.1-1.so
   creating: linux/
   creating: linux/aarch64/
  inflating: linux/aarch64/libzstd-jni-1.5.1-1.so
   creating: linux/amd64/
  inflating: linux/amd64/libzstd-jni-1.5.0-5.so
  inflating: linux/amd64/libzstd-jni-1.5.1-1.so
   creating: linux/arm/
  inflating: linux/arm/libzstd-jni-1.5.1-1.so
   creating: linux/i386/
  inflating: linux/i386/libzstd-jni-1.5.1-1.so
   creating: linux/mips64/
  inflating: linux/mips64/libzstd-jni-1.5.1-1.so
   creating: linux/ppc64/
  inflating: linux/ppc64/libzstd-jni-1.5.1-1.so
   creating: linux/ppc64le/
  inflating: linux/ppc64le/libzstd-jni-1.5.1-1.so
   creating: linux/s390x/
  inflating: linux/s390x/libzstd-jni-1.5.1-1.so
   creating: win/
   creating: win/amd64/
  inflating: win/amd64/libzstd-jni-1.5.1-1.dll
   creating: win/x86/
  inflating: win/x86/libzstd-jni-1.5.1-1.dll
```

The file `inflating: linux/amd64/libzstd-jni-1.5.0-5.so` seems like it should not be in the jar, since the version is older, and that only `libzstd-jni-1.5.1-1.so` should be present under `amd64`. For reference, I'm getting this jar from this link: https://repo1.maven.org/maven2/com/github/luben/zstd-jni/1.5.1-1/zstd-jni-1.5.1-1.jar , which is the jar linked to from the main page for this version: https://mvnrepository.com/artifact/com.github.luben/zstd-jni/1.5.1-1

**Comment by dchristle** [comment]
As a followup, I checked the `linux/amd64` specific jar, and the old version is not present; I only see `linux/amd64/libzstd-jni-1.5.1-1.so`. So, this only seems like an issue with the jar that's supposed to include all OS/architectures.

**Comment by luben** [comment]
Hmm, looks I have not cleaned properly the artifacts before creating the release. Unfortunately there is nothing to do now - you can replace artifacts on Maven.

In a few days there will be Zstd-1.5.2 (https://github.com/facebook/zstd/pull/2995) and I will prepare new release.

**Comment by luben** [comment]
just pushed 1.5.2-1 to Maven, it does not have the duplicate native library.
