### ISSUE TITLE
Support for streaming decompression for ZStd

### ISSUE THREAD

**Issue by DinoCassowary** [luben/zstd-jni#205]
Looking through the Zstd and ZstdDecompressCtx, some critical methods are missing for one to implement streaming decompression. This is somewhat related to https://github.com/luben/zstd-jni/issues/165 and has similar motivation - integrating this library into a streaming system like Netty. Specifically, exposing parsing methods for the frame header data and blocks/block headers would allow one to write a streaming decompressor that can process the data in blocks as intended. The ask in issue 165 would not conform to the Zstd spec, and it's actually not necessary *if* one can parse the frame header and blocks/black headers.

**Comment by luben** [comment]
We can expose the frame header information but there is a problem that it's not guaranteed to have the whole frame size, e.g. when it was compressed in streaming mode. Exposing when frame finishes is doable but it will conflict with the InputStream requirements: reading 0 bytes means that the stream has finished and if we split the reads on frame boundaries it can happen that read1 reads the whole frame except the closing block and read2 reads the close block and returns 0 but there may be another frame after it, so before read2 we can not tell if the frame has finished.

Now thinking, it should be possible to add flag/method that does not comply with the InputStream interface and returns 0 on frame finish, though next read could continue with the next frame. Is this acceptable interface?

**Comment by DinoCassowary** [comment]
I'm actually not asking to do anything non-conforming to the spec :)

I'm asking if we can have finer grained methods than "decompress(ByteBuffer everything)". Specifically, Being able to pull out the frame header, block headers, and have a method that processes block data. E.g. I receive some bytes, I extract the frame header which tells me how much space to allocate for the lookback window. I read the next bytes to get the block header. That tells me how many bytes I need to decompress this block; I can wait for those to all show up. Then I can just repeat that process of reading the next block header and having enough info to know how many bytes to wait for.

I suppose I need to look through the native code to see if the native library supports that, but it seems like it must since it supports streaming compression and decompression.

**Comment by DinoCassowary** [comment]
I might actually be okay here after reading deeper into the API and backing native methods. I may need to write my own little parsing functions for FrameHeader and BlockHeader, but the API on ZStdDecompressCtx seems like it will work if I keep track of the offsets and where I am in a given stream.

**Comment by luben** [comment]
I was thinking a little bit different approach. On the sender side you can still use `ZstdOutputStream` but enable `closeFrameOnFlush` and call `flush` after each chunk. On the receiver side, we can add new `readFrame` method to `ZstdInputStream` that would read up to the end of the frame and return 0 if we hit end of the frame. You can read the chunk in smaller buffers by calling `readFrame` multiple times until it returns 0. And you can continue reading the next frame by calling `readFrame` again.

One disadvantage I can see in this approach is that the compression dictionary is reset for each frame so it will have worse compression ratio.

If we expose lower level methods that let you decompress block by block how can you tell if one block is one message/logical chunk? If the message is larger than 128KB it will be split into multiple blocks. If you receive one block of 128KB, how can you tell if this is the last block in the message (e.g. the message is exactly 128KB) or there are more to come.

**Comment by luben** [comment]
The "last block" flag is set on the last block in the frame. Do you intend to have each logical message be separate frame? If that is the case we can use the approach I proposed above - use `closeFrameOnFlush` and expose new method `readFrame`.

What would be the value exposing the block-level information?

**Comment by DinoCassowary** [comment]
I'm planning on writing the streaming decompressor for use in Netty which is going to stream bytes piece-meal to the decompressor. I do want to support clients with streaming use cases, and it also lets me keep the decompression buffer to a minimum. The methods you're talking about would be very helpful for the ask in Issue #165 , but for my case I would need the block headers :)

**Comment by DinoCassowary** [comment]
Following up here - had to re-read the spec and the docs; I think I also need a handle to the ZStd_Stream as described here: https://facebook.github.io/zstd/zstd_manual.html#Chapter9 I may fork and add that to the JNI bindings? Not sure yet how to best proceed.

**Comment by luben** [comment]
If you fork and make it work for your use case I can merge it back if we don't change the existing interfaces.

**Comment by DinoCassowary** [comment]
Annnnnd it looks like you have wrappers for that also - I was going down the wrong rabbit hole I think with the ZStdDecompressCtx. I will follow up (and hopefully close the issue?) if this already works as desired.

**Comment by luben** [comment]
Yes, the Input/Output streams are using the Compress/Decompress Ctxs. Though there may be some memory copying between the java and the native side if the blocks don't align. In my case it's taken care by the native lib - it buffers until it gets 128KB to compress, manages the look-back buffer of a few blocks, etc.

**Comment by DinoCassowary** [comment]
I've got this working using the Streaming wrapper. Sorry for the false alarm!
