### ISSUE TITLE
Collision with libzstd when using JavaFX on Ubuntu 18.04.6

### ISSUE THREAD

**Issue by duffrohde** [luben/zstd-jni#207]
The following piece of code ends up in an infinite loop on Ubuntu 18.04.6:

```
...
import javafx.scene.layout.GridPane;
...
	public static void main(String[] args) throws IOException {
		GridPane pane = new GridPane();
		ByteArrayOutputStream os = new ByteArrayOutputStream();
		try (OutputStream zos = new ZstdOutputStream(os)) {
			zos.write(new byte[256]);
		}
	}
```

If we look at the libraries loaded by the program we can see that JavaFX pulls in a version of libzstd as does zstd-jni:

```
$ grep zstd /proc/15488/maps
7fd3d34fd000-7fd3d35fe000 r-xp 00000000 08:04 3807425                    /tmp/libzstd-jni-1.5.2-114932177735405861661.so (deleted)
7fd3d35fe000-7fd3d37fd000 ---p 00101000 08:04 3807425                    /tmp/libzstd-jni-1.5.2-114932177735405861661.so (deleted)
7fd3d37fd000-7fd3d37ff000 rw-p 00100000 08:04 3807425                    /tmp/libzstd-jni-1.5.2-114932177735405861661.so (deleted)
7fd3de7d0000-7fd3de84a000 r-xp 00000000 08:04 917679                     /usr/lib/x86_64-linux-gnu/libzstd.so.1.3.3
7fd3de84a000-7fd3dea49000 ---p 0007a000 08:04 917679                     /usr/lib/x86_64-linux-gnu/libzstd.so.1.3.3
7fd3dea49000-7fd3dea4a000 r--p 00079000 08:04 917679                     /usr/lib/x86_64-linux-gnu/libzstd.so.1.3.3
7fd3dea4a000-7fd3dea4b000 rw-p 0007a000 08:04 917679                     /usr/lib/x86_64-linux-gnu/libzstd.so.1.3.3
```

I believe this causes a collision on the ZSTD symbols as these are exported both from libzstd-jni.so and libzstd.so.
If the libzstd.so library is built with the option -Wl,--version-script=libzstd-jni.so.map where the file contains:

```
LOCAL_ZSTD {
	global: Java_com_github_luben_zstd*;
	local: *;
};
```

then the ZSTD symbols are not exported outside the module, which can be confirmed by running nm -CD libzstd-jni.so.
Running the above program with our custom built libzstd-jni.so makes it succeed.

Any comments on this?

Thanks.

**Comment by luben** [comment]
Hmm, thanks for debugging the issue.  Do you mean building `libzstd-jni.so` with `-Wl,--version-script=libzstd-jni.so.map` ? Can you send a PR to modify the build?

**Comment by duffrohde** [comment]
Thanks for the quick response. One thing I am slightly uncertain about is the implication of making for example these symbols local:

```
00000000002ab0e4 B __bss_start
00000000002ab0e4 D _edata
00000000002ab188 B _end
000000000009de10 T _fini
0000000000003530 T _init
```

One easy way to include these would be a map file like this:

```
LOCAL_ZSTD {
	global: Java_com_github_luben_zstd*; _*;
	local: *;
};

```

**Comment by luben** [comment]
let' see if the CI passes - if it does we don't need them

**Comment by luben** [comment]
Hmm, the clang linker does not support version scripts. Do you have any idea how we can solve it there?

**Comment by duffrohde** [comment]
Sorry, I have limited experience with linkers and I think that these version scripts are mainly used for ELF shared objects. I also doubt that this specific issue will materialize on Mac OSX and Windows.

**Comment by luben** [comment]
I found it. Let's see if it compiles and passes the tests

**Comment by luben** [comment]
I think I made it also un-export the zstd symbols on Mac OS. I have to change a few other small things and will release new version this week

**Comment by luben** [comment]
Just pushed v1.5.2-2 to maven central.

**Comment by duffrohde** [comment]
Thanks a lot. I will do some testing over the coming days.
