### ISSUE TITLE
library does not match zstd cli tool

### ISSUE THREAD

**Issue by luxe** [luben/zstd-jni#209]
I'm not able to get matching results between [zstd-jni](https://github.com/luben/zstd-jni) and the [zstd](https://www.mankier.com/1/zstd) cli program.

### example:
```
echo -n "H" | zstd --stdout --no-check  | xxd                         
00000000: 28b5 2ffd 0058 0900 0048                 (./..X...
```

```
String data = "H";
byte[] compressed = Zstd.compress(data.getBytes());
for (int i = 0; i < compressed.length; ++i){
    System.out.print(String.format("%02x ", compressed[i])); //prints 28 b5 2f fd 20 01 09 00 00 48
}
```

### compared results:
28 b5 2f fd **00 58** 09 00 00 48
28 b5 2f fd **20 01** 09 00 00 48

Why are the 2 bytes different?  

I can't find any settings or locale related information that is causing this.  Changing the 'level' did not seem to have any effect.  Setting the `--no-dictID` option does not have any effect.

**Comment by luben** [comment]
`Zstd.compress` knows the size of the input and passes is in the zstd frame header. You can achieve the same with the zstd CLI:
```
$ echo -n H > zH
$ zstd --stdout --no-check zH | xxd
00000000: 28b5 2ffd 2001 0900 0048                 (./. ....H
```

Alternatively, if you don't want to have the uncompressed size in the frame header you can use `ZstdOutputStream` to compress the input.
