### ISSUE TITLE
Example and usage for this project

### ISSUE THREAD

**Issue by davidarchi** [luben/zstd-jni#21]
Hi luben :)
Thank you for your project.

Can you provide a example about compress a media file or any format file ?
if would be better if you can provide usage also!

Thank you

**Comment by luben** [comment]
Closing as a duplicate of #19 that has broader scope. Meanwhile you can consult the test suite for examples how to use it: https://github.com/luben/zstd-jni/blob/master/src/test/scala/Zstd.scala

**Comment by swb0802** [comment]
Could you please offer a simple test case demo of java version? I don't know how to create a dictionary at first time using Zstd.

**Comment by luben** [comment]
The creation of the dictionary is done by the zstd CLI (outsize this library) and is then used for compression and decompression by this library (e.g. Zstd.compressUsingDict)

**Comment by sumit784** [comment]
A fully working test example in Java will be highly appreciated.
