### ISSUE TITLE
Design issue: Type of Zstd.decompressedSize() doesn't match 2nd argument of ZstdDecompressCtx.decompress().

### ISSUE THREAD

**Issue by TheBlackPlague** [luben/zstd-jni#212]
The issue here is more of a design issue, one where I'm requesting that certain types (either in return or, more preferably, the argument) be changed.

`Zstd.decompressedSize()` given a compressed `byte[] data` provides a `long` type for the size.
```java
long size = Zstd.decompressedSize(data);
```
On the other hand, `ZstdDecompressCtx.decompress()` requires a `byte[] data` as well as an `int originalSize`. However we can see that the `originalSize` & the return from `Zstd.decompressedSize()` don't have the same type. 

Why is that? And can this be changed, if it should be changed?

**Comment by luben** [comment]
Original size can be bigger than 2GB (max int) but you cannot construct `byte[]` (for the return) bigger than 2GB - array sizes on JVM are limited for better or worse.
