### ISSUE TITLE
Closing streams twice crashes JVM

### ISSUE THREAD

**Issue by kbotond** [luben/zstd-jni#23]
There are currently no checks in the `close()` methods of `ZstdInputStream`/`ZstdOutputStream`. When attempting to close an already closed stream, the `freeDStream`/`freeCStream` native methods are called again, resulting in a segmentation fault and crashing the JVM.

The streams should behave like the default `DeflaterOutputStream`/`InflaterInputStream` by maintaining a closed flag and doing nothing if it has been set. It could also be used to prevent potential crashes in the `read`/`write` methods, by throwing an exception if the stream has already been closed.

**Comment by luben** [comment]
yes, you are right

**Comment by luben** [comment]
Fixed in the last commit. I will publish/release it with zstd-1.1.2 that should come soon,

**Comment by kbotond** [comment]
Great, thanks!
