### ISSUE TITLE
tag missing problem

### ISSUE THREAD

**Issue by CChengjie** [luben/zstd-jni#230]
I'm doing a research on tags .
We found that version 1.4.5-5、1.4.4-6 was released in Maven, but there was no corresponding tag in github. Can you help me with this?
1）What is the reason for tag's absence?

- a、This version code has problems, such as the loophole, compatibility and interface issues, etc.
- b、This version has functional problems, such as unreasonable function planning, basic function cannot be used
- c、Forgot to tag
- d、Don't care or is too trouble
- e、others，_

2） To solve this problem, we propose a method that can find the true commit of version to help developers quickly locate the problem code and fix the bug. Here are the possible true commits given by our method. Can you confirm whether or not the actual commits are included, and if not, which ones?
Is **v1.4.5-5** release on commit:
['2662fbdc320ce482a24c20b8fcac8b1d5b79fe33']
Is **v1.4.4-6** release on commit:
['630adcdbb8abe1bf7b88bd266794cfdd9d33796f']
♥ This question is very important to our research. Thank you for your time!

**Comment by luben** [comment]
I forgot to tag them. Looks like these are the right commits.
