### ISSUE TITLE
Please publish GPG key associated with repo

### ISSUE THREAD

**Issue by lizthegrey** [luben/zstd-jni#245]
I was unable to verify that 9AC5712CABE9635B65663AB0711C0A9A896FE336 is in fact your key -- it's only self-signed, and there's only a few references to the key hash elsewhere (e.g. a couple of places on GitHub). Can you at least confirm here on GitHub with a :+1: that the key is yours, @luben?

**Comment by luben** [comment]
Yes, that's the finger print of my key. Here it is again: 9AC5 712C ABE9 635B 6566 3AB0 711C 0A9A 896F E336
