### ISSUE TITLE
provide ByteBuffer support for dictionary compression

### ISSUE THREAD

**Issue by phraktle** [luben/zstd-jni#25]
Hi,

It would be great to have support for dictionary based compression and decompression methods that operate on (direct) ByteBuffers. This would avoid additional copying when operating on off-heap buffers.

Thanks,
  Viktor

**Comment by luben** [comment]
Makes sense. I will give it a try.

**Comment by luben** [comment]
Hi,

I have added the ByteBuffer compression/decompression with FastDicts and  byte[] dicts. Take a look at the test to get an idea what is covered:

https://github.com/luben/zstd-jni/blob/master/src/test/scala/ZstdDict.scala

Please, let me know if I have missed something.

Regards,
luben
