### ISSUE TITLE
Zstd release 1.5.5

### ISSUE THREAD

**Issue by smiklosovic** [luben/zstd-jni#254]
Hi, @luben 

we would like to release Apache Cassandra 4.0.9 but we just stumbled upon 1.5.5 release of Facebook which fixes some data corruption bugs literally few hours ago.

I want to ask: when do you plan to release 1.5.5 of this library so we can incorporate it in the project? We would love to do so!

Thanks

**Comment by luben** [comment]
The plan is to release it tomorrow or during the weekend

**Comment by luben** [comment]
Sure.

**Comment by luben** [comment]
@smiklosovic , I am releasing it now. It should be on Maven central in an hour or so.

**Comment by luben** [comment]
Done
