### ISSUE TITLE
native memory leak

### ISSUE THREAD

**Issue by phraktle** [luben/zstd-jni#26]
Hi,

Looks like there's a native memory leak in zstd-jni. The code in question is a straightforward reader in a server, where a `GZIPInputStream` was simply replaced by a `ZstdInputStream`, which clearly caused a native memory leak (but not a JVM heap leak). The same code was very stable with GZIPInputStream.

I'll spend some time to reproduce and diagnose later, but wanted to report this in the meantime.

**Comment by phraktle** [comment]
On first glance, this looks like a problem caused by an unclosed stream combined with the lack of proper finalizers in `zstd-jni`. The on-heap instances are GC'd but the native resources are leaked. While there's an application problem here (InputStream not explicitly closed), the library should implement proper finalizers for safety.

**Comment by luben** [comment]
Thanks for the finding the issue. It looks like te GZIPInputStream also doesn't have finalize method. I suspect you have the same problem there but it's less noticeable as the buffers are smaller. I will add a finializers for the Stream Reader/Writer.

**Comment by luben** [comment]
I just pushed a patch that adds finalizers to the relevant classes (https://github.com/luben/zstd-jni/commit/a9650343e38b318f94c12254642d2d7a733c6dde). You can try it, I hope it will fix the issue.

**Comment by phraktle** [comment]
`GZIPInputStream` itself allocates no native resources, but the underlying `Inflater` instance does – and it has the corresponding `finalize` method, so there's no native memory leak.

**Comment by phraktle** [comment]
The patch seems okay at a glance, however to actually ensure that resource allocation / release works as expected, you should add automated test cases for the following:

1. allocate thousands of Zstd* objects in a loop (without explicit close, just letting it get GC'd). For example, with zstd-jni 1.1.1 the following clearly leads to memory exhaustion (run the JVM with `-Xms32m -Xmx32m -XX:+UseSerialGC` to force frequent GC and demonstrate that it's a native memory leak):

```
        ByteArrayOutputStream baos = new ByteArrayOutputStream();
        try (ZstdOutputStream out = new ZstdOutputStream(baos)) {
            byte[] data = new byte[4096];
            ThreadLocalRandom.current().nextBytes(data);
            out.write(data);
        }
        
        byte[] compressed = baos.toByteArray();
        for (int i=0; i < 10_000_000; i++) {
            ZstdInputStream in = new ZstdInputStream(new ByteArrayInputStream(compressed));
            // not calling in.close() here
        }
```

(your patch should fix this)

2. call `close` repeatedly to double-close (a common mistake in native bindings that double-free crashes the VM).

(not sure, haven't tried :)

**Comment by luben** [comment]
released, no test though
