### ISSUE TITLE
Reference multiple dictionaries in decompression context

### ISSUE THREAD

**Issue by Alex1OPS** [luben/zstd-jni#261]
Is there any plan to support setting `ZSTD_d_refMultipleDDicts` and enabling the usage of multiple dictionaries in a decompression context?
It seems like a very useful feature in production, taking into account the evolution of the dictionary over time. 

Currently, we're using a workaround using `getDictIdFromFrame` and `getDictIdFromDict` to select the correct dictionary from a hashmap for a particular message, but the zstd itself seems to support such functionality through `ZSTD_DCtx_selectFrameDDict` [link](https://github.com/facebook/zstd/blob/7806d803383b75b00868a5367154a18caf535a92/lib/decompress/zstd_decompress.c#L2120).

**Comment by Alex1OPS** [comment]
I have some intermediate results that I can bring and finalise as a PR if it is useful.

**Comment by luben** [comment]
Looks like a useful functionality to have. I am open to PRs.

**Comment by Alex1OPS** [comment]
Here is a PR which enables multiple dict references #262.

**Comment by luben** [comment]
@Alex1OPS , just released v1.5.5-3 with this change included
