### ISSUE TITLE
com.github.luben.zstd.ZstdException: Destination buffer is too small

### ISSUE THREAD

**Issue by wuxianseng** [luben/zstd-jni#270]
![image](https://github.com/luben/zstd-jni/assets/29628381/52e8df77-daaa-452f-a554-1ea8263aa087)

How to fix this problem? When i compress twice.

**Comment by wuxianseng** [comment]
@luben pls help

**Comment by luben** [comment]
your ‘decompressedSize’ returns only the original size of the first message, it’s just reading it from the frame header. but ‘decompress’ tries to decompress both frames and there is not enough space
