### ISSUE TITLE
How to Decompress an Entire File Using a Byte Array

### ISSUE THREAD

**Issue by qianfeiyu** [luben/zstd-jni#276]
Now I can only read the contents of the file into a single byte array, so I can only read a limited length of content at a time, and using Zstd.decompress() directly returns ZSTD_CONTENTSIZE_UNKNOWN, so I have to use Stream to decompress. But when I read the next part of the file, I get 'the Unknown frame descriptor'. Is there any way to let me decompress normally in this case?

**Comment by luben** [comment]
No, if you don't know the size of the originals input, you have to use one of the `ZstdInputStream` variants.
