### ISSUE TITLE
Windows arm build

### ISSUE THREAD

**Issue by Bixilon** [luben/zstd-jni#277]
Hi, will there ever be an aarch64 build for windows?

**Comment by luben** [comment]
Reasonable ask. Though currently I am  using the GitHub workers to produce and test the Windows binaries as I don't have access to Windows machines. GH hosted workers provide only x86 machines so I cannot use them to produce ARM Windows builds. May be there is a way to cross-compile them, but I am not sure, it needs investigation

**Comment by luben** [comment]
closing as duplicate of #238
