### ISSUE TITLE
Support for patchs

### ISSUE THREAD

**Issue by RowlaxX** [luben/zstd-jni#289]
Hi Luben, 

according to the ZSTD wiki, it is possible to create and apply patchs :
https://github.com/facebook/zstd/wiki/Zstandard-as-a-patching-engine

Could you add this feature into the library please ?

Thanks !

**Comment by luben** [comment]
Patching is a feature of the zstd CLI, it is not provided by Zstd lib. We don't have plans to replicate that as zstd-jni is just bindings to the zstd lib
