### ISSUE TITLE
Can you provide version update logs

### ISSUE THREAD

**Issue by darrenjh** [luben/zstd-jni#293]
![image](https://github.com/luben/zstd-jni/assets/12735732/b2697727-8634-44fc-ab85-bf96b057b87d)

Do you have version update logs? I used libraries from version 1.5.5-5 and experienced some JNI layer crashes. I would like to check if there are any fixes in your library

**Comment by luben** [comment]
I am not planning to write separate change log. I will try to make my commit description more useful for that purpose
