### ISSUE TITLE
Not support linux_x86_64.

### ISSUE THREAD

**Issue by lazyjack001** [luben/zstd-jni#30]
Would you  like to support linux_x86_64? Or I want to know what cause it. Thanks.

**Comment by luben** [comment]
It's already supported architecture and in fact the best tested as I am using it for development. It's the same as linux_amd64.

**Comment by lazyjack001** [comment]
I think the architecture x86_64 is not same to amd64. Can it  adapt to suse x86_64 automatically if  zstd-jun run in suse x86_64?

**Comment by luben** [comment]
It is exactly the same, different software systems name it differently. You can ask java for: `System.getProperty("os.arch")` and I bet it will return "amd64".
