### ISSUE TITLE
Limit the maximal block size while decompress 

### ISSUE THREAD

**Issue by normanmaurer** [luben/zstd-jni#302]
Is there a way how I can limit the maximum block size that I want to "accept" in the decompression side ? Like I would like to throw an exception if the block is too big.

**Comment by luben** [comment]
There is already upper limit of 128KB for the block size, see [Is there a way how I can limit the maximum block size that I want to "accept" in the decompression side ? Like I would like to throw an exception if the block is too big.](https://github.com/facebook/zstd/issues/1358#issuecomment-427925508)

**Comment by normanmaurer** [comment]
@luben ah perfect!
