### ISSUE TITLE
No way to only decompress part of a file without decompressing whole thing

### ISSUE THREAD

**Issue by hYdos** [luben/zstd-jni#308]
![image](https://github.com/luben/zstd-jni/assets/25501603/31821509-bc7a-441b-9ca2-d47a8161e985)
This is my test  I'm using to test the Zstd compression in java. I have a file defining a bunch of hashes which point to offsets and sizes in the archive. I then am trying to skip to these locations and read only them. However, My test shows a .tar.xz file manages to beat me by over 2x because of the stream.skip call. What do you suggest?

**Comment by luben** [comment]
Yes, zstd is not splittable so you can not cheaply skip to given position - you need to decompress previous blocks to be able to decompress current block. For comparison, xz can skip to a block without decompressing previous blocks. A splittable format could be layered on top of zstd. I can imagine something like this to work:
- on compression, split the input in chunks, say by 1-10MB - this depends a lot on your data, smaller the chunk - lower the compression ratio.
- each chunk is encoded as new frame and all frames are written to the same file sequentially. Keep an auxiliary list of compressed frame offsets for each chunk.
- when you want to read an object at given offset, lookup the compressed offset for the chunk where your object is located and rewind the compressed stream to that position and start decompressing from there.

There is still ongoing discussion about the best path forward in https://github.com/facebook/zstd/issues/395
