### ISSUE TITLE
Caused by: org.osgi.framework.BundleException: Unable to resolve fi.i4ware.dark

### ISSUE THREAD

**Issue by foghorn-hash** [luben/zstd-jni#319]
Hello,

ChatGPT 4 and Copilot can't help me and duplicates similar reponsesses over and over again and nothing helps.

I use Maven Shade Plugin on my Confluence Data Center App that is just Real-Time Chat with Pusher.

I getting this error on installation of my App and it come not to enabled: Caused by: org.osgi.framework.BundleException: Unable to resolve fi.i4ware.dark [421](R 421.0): missing requirement [fi.i4ware.dark [421](R 421.0)] osgi.wiring.package; (&(osgi.wiring.package=com.github.luben.zstd)(version>=1.5.0)(!(version>=2.0.0))).

`<plugin>
                <groupId>org.apache.felix</groupId>
                <artifactId>maven-bundle-plugin</artifactId>
                <version>4.2.1</version>
                <extensions>true</extensions>
                <configuration>
                    <instructions>
                        <Bundle-SymbolicName>fi.i4ware.dark</Bundle-SymbolicName>
                        <Import-Package>
                        ....
                        com.github.luben.zstd;version="[1.5,2.0)",
                        .....
                       </Import-Package>
... so on and everything is made correctly
`

**Comment by luben** [comment]
No idea what this could be about. Are you relocating the zstd-jni artifacts? This may be the issue as the native part is loaded from pre-determined patch and cannot be relocated.

**Comment by foghorn-hash** [comment]
I got this issue fixed and I do not try to relocate this with Shade but in Atlassian Confluence Data Center 3rd-.party API jars things not works without Maven Shade Plugin and not if I but them to lib folder of Tomcat. They just need to compile in pom.xml inside the Apps jar file.

**Comment by foghorn-hash** [comment]
Reason why it not work was I wrote wrong to Maven Shade Plugin this: org.objectweb.asm.*, so I forget to put that .*.

**Comment by luben** [comment]
Great it's solved
