### ISSUE TITLE
Question about buffer size when streaming

### ISSUE THREAD

**Issue by javafanboy** [luben/zstd-jni#320]
I have a use-case where I would like to compress a stream  of variable length byte[] until the total compressed length comes **as close as possible** to a set maximum size say 1MB **BUT NOT EXCEEDING** that size.

As part of a solution I can use a custom byte array output stream that keeps track of how much have been written by the compressing output stream but I would also need an "as precise as possible" upper limit on how much additional data that can be written by the zstd compression stream when I flush / close it - if I had this I could stop feeding in more data when less than that limit remain in my destination. I would not be able to use the full max message size but if this buffer size is not that big it would be good enough.

I would assume the compressing output stream uses some internal specific buffer size that limits how much that can be produced when flushing / closing but right now I cant find any mention of this in the documentation. If there is such a fixed buffer size can it be set (in my case I may prefer a smaller buffer even if that slowed down compression a bit to be able to get closer to my ideal data size before having to stop streaming in more data)...

**Comment by luben** [comment]
The zstd algorithm is splitting the input into blocks of max 128 KB. If the data is completely un-compressible  it can result in an output of 131584 bytes. You can find that with `Zstd.compressBound(Zstd.blockSizeMax)`. In your case I guess you want to keep going until the output crosses TARGET_SIZE - 131584.

**Comment by javafanboy** [comment]
Thanks for the info - 128KB is a bit much for being ideal for my current use-case but I may be able to work-around that...
With the standard Java GZIP implementation the buffer size is selectable but with a small size the compression ration (and performance most likely) suffers significantly and as it is worse than Zstd at any size I would prefer to not having to fallback to using that....

**Comment by javafanboy** [comment]
Thanks for the info - 128KB is a bit much for being ideal for my current use-case but I may be able to work-around that...
With the standard Java GZIP implementation the buffer size is selectable but with a small size the compression ration (and performance most likely) suffers significantly and as it is worse than Zstd at any size I would prefer to not having to fallback to using that....

**Comment by luben** [comment]
@javafanboy , you can `flush` the output stream earlier to emit smaller block so you can get closer to your target size. Keep in mind that `close` will also add a few bytes at the end,
