### ISSUE TITLE
Invalid Java module

### ISSUE THREAD

**Issue by vietj** [luben/zstd-jni#322]
The jar of this library seems invalid because the jar contains a module-info and an automatic module name.

The automatic module name in the manifest should be removed.

**Comment by vietj** [comment]
@luben  thank you, let me know when there is an available release so we can upgrade it in Netty and check the box in this issue https://github.com/netty/netty/issues/14176

**Comment by vietj** [comment]
you can comment on https://github.com/netty/netty/issues/14176 when it is available

**Comment by vietj** [comment]
@luben a release could be expected soon ?

**Comment by luben** [comment]
yes, I will release it this week

**Comment by luben** [comment]
Released v1.5.6-5 with the change. Sorry for the delay. Will comment on the netty issue also.
