### ISSUE TITLE
Add flag 'magicless' to decompress() methods

### ISSUE THREAD

**Issue by jdotsoft** [luben/zstd-jni#328]
The methods decompress() are missing option 'magicless'
Alternative could be Zstd.setCompressionMagicless(), but this method is missing JavaDoc about first parameter 'long stream'...
Attempt to set this value to 0 crashed Java.

Please add the flag 'magicless' to the family of decompress() methods, and probably to compress() as well (but not required for my case.
Thanks!

**Comment by luben** [comment]
You should use it through `ZstdDecompressionCtx`.  There is example: https://github.com/luben/zstd-jni/blob/master/src/test/scala/Zstd.scala#L1183-L1204
