### ISSUE TITLE
v1.5.6-7 is released officially?

### ISSUE THREAD

**Issue by dongjoon-hyun** [luben/zstd-jni#329]
To @luben , it seems that `v1.5.6-7` tag doesn't exist. Is there any issue during the release?

As a downstream, we are wondering if we can upgrade to this untagged version or not.
- https://github.com/apache/spark/pull/48671

**Comment by dongjoon-hyun** [comment]
cc @panbingkun

**Comment by luben** [comment]
I just forgot to push the tag, did it now.

**Comment by panbingkun** [comment]
> I just forgot to push the tag, did it now.

Thanks! ❤️
