### ISSUE TITLE
Integrate on Android

### ISSUE THREAD

**Issue by AhmedX6** [luben/zstd-jni#36]
Hello

I don't find how to include zstd to my Android JNI Project.
Can you please provide a guide how to build it ?

Thank you

**Comment by luben** [comment]
Hi, I have no experience and exposure to Android development. Here is jordanhgl's project that made it work: https://github.com/jordanhgl/zstd_4_android

There is also #10 so if you succeed at making an Android packages please share or send PR

**Comment by AhmedX6** [comment]
Thank you :)

**Comment by Cl1608Ho** [comment]
as the repo linked above gives me a 404, here is my port: https://github.com/monstertoss/zstd-android

**Comment by luben** [comment]
Hi,

Thanks a lot. I see now what's the idea. I will start putting it together. I will do it in steps:

1. add cmake build for the native part
2. add the gradle build and AndroidManifest.

I have a few questions:

1. In your cmake you declare dependency on "log" library. Is it necessary?
2. How different architectures are handled? arm32/aarch64?

**Comment by Cl1608Ho** [comment]
0. I'm not sure if android manifest is even necessary.
1. I have no idea what is actually necessary. When I analyzed the apk it contained only the zstd-android and zstd libraries (the jni and the Facebook one), so no idea.

Should be stated that I just created a new project with c++ support, deleted just a little bit and let everything else android Studio put in there be.

2. Android Studio handles cross compilation using the Nda, with all supported (or just necessary, Idk) platforms. Hence, when you built it, android Studio compiles the library several times (if it hasn't already cached it) and sticks everything together so it just works.

For reference, this is what I did:
 1. my cmake file just includes the zstd cmake file and adds the cmake directory as include (so I keep zstd source and mine cleanly seperated)
 ‎2. Copied over all the jni_ c files from yours, changed the namespace :hehe: and changed the includes so they fit. 
 ‎3. Copied over the Java files, changed namespace, heavily modified the loader to reduce it to what's needed on Android and only that (dunno about computer Java, this is android specific). Info on that can be found online.

So i should also say I have no idea if one can produce completely platform agnostic code where the respective build system (IDE) just figures everything out, so maybe this should stay two seperate projects.

**Comment by luben** [comment]
I see. I already have an cmake config, now it needs only build.gradle and optionally manifest.

**Comment by luben** [comment]
Hi,

I made it build with gradle and imports cleanly in android studio. It produces the aar-s with native libraries for the all architectures, that's nice.

Can you test it if it loads and works as expected?

Regards,
luben

**Comment by Cl1608Ho** [comment]
Sure thing (it's not on maven, isn't it?)

That btw might also fix this arm32 issue as armeabi (or armeabi-v7) is the build for 32 bit arm builds.

But as it's plain c code, it will surely produce working binaries for any platform you want, if it works for

**Comment by luben** [comment]
yes, it's not on maven - I still have not figured how to publish it as it should go in .aar not in .jar file. I don't know if I can combine them in one jar - still worth a try.

Yes, I guess the shared library will work on linux/arm32 as you suggest.

**Comment by Cl1608Ho** [comment]
Hmmm I would have greatly favored distributing it in source form as it enables any user to compile the library for the system(s) they need, especially on Android, but do it as you deem fit

**Comment by luben** [comment]
The source is here to stay, it will not diverge from the non-android package as only the build is different. I don't know what is the best way to distribute it.

**Comment by Cl1608Ho** [comment]
I just tested it and it works fine :) congraz

the only change i still would like to see is moving the zstd source into something like thirdparty/zstd and include its own cmake file and include dir (take a look at my cmake file. the only thing that you need to do apart from that is fixing the #includes acoordingly). doing this would make updating zstd a lot easier (as its just a copy paste / git submodule containing the original repo) and would cause less confusion but make clear it is facebook's code, not your own (plus, you could then remove the jni_ namespace from your own code too, if you like)

**Comment by luben** [comment]
Thanks for testing it. I also added an androidTest that ensures that the library is loadable. I still have not figured out how to run it no travis-ci.

Regarding the git sub-module - I don't know. Currently we don't build everything from the upstream, e.g. the old legacy support is not API compatible with the new ones so it will not work anyway. We don't yet support multi-threading yet, etc. Keeping just the sources we need gives smaller binaries and is less confusing on the build side (don't have to selectively pick source files). Using their cmake is also not practical as we will end with 2 shared libraries instead of one, making it more complicated to load. I agree that it's not perfect but works for now.

I am going to close all the android support issues and open a new one about suggestions how to distribute it

**Comment by luben** [comment]
If you have suggestions about the distribution model, please give and advice in #54
