### ISSUE TITLE
SIGILL in HUF_compress4X_repeat

### ISSUE THREAD

**Issue by uwemaurer** [luben/zstd-jni#37]
We noticed crashes like this:
```
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGILL (0x4) at pc=0x00007f562ea0575f, pid=32000, tid=0x00007f5646e99700
#
# JRE version: Java(TM) SE Runtime Environment (8.0_131-b11) (build 1.8.0_131-b11)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.131-b11 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libzstd6655353904108682045.so+0x3175f]  HUF_compress4X_repeat+0x68f
#
```
It was only on machines with `AMD Opteron(tm) Processor 4170`.  To fix it the compiler flag can be changed in `build.sbt` from `-msse4` to `-msse3`. 

```
-  case "amd64"|"x86_64"   => Seq("-msse4")
-  case "i386"             => Seq("-msse4")
+  case "amd64"|"x86_64"   => Seq("-msse3")
+  case "i386"             => Seq("-msse3")
```

**Comment by luben** [comment]
Good catch. I will fix it.

Thanks for reporting and debugging it.

**Comment by luben** [comment]
Fixed it in the last commit as you suggest. Do you need the fixed the maven artifacts or you are using internal version?

**Comment by uwemaurer** [comment]
Thank you. I use an own internal version for now. When there is a new release I will switch back to the maven artifacts.

**Comment by luben** [comment]
Great. Thanks again for reporting it
