### ISSUE TITLE
Error running on alpine docker image

### ISSUE THREAD

**Issue by gyscos** [luben/zstd-jni#38]
When trying to use zstd-jni in a docker container build from `openjdk:alpine`, I get this error:

```
Caused by: java.lang.UnsatisfiedLinkError: /tmp/libzstd3471839276809832200.so: Error relocating /tmp/libzstd3471839276809832200.so: __fprintf_chk: symbol not found
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
        at java.lang.Runtime.load0(Runtime.java:809)
        at java.lang.System.load(System.java:1086)
        at com.github.luben.zstd.util.Native.load(Native.java:78)
        at com.github.luben.zstd.ZstdInputStream.<clinit>(ZstdInputStream.java:22)
```

Problem seems to be that the `libzstd.so` bundled in the jar links to `glibc`. Adding one built with `musl` would allow it to work in a musl environment.

**Comment by gyscos** [comment]
To build such a lib:

```
$ docker run -v $(pwd):/out -it alpine sh
# apk update
# apk add build-base git
# git clone https://github.com/facebook/zstd
# cd zstd && make
# cp lib/libzstd.so /out/libzstd-musl.so
# exit
$ ldd libzstd-musl.so
	linux-vdso.so.1 (0x00007fff82986000)
	libc.musl-x86_64.so.1 => not found
```
(The `not found` is because the host doesn't have a musl library)

**Comment by luben** [comment]
try to rebuild the zstd-jni jar in your target environment, it should link to the available libc.

**Comment by gyscos** [comment]
Oh, I hoped I could get a complete solution working both in the container and on the host. The application itself has `zstd-jni` has part of its maven dependencies. I suppose I could re-build `zstd-jni` and upload it to a private repository, but it still wouldn't work on both environments.

**Comment by luben** [comment]
Yes, but how do you decide which .so to extract and link at runtime?

**Comment by luben** [comment]
What about as a fallback to try to load the libzstd-jni from the system libraries path and you provide the libzstd-jni.so in the image's /usr/lib, compiled for your OS?

**Comment by gyscos** [comment]
That could work for me, though it does mean deploying applications to alpine-based containers aren't as straightforward if they depend on `zstd-jni`. :-/

**Comment by luben** [comment]
It will be another library, for example /usr/lib/libzstd-jni.so that will be produced by building this package. The artifact will be in target/classes/linux/amd64/ . As part of your container image you will copy it /usr/lib

**Comment by gyscos** [comment]
Ah right, I forgot the bundled `libzstd.so` included JNI methods as well.

**Comment by luben** [comment]
Hi, the new version (1.2.0-1) is now on Maven. Can you try it?

Regarding building the library without sbt I am using:

```
gcc -shared -fPIC -O3 -DZSTD_LEGACY_SUPPORT=4 -I/usr/include -I/usr/local/jdk/jre/../include -I/usr/local/jdk/jre/../include/linux -I./native -I./native/common -I./native/legacy -std=c99 -o libzstd-jni.so native/*.c native/legacy/*.c native/common/*.c native/compress/*.c native/decompress/*.c native/dictBuilder/*.c
```
but you should adjust the path to your JDK headers to match your system, you actually need only `jni.h` and `jni_md.h`

**Comment by luben** [comment]
@gyscos , any issues with it? Does it help your use case?

**Comment by gyscos** [comment]
I'm not sure what happened, but with the lastest `openjdk:alpine` and `zstd-jni` 1.2.0-2, I don't even need to copy the custom libzstd-jni anymore, the bundled one seems to be working...

**Comment by luben** [comment]
I compiled it on host with older glibc. Happy that it helps.

**Comment by gyscos** [comment]
I suppose the musl used in the alpine image isn't compatible yet with the latest glibc.
Anyway, thanks for the help!

**Comment by luben** [comment]
Thanks for coming back. I will keep compiling the future releases with relatively old libc (from ubuntu trusty I guess)
