### ISSUE TITLE
[ENQUIRY] why decompressing is using ByteBuffer.capacity instead of ByteBuffer.limit as its boundary

### ISSUE THREAD

**Issue by revintec** [luben/zstd-jni#39]
Hi, I'm using version 1.2.0, which is the newest version available as of writing this,
And I found no open or closed issue regarding this question.

com/github/luben/zstd/Zstd.java around line 695:
```java
    long size = decompressDirectByteBuffer(dstBuf, //decompress into dstBuf
    dstBuf.position(), //write decompressed data at offset position()
 ***dstBuf.capacity() - dstBuf.position(), //write no more than capacity() - position()
    srcBuf, //read compressed data from srcBuf
    srcBuf.position(), //read starting at offset position()
    srcBuf.limit() - srcBuf.position()); //read no more than limit() - position()
```
and later in line 704: dstBuf.position(dstBuf.position() + (int)size);
also in corresponding JNI native code, it seems that the dstBuf's limit is not respected.

this will not only cause runtime exception as shown below:

    Exception in thread "main" java.lang.IllegalArgumentException
        at java.nio.Buffer.position(Buffer.java:244)
        at com.github.luben.zstd.Zstd.compress(Zstd.java:354)
        ...

but it will also cause data corruption in violation to ByteBuffer's contract.

So my question here: is this a design decision? if so, why?

**Comment by luben** [comment]
Looks like an error

**Comment by revintec** [comment]
@luben OK, hope it get fixed soon

**Comment by luben** [comment]
The list commit (I just pushed it) makes the fix. I will push later today to sonatype/maven.

**Comment by luben** [comment]
@revintec , just pushed 1.2.0-2 with the changes
