### ISSUE TITLE
Native builds for MacOS X / Darwin

### ISSUE THREAD

**Issue by phraktle** [luben/zstd-jni#4]
Hi,

Thanks for the nice wrapper! Could you please also provide native builds for OS X?

Thanks,
  Viktor

**Comment by luben** [comment]
Yes, it should be easy. I have provisions in place to make it work on Darwin/OS X.

**Comment by luben** [comment]
Coming soon.

**Comment by luben** [comment]
Thanks to the Travis support for Mac OS X I have uploaded a new build on Maven with native support for mac_os_x-x86_64. It may take some time to become public though. Can you try it?

**Comment by luben** [comment]
It's on the maven central already

**Comment by phraktle** [comment]
Thanks for the quick response! Seems to be working fine.
