### ISSUE TITLE
could we have a constructor that enabling checksum as an option?

### ISSUE THREAD

**Issue by blackmagic02881** [luben/zstd-jni#41]
currently there is no way to enable checksum, which is unsafe. could we have an option to enable checksum? thanks.

**Comment by luben** [comment]
Seems reasonable. I will work on bringing zstd-1.3.0 this weekend and will also add an option to enable checksums.

**Comment by blackmagic02881** [comment]
thanks so much. really appreciated.

**Comment by luben** [comment]
Added an option to enable checksums when using ZstdOutputStream.

There is a rework going on Zstd with new API proposed (but not stable). When it stabilizes I will rework the zstd-jni internals and make it more convenient to set and get different flags.

Regarding the functional invocations, e.g. Zstd.compress(...) I still don't support setting flags, it will need more work.

I will release zstd-jni-1.3.0-1 in a couple of hours
