### ISSUE TITLE
UnsatisfiedLinkError: no zstd-jni in java.library.path

### ISSUE THREAD

**Issue by revintec** [luben/zstd-jni#44]
using 1.3.1-1(newest version as of writing) on Mac OS X 10.10.5(64bit):

java.lang.UnsatisfiedLinkError: no zstd-jni in java.library.path
Unsupported OS/arch, cannot find /darwin/x86_64/libzstd-jni.dylib or load zstd-jni from system libraries. Please try building from source the jar or providing libzstd-jni in you system.                            ClassLoader.loadLibrary(ClassLoader.java:1867)

as I recall, previous versions of zstd-jni worked on my OS

**Comment by luben** [comment]
Sorry for the delay. I will look soon - AFK this week.

**Comment by revintec** [comment]
the latest version on GitHub is v1.3.0-1, I'm currently using this version instead
1.3.1-1 is the latest version on maven-central

**Comment by luben** [comment]
I just pushed updated release to maven-central. I will land in a few hours. There is no functional changes, just includes also the missing binaries. Thanks for the report!
