### ISSUE TITLE
Support Older version of Linux distribution

### ISSUE THREAD

**Issue by sitalkedia** [luben/zstd-jni#47]
We are currently adding zstd compression support to Spark and we are using ztsd-jni for that. We are facing Spark unit tests failure because the library is compiled with a newer glibc requirement than the amplab machines have. Can you tweak your compilation to support older Linux distros?

See https://github.com/apache/spark/pull/18805#issuecomment-336524557 for more details.

**Comment by luben** [comment]
Thanks for notification. I just pushed v1.3.2-2 to maven that has the linux-amd64 library compiled on older distro (debian 6). It should become public in several hours. Please let me know if it works as expected on your test fleet.

**Comment by sitalkedia** [comment]
Thanks a lot for the quick turn around on this. Will let you know how it goes.

**Comment by vanzin** [comment]
This may also fix #43 (not sure what glibc that distro has).

**Comment by sitalkedia** [comment]
BTW, the change worked and Spark unit tests passed now.

**Comment by luben** [comment]
@sitalkedia, great! Thanks for coming back with the results. I will update my release process to use older distro for the amd64 shared object compilation.
