### ISSUE TITLE
Add ability to explicitly define src/dst heap buffer offset and size in decompress() method

### ISSUE THREAD

**Issue by jamel** [luben/zstd-jni#48]
Function ```ZSTD_decompress()``` expects to get _exact_ size of a single compressed frame.
In case of decompressing data stored on heap in byte-array it is not always possible to use ```long decompress(byte[] dst, byte[] src)``` binding function. Because ```byte[] src``` might not represent single compressed frame (e.g. data was read from socket in temporary buffer which contains several neighbouring frames).

It will be great to have overloaded decompress()  method with next signature:

```java
long decompress(byte[] dst, int dstOff, int dstLen, byte[] src, int srcOff, int srcLen)
```

**Comment by luben** [comment]
Isn't it more convenient to use the reader/writer interfaces? they will take care of the framing, streaming and buffer sizes.

**Comment by jamel** [comment]
In my case I need to decompress stream of ZTSD frames interleaved with custom header blocks (produced by internal C++ library which I cannot change because this will break a lot of other consumers).

A simplified version of the stream that I'm processing looks like this:
```
+---------+--------------+---------+--------------+---
+ header1 |  ZSTD frame1 | header2 |  ZSTD frame2 | ...
+---------+--------------+---------+--------------+---
```

So it is not possible to use stream implementations available in zstd-jni library.

**Comment by luben** [comment]
I see, I will expose it more directly.

**Comment by luben** [comment]
Please take a look at the last commit - it exposes (compress|decompress)ByteArray static methods following the (compress|decompress)DirectByteBuffer API with buffer sizes and offsets.

I can push it later to Maven

**Comment by jamel** [comment]
Looks very good! Thank you!

**Comment by luben** [comment]
It should come soon to maven as 1.3.2-3

**Comment by luben** [comment]
Hmm, sure. Looks like omission on my side

**Comment by luben** [comment]
Just uploaded the fixed JAR.

**Comment by jamel** [comment]
Now everything ok. Thanks again for your fast reply!
