### ISSUE TITLE
Add ppc64le support

### ISSUE THREAD

**Issue by odaira** [luben/zstd-jni#49]
Can you add libzstd-jni.so for linux/ppc64le to a binary release?  I have access to a ppc64le machine, so I can contribute it.  Or, would you like to build it yourself?

**Comment by luben** [comment]
Hi, looks I already have access to ppc64le, even the current linux/ppc64 is in fact little endian. I made the corrections on the build scripts and will release a patch version later today with fixed paths for ppc libraries.

**Comment by odaira** [comment]
Great!

Just for curiosity, when you add support for a new platform in the binary release, would you prefer building it yourself by getting access to that platform, or do you accept a contribution of the binary from someone else?  I know it depends on the projects, like snappy-java accepts contributions, while netty wants to build.

**Comment by luben** [comment]
I prefer to compile them myself in order to be sure that I can release them in the next versions. It's also a less overhead in communication.

**Comment by odaira** [comment]
Thanks for the reply!

**Comment by odaira** [comment]
Unfortunately, zstd-jni-1.3.2-5.jar does not work on ppc64le yet.  It has linux/ppc64/libzstd-jni.so, but not linux/ppc64le/libzstd-jni.so.

**Comment by luben** [comment]
Hmm, yes. You are right. Trying to fix it now

**Comment by luben** [comment]
It was compiled but not included in the jar. v1.3.2-6 with the fix is on the way to maven central.

**Comment by odaira** [comment]
Confirmed that zstd-jni-1.3.2-6.jar ran well on ppc64le.  Thanks!
