### ISSUE TITLE
Flushing the ZstdOutputStream with `closeFrameOnFlush=true` before closing it might cause "Underlying input stream returned zero bytes"

### ISSUE THREAD

**Issue by stmlange** [luben/zstd-jni#51]
Hi first of all thanks for this project!
I'm not quite sure if this is an edge case, but I came across an issue that seems to be caused when using the ZstdOutputStream with `closeFrameOnFlush=true` and issuing a flush before closing a BufferedWriter. In general when attempting to the read the data back again it causes a "Underlying input stream returned zero bytes" Exception. I feel it would be most help full to provide a full working minimal example (see blow) to reproduce this issue. I'm fully aware that close itself causes a flush, but in my case I want to "force-fully" flush every X-Elements. IMO the compression/decompression should should remain working when performing multiple flushes (potentially resulting in flush a NO-OP if no data need to be flushed). When removing the additional flush everything works fine. 

### Steps to Reproduce (for bugs only)
```java

import java.io.*;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;

import com.github.luben.zstd.ZstdInputStream;
import com.github.luben.zstd.ZstdOutputStream;

public class Sample {
    private static final int ZSTD_CLEVEL_DEFAULT = 3;

    public static void main(String[] args) throws Throwable {
        final File compressedFile = createTempFile("random_compressed");
        final File uncompressed = createTempFile("random_extracted");
        decompressFile(compressedFile, uncompressed);

        Files.lines(uncompressed.toPath()).forEach(System.out::println);
    }

    private static void createCompressedFile(final File compressedFile){
        try (final BufferedWriter writer = new BufferedWriter(new OutputStreamWriter(
                new ZstdOutputStream(
                        Files.newOutputStream(compressedFile.toPath()),
                        ZSTD_CLEVEL_DEFAULT, true),
                StandardCharsets.UTF_8))) {
            for (int i = 0; i < 20; i++) {
                writer.write(i + System.lineSeparator());
            }

            // when using an additional flush before the try-with-resources closes the stream the execution yields "java.io.IOException: Underlying input stream returned zero bytes"
            writer.flush();
        } catch (final IOException e) {
            e.printStackTrace();
        }
    }

    private static void decompressFile(
            final File compressedFile, final File uncompressed) throws IOException {
        final ZstdInputStream zstdInputStream = new ZstdInputStream(
                Files.newInputStream(compressedFile.toPath())).setContinuous(true);
        final BufferedReader fileReader = new BufferedReader(
                new InputStreamReader(zstdInputStream, StandardCharsets.UTF_8));

        try (final BufferedWriter fileWriter = Files.newBufferedWriter(uncompressed.toPath(),
                StandardCharsets.UTF_8)) {
            String line;
            while ((line = fileReader.readLine()) != null) {
                fileWriter.write(line);
            }
        }
    }

    private static File createTempFile(final String prefix) throws IOException {
        final File tempFile = File.createTempFile(prefix, ".tmp");
        tempFile.deleteOnExit();
        return tempFile;
    }
}
```

### Environment
```com.github.luben:zstd-jni:1.3.3-1```
```
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)
```

**Comment by luben** [comment]
Hi,

Makes sense. We can keep track if we have put new data after last flush and skip the new "end frame" if there is nothing written.

**Comment by stmlange** [comment]
Hi thanks for the quick fix, but it seems on my side that it has broken more than it fixed :/
As of right now it seems that regardless if I use `closeFrameOnFlush=true` or `closeFrameOnFlush=false` in the example above the results end up in `java.io.IOException: Underlying input stream returned zero bytes`. I'm not quite sure why this behavior is caused but I'd suspect that is also has to do with the underlying zstd libraries (does it do some frame closing?)

For full reference I have used my code-snippet I posted above and created a small sample project (based on https://github.com/gradle/gradle/tree/master/subprojects/docs/src/samples/java/quickstart) to rule out any random issue caused by used IDE.
The full project can be found here:
[sample-project.zip](https://github.com/luben/zstd-jni/files/1632022/sample-project.zip)

Is this only a problem on my side or caused by some strange side-effects?

**Comment by luben** [comment]
thanks,  will look in detail

**Comment by luben** [comment]
In your test case you are not creating the compressed file, there are no calls to "createCompressedFile". If I add "createCompressedFile(compressedFile);" just befor the call to decompressFile it works fine.

Without the fix the "java.io.BufferedReader.readLine" throws "java.io.IOException: Underlying input stream returned zero bytes", it's not Zstd - it does exactly what it should do - returns no bytes if the file is empty.

**Comment by stmlange** [comment]
Hi @luben,
oh yeah that's right! Sorry for overlooking the trivial case here....as you mentioned adding`createCompressedFile(compressedFile);` will solve my stupid copy-paste issue.

Thanks for your patience and in particular fixing the original issue so quickly :)

Closing this now ~ works as expected :-)
