### ISSUE TITLE
ARM32 support

### ISSUE THREAD

**Issue by cyrilmhansen** [luben/zstd-jni#53]
Maven artefacts does not seems to support non 64bits ARM architecture.
ZStandard library does, is it possible to build zstd-jni for ARM 32 bits architectures like ARM7 ? How ?
Thanks

**Comment by luben** [comment]
Hi, unfortunately I don't have access to Arm32 with development environment. It's quite easy to build it your self, just to `sbt publishLocal` and you will get a JAR in you local ivy repo.

I will add the script that  I use to compile the binaries without going through sbt as this may be easier for you to use.

**Comment by luben** [comment]
Hi,
just pushed the script that I use to compile the native part on the hosts that lack JDK. Please take a look at https://github.com/luben/zstd-jni/blob/master/make_so.sh for inspiration.

**Comment by cyrilmhansen** [comment]
Ok thanks, I will look into it.

2018-02-01 0:03 GMT+01:00 luben karavelov <notifications@github.com>:

**Comment by luben** [comment]
Hi,
If you prefer there is now a fully functional cmake build that can compile the native lib, to be included in the JAR.
Regards,
luben
