### ISSUE TITLE
crash when calling trainSamples() of ZstdDictTrainer

### ISSUE THREAD

**Issue by moshtagh** [luben/zstd-jni#55]
I need to use compress with dictionary. After add samples to ZstdDictTrainer, and when calling trainSamples it crashes and makes this error:

art/runtime/java_vm_ext.cc:470] JNI DETECTED ERROR IN APPLICATION: jfieldID int java.nio.Buffer.capacity not valid for an object of class int[]
art/runtime/java_vm_ext.cc:470]     in call to GetIntField
art/runtime/java_vm_ext.cc:470]     from long com.github.luben.zstd.Zstd.trainFromBufferDirect(java.nio.ByteBuffer, int[], java.nio.ByteBuffer)
art/runtime/java_vm_ext.cc:470] "main" prio=5 tid=1 Runnable
art/runtime/java_vm_ext.cc:470]   | group="main" sCount=0 dsCount=0 obj=0x74fac610 self=0xa988b400
art/runtime/java_vm_ext.cc:470]   | sysTid=9405 nice=-10 cgrp=default sched=0/0 handle=0xadc3e534
art/runtime/java_vm_ext.cc:470]   | state=R schedstat=( 0 0 0 ) utm=28 stm=41 core=3 HZ=100
art/runtime/java_vm_ext.cc:470]   | stack=0xbf683000-0xbf685000 stackSize=8MB
art/runtime/java_vm_ext.cc:470]   | held mutexes= "mutator lock"(shared held)
art/runtime/java_vm_ext.cc:470]   native: #00 pc 00572f1e  /system/lib/libart.so (_ZN3art15DumpNativeStackERNSt3__113basic_ostreamIcNS0_11char_traitsIcEEEEiP12BacktraceMapPKcPNS_9ArtMethodEPv+238)

**Comment by luben** [comment]
Hmm, that's strange, I thought it's well tested. Can you post some minimal example?

**Comment by moshtagh** [comment]
The following is part of my code where I want to make dictionary from samples. Here my samples is array string with length 4. Each sample string length is less than 500 characters

        ZstdDictTrainer trainer = new ZstdDictTrainer(1024 * 1024, 32 * 1024);
        String[] samples = context.getResources().getStringArray(R.array.samples);
        for (String s : samples) {
            try {
                trainer.addSample(s.getBytes("UTF-8"));
            } catch (UnsupportedEncodingException e) {
                e.printStackTrace();
            }
        }
        trainer.trainSamples();

It craches on last line when trainer.trainSamples is called;

**Comment by luben** [comment]
hmm, can you try something in the same spirit but without going through the dict trainer class? This will narrow-down the bug place. Pseudo-code below:
```
String[] samples = ...
byte[][] samples_bytes = Arrays.stream(samples).map((s) -> s.getBytes("UTF-8")).toArray(byte[][]::new);
byte[] dict_buff = new byte[32 * 1024];
int dict_len = Zstd.trainFromBuffer(samples_bytes, dict_buff);
bytes[] dict = Arrays.copyOfRange(dict_buff, 0, dict_len-1);
```

**Comment by moshtagh** [comment]
The latter works fine. The error may be related to use of buffer. I prefer to use buffer, becuase my real data has several thousand records. could you fix the bug?

**Comment by luben** [comment]
Hi,

I just pushed a commit that hopefully fixes it. Can you test it? I will push a release later today as I don't have my keys with me now.

Regards,

**Comment by luben** [comment]
I pushed 1.3.3-4 with the fix. It's already on maven-central. Can you try if it fixes the issue?

**Comment by moshtagh** [comment]
Hi,
Thanks so much. The problem was solved.
Best regards

**Comment by luben** [comment]
Thanks for reporting it. There was some unnecessary code left.

**Comment by smiklosovic** [comment]
hi @luben 

what does this mean?

        ZstdDictTrainer trainer = new ZstdDictTrainer(1024 * 1024, 32 * 1024);

what are 1024 * 1024 and 32 * 1024?

I do this

        String jsonString1 = "very long hello world string 1";
        String jsonString2 = "very long hello world string 2";
        String jsonString3 = "very long hello world string 3";

        ZstdDictTrainer trainer = new ZstdDictTrainer(1024 * 1024, 32 * 1024);
        trainer.addSample(jsonString1.getBytes(StandardCharsets.UTF_8));
        trainer.addSample(jsonString2.getBytes(StandardCharsets.UTF_8));
        trainer.addSample(jsonString3.getBytes(StandardCharsets.UTF_8));
        trainer.trainSamples();

and it throws:

com.github.luben.zstd.ZstdException: Src size is incorrect

	at com.github.luben.zstd.ZstdDictTrainer.trainSamplesDirect(ZstdDictTrainer.java:40)
	at com.github.luben.zstd.ZstdDictTrainer.trainSamples(ZstdDictTrainer.java:51)
	at com.github.luben.zstd.ZstdDictTrainer.trainSamples(ZstdDictTrainer.java:47)
	at org.apache.cassandra.io.compress.ZstdCompressorTest.testDict(ZstdCompressorTest.java:71)

**Comment by luben** [comment]
> new ZstdDictTrainer(1024 * 1024, 32 * 1024);
This configures dict trainer to expect 1024*1024 bytes as samples - they have to match.
