### ISSUE TITLE
java.io.IOException: Decompression error: Unknown frame descriptor

### ISSUE THREAD

**Issue by stmlange** [luben/zstd-jni#56]
Hi,
sorry to bother again, but unfortunately I bumped into an issue where I'm actually not quite sure what is causing this and how to fix it. Even though the issue is reproducible (in production) and always points a specific piece of code I'm currently unable to tell what is causing this behaviour.

In a nutshell what I'm currently doing is that I create a writer with ``closeFrameOnFlush=true`` and a reader with ``continuous=true``. Reader and writer might run in parallel threads. The writer-Thread flushes every x-Elements (e.g. every 100 elements) and notifies the reader that he can start reading. Since the zstd-Frame is closed at a flush on the writer side and continuous-Mode is enabled on reader side this should technically just give the reader a complete frame to read and should not cause an Exception.

Implementation wise the reader and writer are created in the following way (quite similar to what I outlined in https://github.com/luben/zstd-jni/issues/52 just with threads)
```java
            private static final int ZSTD_CLEVEL_DEFAULT = 3;
            // create writer
            final BufferedWriter writer = new BufferedWriter(
                    new OutputStreamWriter(new ZstdOutputStream(
                            Files.newOutputStream(compressedFile.toPath()),
                            ZSTD_CLEVEL_DEFAULT, true),
                            StandardCharsets.UTF_8));
            // create reader
            final BufferedReader reader = new BufferedReader(
                    new InputStreamReader(
                            new ZstdInputStream(
                                Files.newInputStream(compressedFile.toPath())
                            ).setContinuous(true),
                            StandardCharsets.UTF_8));

```

The Exception that currently pops up is the following:
```
java.io.IOException: Decompression error: Unknown frame descriptor
	at com.github.luben.zstd.ZstdInputStream.read(ZstdInputStream.java:111)
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	at java.io.InputStreamReader.read(InputStreamReader.java:184)
	at java.io.BufferedReader.fill(BufferedReader.java:161)
	at java.io.BufferedReader.readLine(BufferedReader.java:324)
	at java.io.BufferedReader.readLine(BufferedReader.java:389)
```

I currently can't reproduce the issue with testcases (so the tests and code seems to work fine), but the "production" code is producing this exception reliably. Cleaning up any produced files and have them regenerated on-the-fly does not fix the issue.

I can reproduce the issue with ``1.3.3-4`` and ``1.3.4-1``

When looking at the zstd-project the issue seems to be related with "Support for Legacy format". Since I can also reproduce the issue with a clean work environment the files generated are not "old" hence I don't see any relation.

Just a side note:
I can open the files with the zstd command-line tools without any error-messages.

Any help on how to troubleshoot this further or what might go wrong is appreciated.

**Comment by luben** [comment]
That's very strange. Can you try constructing the `ZstdInputStream` without `setContinuous` ? It should work as the frames are closed on flush and you are reading only after flush. I will remove one code-path from debugging the problem.

I have also just pushed a fix for one corner-case int he OutputStream - I don't think this is the root cause here but 1 less bug is always better :)

I am going to publish the 1.3.4-2 with the bugfix in a 7-8 hours.

**Comment by stmlange** [comment]
Sure I can try running without ``setContinuous(true)``. A "run" usually takes ~4h so might take some time to actually see if this fixes the situation.

I wish this issue was more straightforward...for the others I could at least provide a snippet on how to reproduce them, but for this one I'm pretty much digging in the dark.

**Comment by luben** [comment]
I have just published the 1.3.4-2 version with the fix for the writer. It will take 1-2 hours to get to maven central.
 
BTW, I am happy you raise these issues - some of the paths are not well tested in all the scenarios. If we can make the final product better for everyone in the future it's your contribution.

Regards,
luben

**Comment by luben** [comment]
Now thinking again, the bug in the output stream fixed in 1.3.4-2 could manifest with the symptoms you are seeing on the input stream side,

**Comment by stmlange** [comment]
Interestingly running without ``setContinuous(true)`` and ``1.3.4-1`` the error pops up and a different place (so its seems that this might have been the reason for at least one particular case)

Now running without ``setContinuous(true)`` and ``1.3.4-2``

**Comment by stmlange** [comment]
Since everything seems to work fine with `1.3.4-2` I'll close the ticket and consider it as fixed by
https://github.com/luben/zstd-jni/commit/162661e867f0a279859da2c6eb9cdc7793355bbc

Thanks again for your help and the quick fix :-)

**Comment by luben** [comment]
Thanks for reporting and testing the fix.
