### ISSUE TITLE
Handle decompression of empty files more graceful

### ISSUE THREAD

**Issue by stmlange** [luben/zstd-jni#59]
Hi,
I'm pretty sure this is one of the annoying corner cases again :-P

In short I think the handling of the decompression of empty files should be handled more gracefully.
I bumped into a [similar issue](https://github.com/luben/zstd-jni/issues/51#issuecomment-357708615) when attempting to decompress empty files with zstd and ``continuous=true``. I now use zstd for another use-case where I don't necessarily need ``continuous=true`` and noticed that zstd fails with ``Read error or truncated source`` while trying to decompress an empty file with ``continuous=false`` . 

I think the root cause is residing in the fact that the ZstdInputStream gets initialized with ``frameFinished = false`` even though we never read a frame. When opening an empty file with ``Files.newInputStream(originalFile.toPath())`` no exception is thrown and I believe this is exactly how ZstdInputStream should handle the case with ``continuous=false``  (implementation still can fail with ``continuous=true``). As of now it seems that ZstdInputStream only can handle files with at least one frame.

Sample-Code
```java
package com.nuance.stark.internal.dataflow;

import java.io.*;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;

import com.github.luben.zstd.ZstdInputStream;

public class Sample {
    public static void main(String[] args) throws Throwable {
        final File file = createTempFile("random_compressed");

        try {
            readFileWithFis(file);
        } catch (final IOException e) {
            System.out.println("Exception 1: " + e.getMessage());
        }

        try {
            readFileWithZstd(file, true);
        } catch (final IOException e) {
            System.out.println("Exception 2: " + e.getMessage());
        }

        try {
            readFileWithZstd(file, false);
        } catch (final IOException e) {
            // OOF: IMHO not needed to throw an exception
            System.out.println("Exception 3: " + e.getMessage());
        }
    }

    private static void readFileWithFis(final File originalFile)
            throws IOException {
        final InputStream inputStream = Files.newInputStream(originalFile.toPath());
        try (final BufferedReader fileReader = new BufferedReader(
                new InputStreamReader(inputStream, StandardCharsets.UTF_8))) {
            String line;
            while ((line = fileReader.readLine()) != null) {
                System.out.println(line);
            }
        }
    }

    private static void readFileWithZstd(final File originalFile, boolean continuous)
            throws IOException {
        final ZstdInputStream zstdInputStream = new ZstdInputStream(
                Files.newInputStream(originalFile.toPath())).setContinuous(continuous);
        try (final BufferedReader fileReader = new BufferedReader(
                new InputStreamReader(zstdInputStream, StandardCharsets.UTF_8))) {
            String line;
            while ((line = fileReader.readLine()) != null) {
                System.out.println(line);
            }
        }
    }

    private static File createTempFile(final String prefix) throws IOException {
        final File tempFile = File.createTempFile(prefix, ".tmp");
        tempFile.deleteOnExit();
        return tempFile;
    }
}
```

**Comment by luben** [comment]
Makes sense, I heven't tested this case. I am leaving for a week but will look at it soon.

**Comment by stmlange** [comment]
Hi,
sorry to bother again with this issue, but did you had the chance to look into it?
Would be greatly appreciated :-)

**Comment by luben** [comment]
Hi, thanks for the patience. Yes, you are right that initializing frameFinished solves the issue.

I have it committed and pushed. I will publish it to Maven later today.

**Comment by luben** [comment]
I pushed it to Maven-central, version 1.3.4-6 , it should come soon.

**Comment by stmlange** [comment]
Hi,
thanks for releasing the version.
Everything seems to work fine with `1.3.4-6`.

Thanks again for the fix and sorry for nagging to get this integrated :-P
