### ISSUE TITLE
java.lang.UnsatisfiedLinkError: no zstd-jni in java.library.path

### ISSUE THREAD

**Issue by stmlange** [luben/zstd-jni#60]
Hi,
sorry to bother again, but after some testing with the new `1.3.4-6` release I bumped into an issue I can't really explain.
In short I have a gradle project and the stacktraces I get in pre-prod are the following:
```
java.lang.UnsatisfiedLinkError: no zstd-jni in java.library.path
Unsupported OS/arch, cannot find /linux/amd64/libzstd-jni.so or load zstd-jni from system libraries. Please try building from source the jar or providing libzstd-jni in you system.
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at com.github.luben.zstd.util.Native.load(Native.java:101)
	at com.github.luben.zstd.ZstdOutputStream.<clinit>(ZstdOutputStream.java:17)
```
and
```
java.lang.NoClassDefFoundError: Could not initialize class com.github.luben.zstd.ZstdOutputStream
```
Surprisingly everything seems to be working fine in my local linux environment and I can't reproduce the issue there.

In the effected environment the exception is getting raised reliable at the same places, indicating that something? (not sure what) is broken. I have run tests with several versions that [are available on the maven repo](https://repo1.maven.org/maven2/com/github/luben/zstd-jni/) and this is the current results based on the used version

[1.3.4-6](https://github.com/luben/zstd-jni/commit/a2b91ab3e0b7935edeca2da95ae17455ffaa9ebe) - broken with exception
1.3.4-5 (seems non existent in git repo) - broken with exception below
1.3.4-4 (seems not to be aligned with version in git repo) - causes the IO Exception from https://github.com/luben/zstd-jni/issues/59
[1.3.4-3](https://github.com/luben/zstd-jni/commit/44f709d9dd918544df6d80050c6d3cfd54df17b9) - causes the IO Exception from https://github.com/luben/zstd-jni/issues/59
[1.3.4-2](https://github.com/luben/zstd-jni/commit/162661e867f0a279859da2c6eb9cdc7793355bbc) - causes the IO Exception from https://github.com/luben/zstd-jni/issues/59

When I checkout the zstd-jni project locally and build it via `sbt-1.1.4/sbt/bin/sbt publishLocal` or even `./sbt publishLocal` and use the artifact as dependency in my project via `files('..../.ivy2/local/com.github.luben/zstd-jni/1.3.4-fixed/bundles/zstd-jni.jar')` everything is working fine too. For me it seems that something? in the deployment is broken, or I'm not doing the same steps (not sure).
Would kindly appreciate any advice on how to debug this further.

**Comment by luben** [comment]
I guess your pre-prod has older libc and it looks I forgot to copy the native .so from the a build on a legacy system. I will post new version.

**Comment by luben** [comment]
Pushed a new version, 1.3.4-7. Hope it solves the problem

**Comment by stmlange** [comment]
Hi,
thanks again for the quick update.
Indeed our pre-prod and prod systems might use some legacy versions mainly due to SLA-Agreements :/

I can confirm that `1.3.4-7` solved the issue.
Thanks again and sorry for all the trouble :-)
