### ISSUE TITLE
Invalid automatic module name

### ISSUE THREAD

**Issue by hsiafan** [luben/zstd-jni#64]
In sbt build file,  "com.github.luben.zstd-jni" is set as automatic module name. However, jdk module name cannot contains dash('-') char. Maybe we can use "com.github.luben.zstd_jni".

**Comment by luben** [comment]
Yes, modules are new. I will see how can I keep the artifact name and change just the module name. Do you think it's possible?

**Comment by hsiafan** [comment]
Yes, module name can differ from artifact name, infact they are already different(com.github.luben.zstd-jni vs zstd-jni). Seems  changing Automatic-Module-Name setting in build.sbt is all things need to do.

**Comment by luben** [comment]
Thanks, just pushed the fix, next release will have it right

**Comment by luben** [comment]
zstd-jni-1.3.4-11 just landed on Maven Central with the fix.
