### ISSUE TITLE
Release tags

### ISSUE THREAD

**Issue by joschi** [luben/zstd-jni#65]
Thanks for maintaining this immensely useful project!

It would be great, if you could retroactively add tags to this repository the zstd-jni [releases on Maven Central](http://mvnrepository.com/artifact/com.github.luben/zstd-jni) are based on.

**Comment by luben** [comment]
Hi, I pushed some recent version tags. Which tag you are initeresed in, if it's missing?

**Comment by joschi** [comment]
@luben Awesome, thank you. 😃 

I wasn't interested in one specific tag, but wanted to be able to show the diffs between the different versions easily.

I'll close this issue, since the tags are there now.
