### ISSUE TITLE
File Compression and Decompression Code for Brotli and ZStd in JAVA

### ISSUE THREAD

**Issue by PavithranSubramanian** [luben/zstd-jni#67]
Hello,
I was looking for File compression and File Decompression code in Java using BROTLI and ZStandard.
But all i found was a sample code using Byte[] and compressing a single string as byte buffer.

If Possible try a File Compression and File Decompression in Brotli and ZStd using Java.
Here File means any type of file without any specification.

**Comment by luben** [comment]
Hi, there is not high-level utility function to just compress/decompress file but it implements the more general Input/Output Stream interfaces. Take a look here for an example of decompression:

https://github.com/luben/zstd-jni/blob/master/src/test/scala/Zstd.scala#L339-L358

**Comment by PavithranSubramanian** [comment]
Hello luben,nice to hear from you.Actually im looking for best compression algorithm that can be used to compress and decompress a file and found Brotli is the best compression around.But i couldnt find a complete implementation of my requirement. Im currently developing a java file compression code using Brotli . is it possible with Java.?

**Comment by luben** [comment]
I don't know about brotli, have not worked with it. The example in the previous message was how to do it with Zstd

**Comment by PavithranSubramanian** [comment]
yes luben.i was also looking for ZStd . thnx fr share...leeme try with it

**Comment by PavithranSubramanian** [comment]
Do you know any other Powerful fully implemeted Algorithm that compresses file with high compression ratio other than 7zip ( already worked..but my req is more than 7Zip compression ratio )?
 
Thanks & regards

**Comment by luben** [comment]
LZMA implementations usually achieve high compression ration at the expense of speed.
