### ISSUE TITLE
Allow user to specify custom temp folder

### ISSUE THREAD

**Issue by expressoCoder** [luben/zstd-jni#69]
Needed for production systems where system temp folder is locked down

**Comment by luben** [comment]
Reopening. Will close it on next release.

**Comment by alamar** [comment]
It is perhaps possible to have builds where native library is statically linked to JNI wrapper?

**Comment by luben** [comment]
I just pushed v1.3.5-4 with this change. Unfortunately I had to revert the other PR #74 as the NIO2 API was added in Android quite recently.
