### ISSUE TITLE
Compressing an empty byte array and reading it back using ZstdInputStream returns 0 instead of -1

### ISSUE THREAD

**Issue by sivasankariit** [luben/zstd-jni#75]
When an empty byte array is compressed with zstd and the resulting compressed array is read from using ZstdInputStream, the stream returns 0 instead of -1. `InputStream.read()` should return -1 when  no byte is available because the end of the stream has been reached.

Sample test code to reproduce the error:

```
import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.util.Arrays;

import org.testng.annotations.Test;

import com.github.luben.zstd.Zstd;
import com.github.luben.zstd.ZstdInputStream;

public class Sample {

    @Test
    public void testEmptyStream() throws IOException {
        int COMPRESSION_LEVEL = 3;
        byte[] EMPTY = new byte[0];

        //noinspection NumericCastThatLosesPrecision
        int maxCompressedSize = (int) Zstd.compressBound(EMPTY.length);
        byte[] compressed = new byte[maxCompressedSize];
        long compressedSize =
            Zstd.compressByteArray(compressed, 0, maxCompressedSize, EMPTY, 0, EMPTY.length, COMPRESSION_LEVEL);
        assert !Zstd.isError(compressedSize);

        //noinspection NumericCastThatLosesPrecision
        compressed = Arrays.copyOf(compressed, (int) (compressedSize));

        try (InputStream inputStream = new ZstdInputStream(new ByteArrayInputStream(compressed))) {
            assert inputStream.read() == -1;  // This assertion fails.
        }
    }
}
```

**Comment by luben** [comment]
Yes, you are right. Pushing a fix and a test.

**Comment by luben** [comment]
Thanks for reporting it!

**Comment by sivasankariit** [comment]
Thanks for the quick fix! The root cause of the problem actually seems to be in `public int read(byte[] dst, int offset, int len)`.

`InputStream.read(byte b[], int off, int len)` has similar semantics, quoting from the javadoc:
> If len is zero, then no bytes are read and 0 is returned; otherwise, there is an attempt to read at least one byte. If no byte is available because the stream is at end of file, the value -1 is returned; otherwise, at least one byte is read and stored into b.

Can you please extend the fix to cover that method too?

**Comment by luben** [comment]
I think this is difference in interpretation. The current `read(buf, offset, len)` is not going to produce wrong result as was the case with `read()` that you reported. As I read the docs, read bytes / return value is up to `len`, I assume, including 0:

>  Reads up to len bytes of data from the input stream into an array of bytes. An attempt is made to read as many as len bytes, but a smaller number may be read.

If you want to read `x` bytes you should loop (modifying the buf offset param) until `x` total bytes are reported read - there is no guarantee that the whole `len` will be read in one go. So adding a check in the `read(buf, offset, len)` method will be redundant with what the user code should be doing anyway.

Reading the docs it's unclear what refers to the method contract and what refers to the default implementation in terms of `InputStream.read()`.

More on the current implementation. We can read 0 bytes if we are at the end of compression frame. The next call to `read` will try to open the next frame and return -1 if no more data is available. We can make it match the default implementation by inserting additional loop (possibly make the current method private and leave only the loop in the override method). Do you have a use case where the difference in beavour will matter?

**Comment by sivasankariit** [comment]
Yes, it appears a bit confusing, but the expected behavior as implemented by other `InputStream` implementations is that `read(buf, offset, len)` can return 0 only if `len == 0`. Otherwise, the method blocks until input data is available, or returns -1 if the end of the stream has been reached. 

I am using the ZstdInputStream as the backing input stream for [com.google.protobuf.CodedInputStream](https://github.com/protocolbuffers/protobuf/blob/d61aede/java/core/src/main/java/com/google/protobuf/CodedInputStream.java#L2784). When reading from the stream, `CodedInputStream` throws an IllegalStateException when the backing `InputStream` returns unexpected values.

**Comment by luben** [comment]
Yes, I am making it now follow the behaviour of the other implementations (comparing with GZIPInputStream). If you want to test it, I think all the fixes are already pushed.

I will publish a ne version in the weekend.
