### ISSUE TITLE
Java API for getting dictionary ID from compressed bytes

### ISSUE THREAD

**Issue by mjiderhamn** [luben/zstd-jni#76]
Please add support in the Java API for getting a dictionary ID (dictID) from a `byte[]` containing data compressed with a dictionary. In practice I assume this means invoking `ZSTD_getDictID_fromFrame` through JNI.

**Comment by luben** [comment]
Added 2 new static methods: Zstd.getDictIdFromFrame and getDictIdFromDict in 89b9b4fc

**Comment by luben** [comment]
released in v1.3.6-1
