### ISSUE TITLE
Dictionary Id not being written into zstd compressed frame header

### ISSUE THREAD

**Issue by hari-rangarajan** [luben/zstd-jni#77]
Haven't investigated deeply into the C api, but by default compressions with a dictionary do not seem to be stamping the compressed payloads with the dictionary id using the zstd jni api. The command line tool has a (no dict header option) 
'--no-dictID : don't write dictID into header (dictionary compression)'
Wonder if it is getting enabled somewhere in the jni translation layers.

**Comment by luben** [comment]
I will investigate. I haven't used this functionality

**Comment by luben** [comment]
It looks dictIDs are "on" by default: https://github.com/facebook/zstd/blob/dev/lib/zstd.h#L1086

Are you using the ZstdOutputStream or Zstd.compress interface in your tests?

**Comment by luben** [comment]
Also if using Zstd.compress*, are you using the byte array dict or fast dict. Look like using fast dict is enabling dictIDs: https://github.com/facebook/zstd/blob/dev/lib/zstd.h#L239

**Comment by hari-rangarajan** [comment]
Thanks @luben. I wrote my own Java header manipulation routines to write IDs directly and that was working until I started doing a different workflow: I trained the dictionary using the command line zstd and used the jni for the compression. I was previously doing both in JNI. Let me create more tests and see if I can isolate it to a problem (or just user error).

**Comment by hari-rangarajan** [comment]
@luben My bad. I was loading the dictionary from file with incorrect encoding. Zstd allows also non-standard dictionaries to be added via the regular method. I guess it didn't find the magic header and assumed it was non-standard and marked it as no dictionary or version. This way, it wasn't stamping the version but forced dictionary usage was still working.

Thanks for investigating and adding the test cases to confirm.
