### ISSUE TITLE
Support ZSTD_minCLevel and ZSTD_maxCLevel 

### ISSUE THREAD

**Issue by svladykin** [luben/zstd-jni#80]
Subj.

**Comment by luben** [comment]
I will release it with the next batch of changes - will keep the issue open until release,

**Comment by svladykin** [comment]
Thanks a lot! 
BTW, what is the min and max compression levels in the latest released version?

**Comment by luben** [comment]
scala> Zstd.minCompressionLevel()
res0: Int = -131072

scala> Zstd.maxCompressionLevel()
res1: Int = 22

**Comment by luben** [comment]
Just released 1.3.7-2 to Maven-central.

**Comment by svladykin** [comment]
Thank you very much!
