### ISSUE TITLE
IOException when trying to decompress concatenated zstd file

### ISSUE THREAD

**Issue by tomerz90** [luben/zstd-jni#87]
I concatenated a bunch of zstd files and the zstd cli tool is able to decompress them but when I try to read it using `ZstdInputStream` in Java I get `java.io.IOException: Decompression error: Unknown frame descriptor`.
The zstd files I concatenated where created using the python package.
File: https://ufile.io/7r5ik

**Comment by tomerz90** [comment]
Was using a outdated version, it happens in 1.3.8-1 but fixed in 1.3.8-3

**Comment by luben** [comment]
Yes, the 1.3.8-3 is providing just this fix. Thanks anyway for reporting it!

**Comment by tomerz90** [comment]
Thank you, for the fast response, and for this compression format, awesome work!
