### ISSUE TITLE
Setting flags when using Zstd::compress / Zstd::decompress methods

### ISSUE THREAD

**Issue by dineshjoshi** [luben/zstd-jni#89]
It would be nice to easily set flags while using the compression / decompression methods. This was already brought up in issue #41. In particular I'm interesting in setting the checksum flag. Could you add that as an option in the `Zstd` class?

**Comment by luben** [comment]
These static methods translate directly to the ZSD_compress and ZSTD_decompress methods. There are no variants with options. If you need to enable/disable some of the them, you can do it through the ZstdInputStream/ZstdOutputStream.

**Comment by dineshjoshi** [comment]
Can you point me to an example?

**Comment by luben** [comment]
https://github.com/luben/zstd-jni/blob/master/src/test/scala/Zstd.scala#L224-L257

and there is a constructor argument and method to enable checksums in the ZstdOutputStream:

https://static.javadoc.io/com.github.luben/zstd-jni/1.3.8-3/com/github/luben/zstd/ZstdOutputStream.html

**Comment by dineshjoshi** [comment]
Is it fine to use `ZstdOutputStream` to compress with the checksum flag on and then decompress using `Zstd::decompress`?

**Comment by luben** [comment]
Yes, if present checksums are always checked.
