### ISSUE TITLE
Add Zstd::compress variant that enables checksumming

### ISSUE THREAD

**Issue by dineshjoshi** [luben/zstd-jni#90]
So, I know we've discussed this in Issue #89 but I was going through the Zstd source and found that we could simply enable the checksumming flag on the ZSTD_CCtx. The reason we'd like this to be part of the JNI rather than using streams is that, using streams would generate a lot of garbage in the JVM as opposed to adding this into the JNI utility. Here's a mock up of the change that is needed (In src/main/native/compress/zstd_compress.c) -

```
size_t ZSTD_compress_checksummed(void* dst, size_t dstCapacity,
               const void* src, size_t srcSize,
                     int compressionLevel)
{
    size_t result;
    ZSTD_CCtx ctxBody;
    ZSTD_initCCtx(&ctxBody, ZSTD_defaultCMem);
    ZSTD_CCtx_setParameter(&ctxBody, ZSTD_c_checksumFlag, 1);

    result = ZSTD_compressCCtx(&ctxBody, dst, dstCapacity, src, srcSize, compressionLevel);
    ZSTD_freeCCtxContent(&ctxBody);   /* can't free ctxBody itself, as it's on stack; free only heap content */
    return result;
}
```

We'd need to add a new JNI method and plumb the call through to zstd_compress.c but it is doable. It would really help out if you could make this part of the JNI.

**Comment by luben** [comment]
Fare enough. I will add it in the next version. Do you want to send a PT? I better have your name as you have the code already working.

**Comment by luben** [comment]
BTW, I missed this variant when looking in zstd.h

**Comment by dineshjoshi** [comment]
Hi @luben perhaps I wasn't clear. This would be a new method that we would as part of the JNI. It is the same as `ZSTD_compress` except that it calls `ZSTD_CCtx_setParameter(&ctxBody, ZSTD_c_checksumFlag, 1);` to enable the checksum flag.

**Comment by luben** [comment]
Yes, I can copy your code from above and write the Java part, or you can send me the CR yourself if you prefer.

**Comment by luben** [comment]
Merged and released: https://repo1.maven.org/maven2/com/github/luben/zstd-jni/1.3.8-5/

Thanks for the contribution!

**Comment by dineshjoshi** [comment]
Thank you! The Apache Cassandra project is grateful! 👍
