### ISSUE TITLE
Multi-threading mode support

### ISSUE THREAD

**Issue by hc-codersatlas** [luben/zstd-jni#92]
Hi, the advanced API supports multi-threading. Can this be added as an option to select the number of threads? This should help improve performance. Thanks!

See: https://github.com/facebook/zstd/blob/dev/lib/zstd.h#L595

**Comment by luben** [comment]
Yes, I am slowly migrating to the AdvancedAPI and will expose the threads/worker param also.

**Comment by luben** [comment]
Currently this is the blocker to migrate the compression side to the advanced API: https://github.com/facebook/zstd/issues/1544

**Comment by luben** [comment]
Hi, with the last commit I have provided `setWorkers` method on `ZstdOutputStream`. It  should enable the multi-threading but I have not tested it.

**Comment by hc-codersatlas** [comment]
Thanks. Is it possible to use it with byte[] or bytebuffer directly? Or is it only for streams?

**Comment by luben** [comment]
It's only for streams. There is a new API, `ZSTD_compressCCtx` that I intend to bind to but it's not there yet.

**Comment by luben** [comment]
BTW, I pushed v1.3.8-6 to Maven central, if you want to test it.

**Comment by julien-pcd** [comment]
I'm getting an "_Unsupported parameter_" error when calling `setWorkers()`. The [Zstandard manual ](https://facebook.github.io/zstd/zstd_manual.html#Chapter13) indicates multi-threading parameters require the build macro **`ZSTD_MULTITHREAD`**. If this is the reason, do you plan to provide a release with this enabled?

Thanks!

**Comment by luben** [comment]
Hmm, looks like I missed it and didn't have test. I will fix soon.

**Comment by luben** [comment]
@julien-pcd , I just pushed v1.3.8-7 to Maven central - it is compiled with ZSTD_MULTITHREAD defined.

**Comment by tomerz90** [comment]
@luben Is this default 1 or same default in the lib?

**Comment by luben** [comment]
@tomerz90 , by default it does not use multiple threads/workers - multi-threading have to be explicitly enabled with setWorkers(n)

**Comment by tomerz90** [comment]
I see, thanks
