### ISSUE TITLE
High memory usage

### ISSUE THREAD

**Issue by tomerz90** [luben/zstd-jni#93]
Im using this code:
```
public static void main(String[] args) throws IOException {
    Set<ZstdOutputStream> streams = new HashSet<>();
    for (int i = 0; i < 600; i++) {
      File f = new File("/test/" + i);
      f.createNewFile();
      ZstdOutputStream zstd = new ZstdOutputStream(new FileOutputStream(f));
      for (int j = 0; j < 100_000; j++) {
        zstd.write(UUID.randomUUID().toString().getBytes());
      }
      streams.add(zstd);
    }
    streams.forEach(f -> {
      try {
        f.close();
      } catch (IOException e) {
        e.printStackTrace();
      }
    });
```
The memory consumption seems to correlate with how much im writing to the streams (I stopped it when it got to a 1.8 GB memory usage).
Is this normal for zstd? Does it not use fixed size buffers? Am I misusing it somehow?
Tested on versions 1.3.8- 3-5.

**Comment by luben** [comment]
Zstd uses around 384KB buffers per compression context in the native  library. Then there is another 128K on the Java side for a buffer between compression and underlying OutputStream. So it adds to 512KB. All of them are statically allocated.

Have you figured what's happening with this test case?

**Comment by tomerz90** [comment]
Talked to someone who told me this memory usage makes sense so I thought it was just me that is wrong.
I was wrong a bit in my descriptions, the memory usage doesnt go up when I increase `hashes` but it does get to 1.8+ GB in the code I provided.
Your help would be appreciated.

**Comment by luben** [comment]
Yes its comes to 3MB per OutputStream in your case. You should be aware that there is memory overhead due to how JVM GC works. Can print the GC stats, e.g. add this params when executing:

java9+ -Xlog:gc -Xlog:gc+ergo -Xlog:gc+stats
java8: -XX:+PrintGCDetails -verbose:gc

It should tell you how much memory is used in each generation after each GC cycle.

**Comment by tomerz90** [comment]
So does 3MB makes sense? If so, can I reduce it somehow (besides lowering the level)?

**Comment by luben** [comment]
I am not sure lowering the level will help a lot. There is `ZstdDirectBufferCompressingStream` that is a little but harder to use but it does not allocate on the java side. The rest is how much the native library allocates per context. I will look if I can expose some knobs for tweaking it.

**Comment by luben** [comment]
The memory above (~512KB) is for the IO buffers in zstd. There are some other allocations for lookup tables so I can imagine it going to 3 MB per context. I will close this now as I can't help very much with it. I run the test and see 250MB max for the java heap, the rest is in the natively allocated buffers.
