### ISSUE TITLE
Performance Testing?

### ISSUE THREAD

**Issue by shakeelrao** [luben/zstd-jni#94]
I was wondering if there has been any benchmarks which compare the compression speeds of `zstd-jni` with pure `zstd`? I am in the process of creating a JMH benchmark to test dictionary compression, but thought I would ask here as well.

Thanks!

**Comment by luben** [comment]
Yes, it's part of the test suite. E,g. here is it running on Travis:

https://travis-ci.org/luben/zstd-jni/jobs/501286664 

but these numbers are not representative as the Travis is quite variable in terms of load and speed.

You can check the other CIs (click the badges in the README) or run the tests yourself and compare with local run of zstd.

In short - yes, there is some overhead, depending on the use case, e.g. in the DirectBuffers cases it's close to 0. There are also some copies going that are necessary to satisfy the Input/Output Stream interfaces.

**Comment by shakeelrao** [comment]
Thanks! I'm current benchmarking dictionary compression and I'm noticing significantly different results.

For instance, the CLI benchmark outputs `571.0 MB/s` compression speed, while the benchmark outputs `40 MB/s` for the same file, dictionary, and compression level. 

For reference, I'm benchmarking `compress(byte[] dst, byte[] src, byte[] dict, int level)`.

**Comment by luben** [comment]
yes, sure. All the compress methods copy the data back and forward, also allocate new compression context for each request - it can be a huge difference. There is a new API that can improve these numbers by reusing the contex. What level are you benchmaring? 40 MB/s seems too low. Have you tries to use the fast dictionaries - they can give you a big boost. Also, the zstd CLI benchmark is using the streaming protocol.

**Comment by shakeelrao** [comment]
Ah, ok. I'll look into the API a bit more first. I'm actually using a compress level of 3.

**Comment by luben** [comment]
yes, try using `compress(ByteBuffer dstBuff, ByteBuffer srcBuff, ZstdDictCompress dict)` - it will not copy the dictionary on each invocation.

**Comment by shakeelrao** [comment]
By using `ZstdDictCompress`, I'm getting around 200 MB/s on level 3 now, which seems pretty good. By looking at the JNI code, it seems like we create a new context for each call, which may explain the difference.

**Comment by luben** [comment]
Yes, recently `compressCtx` function was added - I intend to expose it in one of the next versions.
