### ISSUE TITLE
Simple test fails with 1.3.8-6: java.io.IOException: Read error or truncated source

### ISSUE THREAD

**Issue by skunkiferous** [luben/zstd-jni#95]
Hi. I've just tried using your package for the first time, and got an error, while replacing our ancient GZip code. Fortunately, a simple test directly reproduces the error.

OS: Windows 10 x64
java version "1.8.0_191"
Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.191-b12, mixed mode)

MVN:
```
<dependency>
    <groupId>com.github.luben</groupId>
    <artifactId>zstd-jni</artifactId>
    <version>1.3.8-6</version>
</dependency>

```
TEST: [gist](https://gist.github.com/skunkiferous/36d9924ad6dc6cbb54f182e21e127359)

Am I doing anything wrong? The same code worked with the standard GZIP streams of the JRE.

The two differences I see, is "ZstdInputStream" doesn't take a size parameter, and "ZstdOutputStream" doesn't support "finish", like GZIPOutputStream (I don't even understand the purpose of "finish"; it was coded "before my time"...)

**Comment by luben** [comment]
Yes, there is no `finish` but `flush` (that is part of OutputStream interface) + `setCloseFrameOnFlush(true)` should do the same. Also for `ZstdInputStream`, the buffer size is allocated dinamically - you can't influence it through the `size` param.

**Comment by luben** [comment]
Going over your gist:
```
 zout = new ZstdOutputStream(bout, 10000);
```
There is no compression level 10000, please consult the docs: https://www.javadoc.io/doc/com.github.luben/zstd-jni/1.3.8-6

You don't need to specify the buffer sizes - they are picked automatically depending on compression level.

**Comment by luben** [comment]
Going again over your code - you are getting the output buffer before closing  the compression stream, so the frame end is not written, you should move the line 54 above line 53. If you want to achive the same as `finish` in `GZIPOutputStream`, use `setCloseFrameOnFlush` and then `flush` will do the same as `finish`, BTW this is the same as using `syncFlush` option for `GZIPOutputStream`
