### ISSUE TITLE
Read error (39) : premature end

### ISSUE THREAD

**Issue by julien-pcd** [luben/zstd-jni#97]
Using the new multi threading compression option, the generated compressed file is invalid. Attempting to decompress it yields the "Read error(39): premature end" error.

I'm guessing it might be due to this Zstandard bug, with a fix provided 4 days ago:
https://github.com/facebook/zstd/commit/48a6427d22f290157b8acc3f7c03c0f762a768be

If this is the case, this means using setWorkers should be avoided until an updated version of Zstandard is included with the library. Or no longer compiling with ZSTD_MULTITHREAD.

Can you confirm this bug?

**Comment by luben** [comment]
I think this may be the underlying issue - there is a lot of movement around the ZSTD advanced API and I hope the will be fixed for the next release. I add tests and will start migrating to the /dev branch in order to test early the next release.

**Comment by luben** [comment]
Relevant: https://github.com/facebook/zstd/issues/1584

As I understand the plan is to have next Zstd release tomorrow, so we can get the fix quite fast.

**Comment by luben** [comment]
Looked at the /dev branch of Zstd and it looks there are quite a few changes there. I have found how to fix it on 1.3.8 branch and will release v1.3.8-9 shortly.

**Comment by luben** [comment]
I pushed it to Maven central, it should arrive shortly. Can you confirm that it solves your issue - I have added tests but second confirmation is always better.

**Comment by julien-pcd** [comment]
Looks like it works. Thanks for the quick turnaround!
